// ============================================================================
//  sha_api.h  —  SHA-512/256 MCDMA driver API declarations
//  Target board : Avnet Ultra96-V2  (xczu3eg-sbva484-1-i)
//  Tool         : Vitis 2024.2
//
//  This file declares all worker functions implemented in sha_api.c.
//  User code only needs to #include this single header — it pulls in
//  sha_config.h and all required Xilinx/BSP headers automatically.
//
//  USAGE PATTERN (in main_user.c):
//
//    #include "sha_api.h"
//
//    int main(void) {
//        sha_system_init();           // step 1: init hardware
//        run_selected_sha_ip(0);      // step 2: run IP 0, 1, 2, or 3
//        return XST_SUCCESS;
//    }
//
//  CALL ORDER (enforced internally by run_selected_sha_ip):
//    1. mcdma_init()              — initialize MCDMA driver
//    2. setup_one_channel()       — create BD rings for selected channel
//    3. XMcDma_ChanSubmit RX      — arm S2MM before anything else
//    4. sha_start()               — program IP registers + ap_start
//    5. XMcDma_ChanSubmit TX      — send message data via MM2S
//    6. wait_for_dma_done()       — poll until TX and RX both complete
//    7. print_digest()            — print received digest to UART
// ============================================================================

#ifndef SHA_API_H
#define SHA_API_H

// ============================================================
//  SECTION 1 — System includes
//  All Xilinx BSP and stdlib headers needed by sha_api.c are
//  pulled in here so main_user.c stays clean with one include.
// ============================================================
#include "xparameters.h"
#include "xil_io.h"
#include "xil_printf.h"
#include "xil_cache.h"
#include "xstatus.h"
#include "xmcdma.h"
#include "xmcdma_hw.h"
#include "xmcdma_bd.h"
#include "sleep.h"
#include <string.h>

#ifdef __aarch64__
#include "xil_mmu.h"
#endif

// ============================================================
//  SECTION 2 — HLS generated register map header
//  Generated by Vitis HLS export. Located in BSP at:
//    drivers/test_v1_0/src/xtest_hw.h
//  Provides:
//    XTEST_CONTROL_ADDR_AP_CTRL
//    XTEST_CONTROL_ADDR_MSG_LEN_DATA
//    XTEST_CONTROL_ADDR_DEST_ID_DATA
// ============================================================
#include "xtest_hw.h"

// ============================================================
//  SECTION 3 — Project configuration header
//  All #define constants: addresses, buffer sizes, timeouts.
//  Update sha_config.h when Vivado address map changes.
// ============================================================
#include "sha_config.h"

// ============================================================
//  SECTION 4 — Function declarations
//
//  These are implemented in sha_api.c.
//  User code calls only mcdma_init() and run_selected_sha_ip()
//  directly. All other functions are used internally by
//  run_selected_sha_ip() but are exposed here for debug use.
// ============================================================

/**
 * print_digest() — Print a 32-byte SHA-512/256 digest to UART
 *
 * @param digest  pointer to 32-byte (DIGEST_BYTES) buffer
 *
 * Prints "Digest = <64 hex chars>\r\n" via xil_printf.
 * Called after wait_for_dma_done() completes successfully.
 */
void print_digest(const u8 *digest);

/**
 * get_tx_len() — Round message length up to 8-byte AXI word boundary
 *
 * @param msg_len  message length in bytes
 * @return         padded length: ceil(msg_len / 8) * 8
 *
 * MCDMA MM2S transfers in 64-bit (8-byte) words. The TX buffer
 * must be sized to a multiple of 8 bytes or the last partial
 * word is never sent and the SHA IP stalls waiting for TLAST.
 */
u32 get_tx_len(u32 msg_len);

/**
 * get_sha_base() — Resolve AXI-Lite base address for selected IP
 *
 * @param ip_select  IP index: 0 = test_0, 1 = test_1,
 *                             2 = test_2, 3 = test_3
 * @return           AXI-Lite base address (SHA0–3_BASEADDR)
 *
 * Returns the correct base from sha_config.h for register
 * writes in sha_start(). Returns SHA3_BASEADDR for any
 * ip_select > 2 (validated upstream by run_selected_sha_ip).
 */
UINTPTR get_sha_base(u32 ip_select);

/**
 * sha_start() — Program SHA HLS IP registers and assert ap_start
 *
 * @param sha_base  AXI-Lite base address of the target IP
 * @param msg_len   message length in bytes (written to msg_len reg)
 * @param dest_id   TDEST value written to dest_id reg (0–3)
 *                  routes digest to correct MCDMA S2MM channel
 *
 * Write order:
 *   1. msg_len  (4 × 32-bit writes covering 128-bit register)
 *   2. dest_id  (32-bit write, only lower 2 bits used)
 *   3. ap_start (bit 0 of ap_ctrl register)
 *
 * Must be called AFTER RX is armed and BEFORE TX is submitted.
 */
void sha_start(UINTPTR sha_base, u32 msg_len, u32 dest_id);

/**
 * mcdma_init() — Initialize the AXI MCDMA driver
 *
 * @return  XST_SUCCESS on success, XST_FAILURE on error
 *
 * Looks up the MCDMA hardware config from xparameters.h and
 * calls XMcDma_CfgInitialize(). Prints channel count, data
 * widths, and max transfer length to UART for verification.
 * Must be called once from main() before any channel setup.
 */
int mcdma_init(void);

/**
 * setup_one_channel() — Create BD rings for one MCDMA channel
 *
 * @param chan_id     channel number 1-based (1 = IP0 ... 4 = IP3)
 * @param TxChanOut   output pointer to TX channel control struct
 * @param RxChanOut   output pointer to RX channel control struct
 * @return            XST_SUCCESS or XST_FAILURE
 *
 * Selects the correct non-cacheable BD base addresses from
 * sha_config.h for the given chan_id, creates TX and RX BD
 * rings with BD_COUNT descriptors each, and disables interrupts
 * (polled mode). Must be called before ChanSubmit calls.
 */
int setup_one_channel(u32 chan_id,
                      XMcdma_ChanCtrl **TxChanOut,
                      XMcdma_ChanCtrl **RxChanOut);

/**
 * wait_for_dma_done() — Poll until TX and RX both complete
 *
 * @param TxChan  TX channel control struct from setup_one_channel
 * @param RxChan  RX channel control struct from setup_one_channel
 * @param RxBuf   pointer to RX data buffer (cache-invalidated on done)
 * @return        XST_SUCCESS or XST_FAILURE (timeout)
 *
 * Polls XMcdma_BdChainFromHW() for both TX and RX independently
 * up to TIMEOUT_COUNT iterations. On RX completion, invalidates
 * the RX buffer cache range so CPU sees the fresh digest bytes.
 * On timeout, dumps channel registers via XMcdma_DumpChanRegs()
 * for diagnosis.
 */
int wait_for_dma_done(XMcdma_ChanCtrl *TxChan,
                      XMcdma_ChanCtrl *RxChan,
                      u8 *RxBuf);

/**
 * run_selected_sha_ip() — Top-level single-IP test function
 *
 * @param ip_select  IP to test: 0 = test_0 ... 3 = test_3
 * @return           XST_SUCCESS or XST_FAILURE
 *
 * Orchestrates the full test sequence for one SHA IP:
 *   1. Validates ip_select range (0–3)
 *   2. Resolves chan_id, dest_id, sha_base, buffer addresses
 *   3. Calls setup_one_channel()
 *   4. Prepares TX buffer (memset + memcpy + cache flush)
 *   5. Arms RX (ChanSubmit + ChanToHw)
 *   6. Starts SHA IP (sha_start)
 *   7. Submits TX (ChanSubmit + BdSetCtrl + ChanToHw)
 *   8. Waits for completion (wait_for_dma_done)
 *   9. Prints digest and expected value for comparison
 *
 * This is the only function main_user.c needs to call after
 * mcdma_init().
 */
int run_selected_sha_ip(u32 ip_select);

#endif /* SHA_API_H */