# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==design_1_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_mcdma_0_0/design_1_axi_mcdma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_mcdma_0_0 || ORIG_REF_NAME==design_1_axi_mcdma_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_test_0_0/design_1_test_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_test_0_0 || ORIG_REF_NAME==design_1_test_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_test_1_0/design_1_test_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_test_1_0 || ORIG_REF_NAME==design_1_test_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_test_2_0/design_1_test_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_test_2_0 || ORIG_REF_NAME==design_1_test_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_test_3_0/design_1_test_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_test_3_0 || ORIG_REF_NAME==design_1_test_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_switch_0_0/design_1_axis_switch_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axis_switch_0_0 || ORIG_REF_NAME==design_1_axis_switch_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_switch_1_0/design_1_axis_switch_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axis_switch_1_0 || ORIG_REF_NAME==design_1_axis_switch_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_smc_0/design_1_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_smc_0 || ORIG_REF_NAME==design_1_axi_smc_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_ps8_0_100M_0/design_1_rst_ps8_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_ps8_0_100M_0 || ORIG_REF_NAME==design_1_rst_ps8_0_100M_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_smc_1_0/design_1_axi_smc_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_smc_1_0 || ORIG_REF_NAME==design_1_axi_smc_1_0} -quiet] -quiet

# XDC: d:/Nilesh_3/Vivado/project_1/project_1.gen/sources_1/bd/design_1/design_1_ooc.xdc
