// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="test_test,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu3eg-sbva484-1-i,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=7.686488,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=4,HLS_SYN_DSP=0,HLS_SYN_FF=11208,HLS_SYN_LUT=9567,HLS_VERSION=2024_2}" *)

module test (
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        ap_clk,
        ap_rst_n,
        interrupt,
        msg_strm_TDATA,
        msg_strm_TKEEP,
        msg_strm_TSTRB,
        msg_strm_TLAST,
        msg_strm_TDEST,
        digest_strm_TDATA,
        digest_strm_TKEEP,
        digest_strm_TSTRB,
        digest_strm_TLAST,
        digest_strm_TDEST,
        msg_strm_TVALID,
        msg_strm_TREADY,
        digest_strm_TVALID,
        digest_strm_TREADY
);

parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
input   ap_clk;
input   ap_rst_n;
output   interrupt;
input  [63:0] msg_strm_TDATA;
input  [7:0] msg_strm_TKEEP;
input  [7:0] msg_strm_TSTRB;
input  [0:0] msg_strm_TLAST;
input  [2:0] msg_strm_TDEST;
output  [255:0] digest_strm_TDATA;
output  [31:0] digest_strm_TKEEP;
output  [31:0] digest_strm_TSTRB;
output  [0:0] digest_strm_TLAST;
output  [2:0] digest_strm_TDEST;
input   msg_strm_TVALID;
output   msg_strm_TREADY;
output   digest_strm_TVALID;
input   digest_strm_TREADY;

 reg    ap_rst_n_inv;
wire   [127:0] msg_len;
wire   [1:0] dest_id;
wire    ap_start;
wire    ap_ready;
wire    ap_done;
wire    ap_idle;
wire    entry_proc_U0_ap_start;
wire    entry_proc_U0_ap_done;
wire    entry_proc_U0_ap_continue;
wire    entry_proc_U0_ap_idle;
wire    entry_proc_U0_ap_ready;
wire    entry_proc_U0_start_out;
wire    entry_proc_U0_start_write;
wire   [1:0] entry_proc_U0_dest_id_c_din;
wire    entry_proc_U0_dest_id_c_write;
wire    axis_to_core_U0_ap_start;
wire    axis_to_core_U0_ap_done;
wire    axis_to_core_U0_ap_continue;
wire    axis_to_core_U0_ap_idle;
wire    axis_to_core_U0_ap_ready;
wire    axis_to_core_U0_start_out;
wire    axis_to_core_U0_start_write;
wire    axis_to_core_U0_msg_strm_TREADY;
wire   [63:0] axis_to_core_U0_core_msg_strm_din;
wire    axis_to_core_U0_core_msg_strm_write;
wire   [127:0] axis_to_core_U0_core_len_strm_din;
wire    axis_to_core_U0_core_len_strm_write;
wire   [0:0] axis_to_core_U0_core_end_len_strm_din;
wire    axis_to_core_U0_core_end_len_strm_write;
wire    sha512_t_64u_256u_U0_ap_start;
wire    sha512_t_64u_256u_U0_ap_done;
wire    sha512_t_64u_256u_U0_ap_continue;
wire    sha512_t_64u_256u_U0_ap_idle;
wire    sha512_t_64u_256u_U0_ap_ready;
wire    sha512_t_64u_256u_U0_core_msg_strm_read;
wire    sha512_t_64u_256u_U0_core_len_strm_read;
wire    sha512_t_64u_256u_U0_core_end_len_strm_read;
wire   [255:0] sha512_t_64u_256u_U0_core_digest_strm_din;
wire    sha512_t_64u_256u_U0_core_digest_strm_write;
wire   [0:0] sha512_t_64u_256u_U0_core_end_digest_strm_din;
wire    sha512_t_64u_256u_U0_core_end_digest_strm_write;
wire    core_to_axis_U0_ap_start;
wire    core_to_axis_U0_ap_done;
wire    core_to_axis_U0_ap_continue;
wire    core_to_axis_U0_ap_idle;
wire    core_to_axis_U0_ap_ready;
wire    core_to_axis_U0_core_digest_strm_read;
wire    core_to_axis_U0_core_end_digest_strm_read;
wire   [255:0] core_to_axis_U0_digest_strm_TDATA;
wire    core_to_axis_U0_digest_strm_TVALID;
wire   [31:0] core_to_axis_U0_digest_strm_TKEEP;
wire   [31:0] core_to_axis_U0_digest_strm_TSTRB;
wire   [0:0] core_to_axis_U0_digest_strm_TLAST;
wire   [2:0] core_to_axis_U0_digest_strm_TDEST;
wire    core_to_axis_U0_dest_id_read;
wire    dest_id_c_full_n;
wire   [1:0] dest_id_c_dout;
wire    dest_id_c_empty_n;
wire   [2:0] dest_id_c_num_data_valid;
wire   [2:0] dest_id_c_fifo_cap;
wire    core_msg_strm_full_n;
wire   [63:0] core_msg_strm_dout;
wire    core_msg_strm_empty_n;
wire   [6:0] core_msg_strm_num_data_valid;
wire   [6:0] core_msg_strm_fifo_cap;
wire    core_len_strm_full_n;
wire   [127:0] core_len_strm_dout;
wire    core_len_strm_empty_n;
wire   [2:0] core_len_strm_num_data_valid;
wire   [2:0] core_len_strm_fifo_cap;
wire    core_end_len_strm_full_n;
wire   [0:0] core_end_len_strm_dout;
wire    core_end_len_strm_empty_n;
wire   [2:0] core_end_len_strm_num_data_valid;
wire   [2:0] core_end_len_strm_fifo_cap;
wire    core_digest_strm_full_n;
wire   [255:0] core_digest_strm_dout;
wire    core_digest_strm_empty_n;
wire   [2:0] core_digest_strm_num_data_valid;
wire   [2:0] core_digest_strm_fifo_cap;
wire    core_end_digest_strm_full_n;
wire   [0:0] core_end_digest_strm_dout;
wire    core_end_digest_strm_empty_n;
wire   [2:0] core_end_digest_strm_num_data_valid;
wire   [2:0] core_end_digest_strm_fifo_cap;
wire    ap_sync_ready;
reg    ap_sync_reg_entry_proc_U0_ap_ready;
wire    ap_sync_entry_proc_U0_ap_ready;
reg    ap_sync_reg_axis_to_core_U0_ap_ready;
wire    ap_sync_axis_to_core_U0_ap_ready;
wire   [0:0] start_for_core_to_axis_U0_din;
wire    start_for_core_to_axis_U0_full_n;
wire   [0:0] start_for_core_to_axis_U0_dout;
wire    start_for_core_to_axis_U0_empty_n;
wire   [0:0] start_for_sha512_t_64u_256u_U0_din;
wire    start_for_sha512_t_64u_256u_U0_full_n;
wire   [0:0] start_for_sha512_t_64u_256u_U0_dout;
wire    start_for_sha512_t_64u_256u_U0_empty_n;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_sync_reg_entry_proc_U0_ap_ready = 1'b0;
#0 ap_sync_reg_axis_to_core_U0_ap_ready = 1'b0;
end

test_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .msg_len(msg_len),
    .dest_id(dest_id),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

test_entry_proc entry_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(entry_proc_U0_ap_start),
    .start_full_n(start_for_core_to_axis_U0_full_n),
    .ap_done(entry_proc_U0_ap_done),
    .ap_continue(entry_proc_U0_ap_continue),
    .ap_idle(entry_proc_U0_ap_idle),
    .ap_ready(entry_proc_U0_ap_ready),
    .start_out(entry_proc_U0_start_out),
    .start_write(entry_proc_U0_start_write),
    .dest_id(dest_id),
    .dest_id_c_din(entry_proc_U0_dest_id_c_din),
    .dest_id_c_full_n(dest_id_c_full_n),
    .dest_id_c_write(entry_proc_U0_dest_id_c_write),
    .dest_id_c_num_data_valid(dest_id_c_num_data_valid),
    .dest_id_c_fifo_cap(dest_id_c_fifo_cap)
);

test_axis_to_core axis_to_core_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(axis_to_core_U0_ap_start),
    .start_full_n(start_for_sha512_t_64u_256u_U0_full_n),
    .ap_done(axis_to_core_U0_ap_done),
    .ap_continue(axis_to_core_U0_ap_continue),
    .ap_idle(axis_to_core_U0_ap_idle),
    .ap_ready(axis_to_core_U0_ap_ready),
    .start_out(axis_to_core_U0_start_out),
    .start_write(axis_to_core_U0_start_write),
    .msg_strm_TDATA(msg_strm_TDATA),
    .msg_strm_TVALID(msg_strm_TVALID),
    .msg_strm_TREADY(axis_to_core_U0_msg_strm_TREADY),
    .msg_strm_TKEEP(msg_strm_TKEEP),
    .msg_strm_TSTRB(msg_strm_TSTRB),
    .msg_strm_TLAST(msg_strm_TLAST),
    .msg_strm_TDEST(msg_strm_TDEST),
    .msg_len(msg_len),
    .core_msg_strm_din(axis_to_core_U0_core_msg_strm_din),
    .core_msg_strm_full_n(core_msg_strm_full_n),
    .core_msg_strm_write(axis_to_core_U0_core_msg_strm_write),
    .core_msg_strm_num_data_valid(core_msg_strm_num_data_valid),
    .core_msg_strm_fifo_cap(core_msg_strm_fifo_cap),
    .core_len_strm_din(axis_to_core_U0_core_len_strm_din),
    .core_len_strm_full_n(core_len_strm_full_n),
    .core_len_strm_write(axis_to_core_U0_core_len_strm_write),
    .core_len_strm_num_data_valid(core_len_strm_num_data_valid),
    .core_len_strm_fifo_cap(core_len_strm_fifo_cap),
    .core_end_len_strm_din(axis_to_core_U0_core_end_len_strm_din),
    .core_end_len_strm_full_n(core_end_len_strm_full_n),
    .core_end_len_strm_write(axis_to_core_U0_core_end_len_strm_write),
    .core_end_len_strm_num_data_valid(core_end_len_strm_num_data_valid),
    .core_end_len_strm_fifo_cap(core_end_len_strm_fifo_cap)
);

test_sha512_t_64u_256u_s sha512_t_64u_256u_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(sha512_t_64u_256u_U0_ap_start),
    .ap_done(sha512_t_64u_256u_U0_ap_done),
    .ap_continue(sha512_t_64u_256u_U0_ap_continue),
    .ap_idle(sha512_t_64u_256u_U0_ap_idle),
    .ap_ready(sha512_t_64u_256u_U0_ap_ready),
    .core_msg_strm_dout(core_msg_strm_dout),
    .core_msg_strm_empty_n(core_msg_strm_empty_n),
    .core_msg_strm_read(sha512_t_64u_256u_U0_core_msg_strm_read),
    .core_msg_strm_num_data_valid(core_msg_strm_num_data_valid),
    .core_msg_strm_fifo_cap(core_msg_strm_fifo_cap),
    .core_len_strm_dout(core_len_strm_dout),
    .core_len_strm_empty_n(core_len_strm_empty_n),
    .core_len_strm_read(sha512_t_64u_256u_U0_core_len_strm_read),
    .core_len_strm_num_data_valid(core_len_strm_num_data_valid),
    .core_len_strm_fifo_cap(core_len_strm_fifo_cap),
    .core_end_len_strm_dout(core_end_len_strm_dout),
    .core_end_len_strm_empty_n(core_end_len_strm_empty_n),
    .core_end_len_strm_read(sha512_t_64u_256u_U0_core_end_len_strm_read),
    .core_end_len_strm_num_data_valid(core_end_len_strm_num_data_valid),
    .core_end_len_strm_fifo_cap(core_end_len_strm_fifo_cap),
    .core_digest_strm_din(sha512_t_64u_256u_U0_core_digest_strm_din),
    .core_digest_strm_full_n(core_digest_strm_full_n),
    .core_digest_strm_write(sha512_t_64u_256u_U0_core_digest_strm_write),
    .core_digest_strm_num_data_valid(core_digest_strm_num_data_valid),
    .core_digest_strm_fifo_cap(core_digest_strm_fifo_cap),
    .core_end_digest_strm_din(sha512_t_64u_256u_U0_core_end_digest_strm_din),
    .core_end_digest_strm_full_n(core_end_digest_strm_full_n),
    .core_end_digest_strm_write(sha512_t_64u_256u_U0_core_end_digest_strm_write),
    .core_end_digest_strm_num_data_valid(core_end_digest_strm_num_data_valid),
    .core_end_digest_strm_fifo_cap(core_end_digest_strm_fifo_cap)
);

test_core_to_axis core_to_axis_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(core_to_axis_U0_ap_start),
    .ap_done(core_to_axis_U0_ap_done),
    .ap_continue(core_to_axis_U0_ap_continue),
    .ap_idle(core_to_axis_U0_ap_idle),
    .ap_ready(core_to_axis_U0_ap_ready),
    .core_digest_strm_dout(core_digest_strm_dout),
    .core_digest_strm_empty_n(core_digest_strm_empty_n),
    .core_digest_strm_read(core_to_axis_U0_core_digest_strm_read),
    .core_digest_strm_num_data_valid(core_digest_strm_num_data_valid),
    .core_digest_strm_fifo_cap(core_digest_strm_fifo_cap),
    .core_end_digest_strm_dout(core_end_digest_strm_dout),
    .core_end_digest_strm_empty_n(core_end_digest_strm_empty_n),
    .core_end_digest_strm_read(core_to_axis_U0_core_end_digest_strm_read),
    .core_end_digest_strm_num_data_valid(core_end_digest_strm_num_data_valid),
    .core_end_digest_strm_fifo_cap(core_end_digest_strm_fifo_cap),
    .digest_strm_TDATA(core_to_axis_U0_digest_strm_TDATA),
    .digest_strm_TVALID(core_to_axis_U0_digest_strm_TVALID),
    .digest_strm_TREADY(digest_strm_TREADY),
    .digest_strm_TKEEP(core_to_axis_U0_digest_strm_TKEEP),
    .digest_strm_TSTRB(core_to_axis_U0_digest_strm_TSTRB),
    .digest_strm_TLAST(core_to_axis_U0_digest_strm_TLAST),
    .digest_strm_TDEST(core_to_axis_U0_digest_strm_TDEST),
    .dest_id_dout(dest_id_c_dout),
    .dest_id_empty_n(dest_id_c_empty_n),
    .dest_id_read(core_to_axis_U0_dest_id_read),
    .dest_id_num_data_valid(dest_id_c_num_data_valid),
    .dest_id_fifo_cap(dest_id_c_fifo_cap)
);

test_fifo_w2_d4_S dest_id_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_dest_id_c_din),
    .if_full_n(dest_id_c_full_n),
    .if_write(entry_proc_U0_dest_id_c_write),
    .if_dout(dest_id_c_dout),
    .if_empty_n(dest_id_c_empty_n),
    .if_read(core_to_axis_U0_dest_id_read),
    .if_num_data_valid(dest_id_c_num_data_valid),
    .if_fifo_cap(dest_id_c_fifo_cap)
);

test_fifo_w64_d64_A core_msg_strm_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(axis_to_core_U0_core_msg_strm_din),
    .if_full_n(core_msg_strm_full_n),
    .if_write(axis_to_core_U0_core_msg_strm_write),
    .if_dout(core_msg_strm_dout),
    .if_empty_n(core_msg_strm_empty_n),
    .if_read(sha512_t_64u_256u_U0_core_msg_strm_read),
    .if_num_data_valid(core_msg_strm_num_data_valid),
    .if_fifo_cap(core_msg_strm_fifo_cap)
);

test_fifo_w128_d4_S core_len_strm_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(axis_to_core_U0_core_len_strm_din),
    .if_full_n(core_len_strm_full_n),
    .if_write(axis_to_core_U0_core_len_strm_write),
    .if_dout(core_len_strm_dout),
    .if_empty_n(core_len_strm_empty_n),
    .if_read(sha512_t_64u_256u_U0_core_len_strm_read),
    .if_num_data_valid(core_len_strm_num_data_valid),
    .if_fifo_cap(core_len_strm_fifo_cap)
);

test_fifo_w1_d4_S core_end_len_strm_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(axis_to_core_U0_core_end_len_strm_din),
    .if_full_n(core_end_len_strm_full_n),
    .if_write(axis_to_core_U0_core_end_len_strm_write),
    .if_dout(core_end_len_strm_dout),
    .if_empty_n(core_end_len_strm_empty_n),
    .if_read(sha512_t_64u_256u_U0_core_end_len_strm_read),
    .if_num_data_valid(core_end_len_strm_num_data_valid),
    .if_fifo_cap(core_end_len_strm_fifo_cap)
);

test_fifo_w256_d4_S core_digest_strm_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(sha512_t_64u_256u_U0_core_digest_strm_din),
    .if_full_n(core_digest_strm_full_n),
    .if_write(sha512_t_64u_256u_U0_core_digest_strm_write),
    .if_dout(core_digest_strm_dout),
    .if_empty_n(core_digest_strm_empty_n),
    .if_read(core_to_axis_U0_core_digest_strm_read),
    .if_num_data_valid(core_digest_strm_num_data_valid),
    .if_fifo_cap(core_digest_strm_fifo_cap)
);

test_fifo_w1_d4_S core_end_digest_strm_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(sha512_t_64u_256u_U0_core_end_digest_strm_din),
    .if_full_n(core_end_digest_strm_full_n),
    .if_write(sha512_t_64u_256u_U0_core_end_digest_strm_write),
    .if_dout(core_end_digest_strm_dout),
    .if_empty_n(core_end_digest_strm_empty_n),
    .if_read(core_to_axis_U0_core_end_digest_strm_read),
    .if_num_data_valid(core_end_digest_strm_num_data_valid),
    .if_fifo_cap(core_end_digest_strm_fifo_cap)
);

test_start_for_core_to_axis_U0 start_for_core_to_axis_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_core_to_axis_U0_din),
    .if_full_n(start_for_core_to_axis_U0_full_n),
    .if_write(entry_proc_U0_start_write),
    .if_dout(start_for_core_to_axis_U0_dout),
    .if_empty_n(start_for_core_to_axis_U0_empty_n),
    .if_read(core_to_axis_U0_ap_ready)
);

test_start_for_sha512_t_64u_256u_U0 start_for_sha512_t_64u_256u_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_sha512_t_64u_256u_U0_din),
    .if_full_n(start_for_sha512_t_64u_256u_U0_full_n),
    .if_write(axis_to_core_U0_start_write),
    .if_dout(start_for_sha512_t_64u_256u_U0_dout),
    .if_empty_n(start_for_sha512_t_64u_256u_U0_empty_n),
    .if_read(sha512_t_64u_256u_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_axis_to_core_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_axis_to_core_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_axis_to_core_U0_ap_ready <= ap_sync_axis_to_core_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_entry_proc_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_entry_proc_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_entry_proc_U0_ap_ready <= ap_sync_entry_proc_U0_ap_ready;
        end
    end
end

assign ap_done = core_to_axis_U0_ap_done;

assign ap_idle = (sha512_t_64u_256u_U0_ap_idle & entry_proc_U0_ap_idle & core_to_axis_U0_ap_idle & axis_to_core_U0_ap_idle);

assign ap_ready = ap_sync_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_axis_to_core_U0_ap_ready = (axis_to_core_U0_ap_ready | ap_sync_reg_axis_to_core_U0_ap_ready);

assign ap_sync_entry_proc_U0_ap_ready = (entry_proc_U0_ap_ready | ap_sync_reg_entry_proc_U0_ap_ready);

assign ap_sync_ready = (ap_sync_entry_proc_U0_ap_ready & ap_sync_axis_to_core_U0_ap_ready);

assign axis_to_core_U0_ap_continue = 1'b1;

assign axis_to_core_U0_ap_start = ((ap_sync_reg_axis_to_core_U0_ap_ready ^ 1'b1) & ap_start);

assign core_to_axis_U0_ap_continue = 1'b1;

assign core_to_axis_U0_ap_start = start_for_core_to_axis_U0_empty_n;

assign digest_strm_TDATA = core_to_axis_U0_digest_strm_TDATA;

assign digest_strm_TDEST = core_to_axis_U0_digest_strm_TDEST;

assign digest_strm_TKEEP = core_to_axis_U0_digest_strm_TKEEP;

assign digest_strm_TLAST = core_to_axis_U0_digest_strm_TLAST;

assign digest_strm_TSTRB = core_to_axis_U0_digest_strm_TSTRB;

assign digest_strm_TVALID = core_to_axis_U0_digest_strm_TVALID;

assign entry_proc_U0_ap_continue = 1'b1;

assign entry_proc_U0_ap_start = ((ap_sync_reg_entry_proc_U0_ap_ready ^ 1'b1) & ap_start);

assign msg_strm_TREADY = axis_to_core_U0_msg_strm_TREADY;

assign sha512_t_64u_256u_U0_ap_continue = 1'b1;

assign sha512_t_64u_256u_U0_ap_start = start_for_sha512_t_64u_256u_U0_empty_n;

assign start_for_core_to_axis_U0_din = 1'b1;

assign start_for_sha512_t_64u_256u_U0_din = 1'b1;


reg find_df_deadlock = 0;
// synthesis translate_off
`include "test_hls_deadlock_detector.vh"
// synthesis translate_on

reg find_kernel_block = 0;
// synthesis translate_off
`include "test_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //test

