// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module test_axis_to_core (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        msg_strm_TDATA,
        msg_strm_TVALID,
        msg_strm_TREADY,
        msg_strm_TKEEP,
        msg_strm_TSTRB,
        msg_strm_TLAST,
        msg_strm_TDEST,
        msg_len,
        core_msg_strm_din,
        core_msg_strm_full_n,
        core_msg_strm_write,
        core_msg_strm_num_data_valid,
        core_msg_strm_fifo_cap,
        core_len_strm_din,
        core_len_strm_full_n,
        core_len_strm_write,
        core_len_strm_num_data_valid,
        core_len_strm_fifo_cap,
        core_end_len_strm_din,
        core_end_len_strm_full_n,
        core_end_len_strm_write,
        core_end_len_strm_num_data_valid,
        core_end_len_strm_fifo_cap
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [63:0] msg_strm_TDATA;
input   msg_strm_TVALID;
output   msg_strm_TREADY;
input  [7:0] msg_strm_TKEEP;
input  [7:0] msg_strm_TSTRB;
input  [0:0] msg_strm_TLAST;
input  [2:0] msg_strm_TDEST;
input  [127:0] msg_len;
output  [63:0] core_msg_strm_din;
input   core_msg_strm_full_n;
output   core_msg_strm_write;
input  [6:0] core_msg_strm_num_data_valid;
input  [6:0] core_msg_strm_fifo_cap;
output  [127:0] core_len_strm_din;
input   core_len_strm_full_n;
output   core_len_strm_write;
input  [2:0] core_len_strm_num_data_valid;
input  [2:0] core_len_strm_fifo_cap;
output  [0:0] core_end_len_strm_din;
input   core_end_len_strm_full_n;
output   core_end_len_strm_write;
input  [2:0] core_end_len_strm_num_data_valid;
input  [2:0] core_end_len_strm_fifo_cap;

reg ap_done;
reg ap_idle;
reg start_write;
reg core_len_strm_write;
reg[0:0] core_end_len_strm_din;
reg core_end_len_strm_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    core_len_strm_blk_n;
reg    core_end_len_strm_blk_n;
wire    ap_CS_fsm_state4;
reg   [125:0] trunc_ln_reg_164;
reg    ap_block_state1;
wire    grp_axis_to_core_Pipeline_FEED_LOOP_fu_85_ap_start;
wire    grp_axis_to_core_Pipeline_FEED_LOOP_fu_85_ap_done;
wire    grp_axis_to_core_Pipeline_FEED_LOOP_fu_85_ap_idle;
wire    grp_axis_to_core_Pipeline_FEED_LOOP_fu_85_ap_ready;
wire   [63:0] grp_axis_to_core_Pipeline_FEED_LOOP_fu_85_core_msg_strm_din;
wire    grp_axis_to_core_Pipeline_FEED_LOOP_fu_85_core_msg_strm_write;
wire    grp_axis_to_core_Pipeline_FEED_LOOP_fu_85_msg_strm_TREADY;
reg    grp_axis_to_core_Pipeline_FEED_LOOP_fu_85_ap_start_reg;
reg   [3:0] ap_NS_fsm;
wire    ap_NS_fsm_state2;
wire    ap_CS_fsm_state3;
wire   [128:0] zext_ln65_fu_102_p1;
wire   [128:0] add_ln65_fu_106_p2;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    regslice_both_msg_strm_V_data_V_U_apdone_blk;
wire   [63:0] msg_strm_TDATA_int_regslice;
wire    msg_strm_TVALID_int_regslice;
reg    msg_strm_TREADY_int_regslice;
wire    regslice_both_msg_strm_V_data_V_U_ack_in;
wire    regslice_both_msg_strm_V_keep_V_U_apdone_blk;
wire   [7:0] msg_strm_TKEEP_int_regslice;
wire    regslice_both_msg_strm_V_keep_V_U_vld_out;
wire    regslice_both_msg_strm_V_keep_V_U_ack_in;
wire    regslice_both_msg_strm_V_strb_V_U_apdone_blk;
wire   [7:0] msg_strm_TSTRB_int_regslice;
wire    regslice_both_msg_strm_V_strb_V_U_vld_out;
wire    regslice_both_msg_strm_V_strb_V_U_ack_in;
wire    regslice_both_msg_strm_V_last_V_U_apdone_blk;
wire   [0:0] msg_strm_TLAST_int_regslice;
wire    regslice_both_msg_strm_V_last_V_U_vld_out;
wire    regslice_both_msg_strm_V_last_V_U_ack_in;
wire    regslice_both_msg_strm_V_dest_V_U_apdone_blk;
wire   [2:0] msg_strm_TDEST_int_regslice;
wire    regslice_both_msg_strm_V_dest_V_U_vld_out;
wire    regslice_both_msg_strm_V_dest_V_U_ack_in;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 grp_axis_to_core_Pipeline_FEED_LOOP_fu_85_ap_start_reg = 1'b0;
end

test_axis_to_core_Pipeline_FEED_LOOP grp_axis_to_core_Pipeline_FEED_LOOP_fu_85(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_axis_to_core_Pipeline_FEED_LOOP_fu_85_ap_start),
    .ap_done(grp_axis_to_core_Pipeline_FEED_LOOP_fu_85_ap_done),
    .ap_idle(grp_axis_to_core_Pipeline_FEED_LOOP_fu_85_ap_idle),
    .ap_ready(grp_axis_to_core_Pipeline_FEED_LOOP_fu_85_ap_ready),
    .msg_strm_TVALID(msg_strm_TVALID_int_regslice),
    .core_msg_strm_din(grp_axis_to_core_Pipeline_FEED_LOOP_fu_85_core_msg_strm_din),
    .core_msg_strm_full_n(core_msg_strm_full_n),
    .core_msg_strm_write(grp_axis_to_core_Pipeline_FEED_LOOP_fu_85_core_msg_strm_write),
    .core_msg_strm_num_data_valid(7'd0),
    .core_msg_strm_fifo_cap(7'd0),
    .trunc_ln(trunc_ln_reg_164),
    .msg_strm_TDATA(msg_strm_TDATA_int_regslice),
    .msg_strm_TREADY(grp_axis_to_core_Pipeline_FEED_LOOP_fu_85_msg_strm_TREADY),
    .msg_strm_TKEEP(msg_strm_TKEEP_int_regslice),
    .msg_strm_TSTRB(msg_strm_TSTRB_int_regslice),
    .msg_strm_TLAST(msg_strm_TLAST_int_regslice),
    .msg_strm_TDEST(msg_strm_TDEST_int_regslice)
);

test_regslice_both #(
    .DataWidth( 64 ))
regslice_both_msg_strm_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(msg_strm_TDATA),
    .vld_in(msg_strm_TVALID),
    .ack_in(regslice_both_msg_strm_V_data_V_U_ack_in),
    .data_out(msg_strm_TDATA_int_regslice),
    .vld_out(msg_strm_TVALID_int_regslice),
    .ack_out(msg_strm_TREADY_int_regslice),
    .apdone_blk(regslice_both_msg_strm_V_data_V_U_apdone_blk)
);

test_regslice_both #(
    .DataWidth( 8 ))
regslice_both_msg_strm_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(msg_strm_TKEEP),
    .vld_in(msg_strm_TVALID),
    .ack_in(regslice_both_msg_strm_V_keep_V_U_ack_in),
    .data_out(msg_strm_TKEEP_int_regslice),
    .vld_out(regslice_both_msg_strm_V_keep_V_U_vld_out),
    .ack_out(msg_strm_TREADY_int_regslice),
    .apdone_blk(regslice_both_msg_strm_V_keep_V_U_apdone_blk)
);

test_regslice_both #(
    .DataWidth( 8 ))
regslice_both_msg_strm_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(msg_strm_TSTRB),
    .vld_in(msg_strm_TVALID),
    .ack_in(regslice_both_msg_strm_V_strb_V_U_ack_in),
    .data_out(msg_strm_TSTRB_int_regslice),
    .vld_out(regslice_both_msg_strm_V_strb_V_U_vld_out),
    .ack_out(msg_strm_TREADY_int_regslice),
    .apdone_blk(regslice_both_msg_strm_V_strb_V_U_apdone_blk)
);

test_regslice_both #(
    .DataWidth( 1 ))
regslice_both_msg_strm_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(msg_strm_TLAST),
    .vld_in(msg_strm_TVALID),
    .ack_in(regslice_both_msg_strm_V_last_V_U_ack_in),
    .data_out(msg_strm_TLAST_int_regslice),
    .vld_out(regslice_both_msg_strm_V_last_V_U_vld_out),
    .ack_out(msg_strm_TREADY_int_regslice),
    .apdone_blk(regslice_both_msg_strm_V_last_V_U_apdone_blk)
);

test_regslice_both #(
    .DataWidth( 3 ))
regslice_both_msg_strm_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(msg_strm_TDEST),
    .vld_in(msg_strm_TVALID),
    .ack_in(regslice_both_msg_strm_V_dest_V_U_ack_in),
    .data_out(msg_strm_TDEST_int_regslice),
    .vld_out(regslice_both_msg_strm_V_dest_V_U_vld_out),
    .ack_out(msg_strm_TREADY_int_regslice),
    .apdone_blk(regslice_both_msg_strm_V_dest_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((core_end_len_strm_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_axis_to_core_Pipeline_FEED_LOOP_fu_85_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (1'b1 == ap_NS_fsm_state2))) begin
            grp_axis_to_core_Pipeline_FEED_LOOP_fu_85_ap_start_reg <= 1'b1;
        end else if ((grp_axis_to_core_Pipeline_FEED_LOOP_fu_85_ap_ready == 1'b1)) begin
            grp_axis_to_core_Pipeline_FEED_LOOP_fu_85_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        trunc_ln_reg_164 <= {{add_ln65_fu_106_p2[128:3]}};
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_axis_to_core_Pipeline_FEED_LOOP_fu_85_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((core_end_len_strm_full_n == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((core_end_len_strm_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        core_end_len_strm_blk_n = core_end_len_strm_full_n;
    end else begin
        core_end_len_strm_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((core_end_len_strm_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        core_end_len_strm_din = 1'd1;
    end else if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        core_end_len_strm_din = 1'd0;
    end else begin
        core_end_len_strm_din = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1)) | ((core_end_len_strm_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state4)))) begin
        core_end_len_strm_write = 1'b1;
    end else begin
        core_end_len_strm_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        core_len_strm_blk_n = core_len_strm_full_n;
    end else begin
        core_len_strm_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        core_len_strm_write = 1'b1;
    end else begin
        core_len_strm_write = 1'b0;
    end
end

always @ (*) begin
    if (((core_end_len_strm_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        msg_strm_TREADY_int_regslice = grp_axis_to_core_Pipeline_FEED_LOOP_fu_85_msg_strm_TREADY;
    end else begin
        msg_strm_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_axis_to_core_Pipeline_FEED_LOOP_fu_85_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((core_end_len_strm_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln65_fu_106_p2 = (zext_ln65_fu_102_p1 + 129'd7);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_NS_fsm_state2 = ap_NS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((core_end_len_strm_full_n == 1'b0) | (core_len_strm_full_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign core_len_strm_din = msg_len;

assign core_msg_strm_din = grp_axis_to_core_Pipeline_FEED_LOOP_fu_85_core_msg_strm_din;

assign core_msg_strm_write = grp_axis_to_core_Pipeline_FEED_LOOP_fu_85_core_msg_strm_write;

assign grp_axis_to_core_Pipeline_FEED_LOOP_fu_85_ap_start = grp_axis_to_core_Pipeline_FEED_LOOP_fu_85_ap_start_reg;

assign msg_strm_TREADY = regslice_both_msg_strm_V_data_V_U_ack_in;

assign start_out = real_start;

assign zext_ln65_fu_102_p1 = msg_len;

endmodule //test_axis_to_core
