// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module test_preProcessing_64u_Pipeline_LOOP_COPY_TAIL_AND_PAD_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        core_msg_strm_dout,
        core_msg_strm_empty_n,
        core_msg_strm_read,
        core_msg_strm_num_data_valid,
        core_msg_strm_fifo_cap,
        shr_i2380_cast,
        len,
        b_13_out,
        b_13_out_ap_vld,
        b_12_out,
        b_12_out_ap_vld,
        b_11_out,
        b_11_out_ap_vld,
        b_10_out,
        b_10_out_ap_vld,
        b_9_out,
        b_9_out_ap_vld,
        b_8_out,
        b_8_out_ap_vld,
        b_7_out,
        b_7_out_ap_vld,
        b_6_out,
        b_6_out_ap_vld,
        b_5_out,
        b_5_out_ap_vld,
        b_4_out,
        b_4_out_ap_vld,
        b_3_out,
        b_3_out_ap_vld,
        b_2_out,
        b_2_out_ap_vld,
        b_1_out,
        b_1_out_ap_vld,
        b_out,
        b_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] core_msg_strm_dout;
input   core_msg_strm_empty_n;
output   core_msg_strm_read;
input  [6:0] core_msg_strm_num_data_valid;
input  [6:0] core_msg_strm_fifo_cap;
input  [3:0] shr_i2380_cast;
input  [2:0] len;
output  [63:0] b_13_out;
output   b_13_out_ap_vld;
output  [63:0] b_12_out;
output   b_12_out_ap_vld;
output  [63:0] b_11_out;
output   b_11_out_ap_vld;
output  [63:0] b_10_out;
output   b_10_out_ap_vld;
output  [63:0] b_9_out;
output   b_9_out_ap_vld;
output  [63:0] b_8_out;
output   b_8_out_ap_vld;
output  [63:0] b_7_out;
output   b_7_out_ap_vld;
output  [63:0] b_6_out;
output   b_6_out_ap_vld;
output  [63:0] b_5_out;
output   b_5_out_ap_vld;
output  [63:0] b_4_out;
output   b_4_out_ap_vld;
output  [63:0] b_3_out;
output   b_3_out_ap_vld;
output  [63:0] b_2_out;
output   b_2_out_ap_vld;
output  [63:0] b_1_out;
output   b_1_out_ap_vld;
output  [63:0] b_out;
output   b_out_ap_vld;

reg ap_idle;
reg core_msg_strm_read;
reg b_13_out_ap_vld;
reg b_12_out_ap_vld;
reg b_11_out_ap_vld;
reg b_10_out_ap_vld;
reg b_9_out_ap_vld;
reg b_8_out_ap_vld;
reg b_7_out_ap_vld;
reg b_6_out_ap_vld;
reg b_5_out_ap_vld;
reg b_4_out_ap_vld;
reg b_3_out_ap_vld;
reg b_2_out_ap_vld;
reg b_1_out_ap_vld;
reg b_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
reg   [0:0] icmp_ln155_reg_1579;
reg   [0:0] icmp_ln164_reg_1583;
wire   [2:0] len_read_reg_1568;
reg    ap_predicate_op63_read_state2;
reg    ap_predicate_op99_read_state2;
reg    ap_predicate_op134_read_state2;
reg    ap_predicate_op168_read_state2;
reg    ap_predicate_op201_read_state2;
reg    ap_predicate_op233_read_state2;
reg    ap_predicate_op292_read_state2;
reg    ap_block_state2_pp0_stage0_iter1_grp1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln153_fu_412_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    core_msg_strm_blk_n;
wire    ap_block_pp0_stage0_grp1;
reg    ap_block_pp0_stage0_11001_grp1;
reg   [3:0] i_1_reg_1572;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln155_fu_424_p2;
wire   [0:0] icmp_ln164_fu_430_p2;
reg   [3:0] i_fu_168;
wire   [3:0] add_ln153_fu_418_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_i_1;
wire    ap_block_pp0_stage0;
reg   [63:0] b_fu_172;
wire   [63:0] b_20_fu_445_p8;
wire   [63:0] b_19_fu_537_p7;
wire   [63:0] b_18_fu_627_p6;
wire   [63:0] b_17_fu_715_p5;
wire   [63:0] b_16_fu_801_p4;
wire   [63:0] b_15_fu_885_p3;
wire   [63:0] b_21_fu_1037_p9;
wire   [63:0] l_24_fu_1206_p9;
reg   [63:0] b_1_fu_176;
reg   [63:0] b_2_fu_180;
reg   [63:0] b_3_fu_184;
reg   [63:0] b_4_fu_188;
reg   [63:0] b_5_fu_192;
reg   [63:0] b_6_fu_196;
reg   [63:0] b_7_fu_200;
reg   [63:0] b_8_fu_204;
reg   [63:0] b_9_fu_208;
reg   [63:0] b_10_fu_212;
reg   [63:0] b_11_fu_216;
reg   [63:0] b_12_fu_220;
reg   [63:0] b_13_fu_224;
reg    ap_block_pp0_stage0_01001_grp1;
wire   [7:0] trunc_ln214_fu_441_p1;
wire   [7:0] grp_fu_344_p4;
wire   [7:0] grp_fu_354_p4;
wire   [7:0] grp_fu_364_p4;
wire   [7:0] grp_fu_384_p4;
wire   [7:0] grp_fu_374_p4;
wire   [7:0] trunc_ln206_fu_533_p1;
wire   [7:0] trunc_ln198_fu_623_p1;
wire   [7:0] trunc_ln191_fu_711_p1;
wire   [7:0] trunc_ln184_fu_797_p1;
wire   [7:0] trunc_ln177_fu_881_p1;
wire   [7:0] trunc_ln223_fu_1033_p1;
wire   [7:0] grp_fu_394_p4;
wire   [7:0] empty_fu_1192_p1;
wire   [7:0] p_s_fu_1196_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_45;
reg    ap_condition_51;
reg    ap_condition_58;
reg    ap_condition_65;
reg    ap_condition_72;
reg    ap_condition_79;
reg    ap_condition_229;
reg    ap_condition_86;
reg    ap_condition_999;
reg    ap_condition_1026;
reg    ap_condition_1029;
reg    ap_condition_677;
reg    ap_condition_685;
reg    ap_condition_692;
reg    ap_condition_699;
reg    ap_condition_706;
reg    ap_condition_713;
reg    ap_condition_720;
reg    ap_condition_727;
reg    ap_condition_736;
reg    ap_condition_743;
reg    ap_condition_206;
reg    ap_condition_1054;
reg    ap_condition_1057;
reg    ap_condition_1060;
reg    ap_condition_1063;
reg    ap_condition_1066;
reg    ap_condition_1069;
reg    ap_condition_1072;
reg    ap_condition_1075;
reg    ap_condition_1078;
reg    ap_condition_1081;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 i_fu_168 = 4'd0;
#0 b_fu_172 = 64'd0;
#0 b_1_fu_176 = 64'd0;
#0 b_2_fu_180 = 64'd0;
#0 b_3_fu_184 = 64'd0;
#0 b_4_fu_188 = 64'd0;
#0 b_5_fu_192 = 64'd0;
#0 b_6_fu_196 = 64'd0;
#0 b_7_fu_200 = 64'd0;
#0 b_8_fu_204 = 64'd0;
#0 b_9_fu_208 = 64'd0;
#0 b_10_fu_212 = 64'd0;
#0 b_11_fu_216 = 64'd0;
#0 b_12_fu_220 = 64'd0;
#0 b_13_fu_224 = 64'd0;
#0 ap_done_reg = 1'b0;
end

test_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_999)) begin
        if ((icmp_ln155_reg_1579 == 1'd1)) begin
            b_10_fu_212 <= l_24_fu_1206_p9;
        end else if (((icmp_ln164_reg_1583 == 1'd1) & (icmp_ln155_reg_1579 == 1'd0))) begin
            b_10_fu_212 <= 64'd0;
        end else if ((1'b1 == ap_condition_86)) begin
            b_10_fu_212 <= b_21_fu_1037_p9;
        end else if ((1'b1 == ap_condition_229)) begin
            b_10_fu_212 <= 64'd9223372036854775808;
        end else if ((1'b1 == ap_condition_79)) begin
            b_10_fu_212 <= b_15_fu_885_p3;
        end else if ((1'b1 == ap_condition_72)) begin
            b_10_fu_212 <= b_16_fu_801_p4;
        end else if ((1'b1 == ap_condition_65)) begin
            b_10_fu_212 <= b_17_fu_715_p5;
        end else if ((1'b1 == ap_condition_58)) begin
            b_10_fu_212 <= b_18_fu_627_p6;
        end else if ((1'b1 == ap_condition_51)) begin
            b_10_fu_212 <= b_19_fu_537_p7;
        end else if ((1'b1 == ap_condition_45)) begin
            b_10_fu_212 <= b_20_fu_445_p8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1026)) begin
        if ((icmp_ln155_reg_1579 == 1'd1)) begin
            b_11_fu_216 <= l_24_fu_1206_p9;
        end else if (((icmp_ln164_reg_1583 == 1'd1) & (icmp_ln155_reg_1579 == 1'd0))) begin
            b_11_fu_216 <= 64'd0;
        end else if ((1'b1 == ap_condition_86)) begin
            b_11_fu_216 <= b_21_fu_1037_p9;
        end else if ((1'b1 == ap_condition_229)) begin
            b_11_fu_216 <= 64'd9223372036854775808;
        end else if ((1'b1 == ap_condition_79)) begin
            b_11_fu_216 <= b_15_fu_885_p3;
        end else if ((1'b1 == ap_condition_72)) begin
            b_11_fu_216 <= b_16_fu_801_p4;
        end else if ((1'b1 == ap_condition_65)) begin
            b_11_fu_216 <= b_17_fu_715_p5;
        end else if ((1'b1 == ap_condition_58)) begin
            b_11_fu_216 <= b_18_fu_627_p6;
        end else if ((1'b1 == ap_condition_51)) begin
            b_11_fu_216 <= b_19_fu_537_p7;
        end else if ((1'b1 == ap_condition_45)) begin
            b_11_fu_216 <= b_20_fu_445_p8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1029)) begin
        if ((icmp_ln155_reg_1579 == 1'd1)) begin
            b_12_fu_220 <= l_24_fu_1206_p9;
        end else if (((icmp_ln164_reg_1583 == 1'd1) & (icmp_ln155_reg_1579 == 1'd0))) begin
            b_12_fu_220 <= 64'd0;
        end else if ((1'b1 == ap_condition_86)) begin
            b_12_fu_220 <= b_21_fu_1037_p9;
        end else if ((1'b1 == ap_condition_229)) begin
            b_12_fu_220 <= 64'd9223372036854775808;
        end else if ((1'b1 == ap_condition_79)) begin
            b_12_fu_220 <= b_15_fu_885_p3;
        end else if ((1'b1 == ap_condition_72)) begin
            b_12_fu_220 <= b_16_fu_801_p4;
        end else if ((1'b1 == ap_condition_65)) begin
            b_12_fu_220 <= b_17_fu_715_p5;
        end else if ((1'b1 == ap_condition_58)) begin
            b_12_fu_220 <= b_18_fu_627_p6;
        end else if ((1'b1 == ap_condition_51)) begin
            b_12_fu_220 <= b_19_fu_537_p7;
        end else if ((1'b1 == ap_condition_45)) begin
            b_12_fu_220 <= b_20_fu_445_p8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_206)) begin
        if ((1'b1 == ap_condition_743)) begin
            b_13_fu_224 <= l_24_fu_1206_p9;
        end else if ((1'b1 == ap_condition_736)) begin
            b_13_fu_224 <= 64'd0;
        end else if ((1'b1 == ap_condition_727)) begin
            b_13_fu_224 <= b_21_fu_1037_p9;
        end else if ((1'b1 == ap_condition_720)) begin
            b_13_fu_224 <= 64'd9223372036854775808;
        end else if ((1'b1 == ap_condition_713)) begin
            b_13_fu_224 <= b_15_fu_885_p3;
        end else if ((1'b1 == ap_condition_706)) begin
            b_13_fu_224 <= b_16_fu_801_p4;
        end else if ((1'b1 == ap_condition_699)) begin
            b_13_fu_224 <= b_17_fu_715_p5;
        end else if ((1'b1 == ap_condition_692)) begin
            b_13_fu_224 <= b_18_fu_627_p6;
        end else if ((1'b1 == ap_condition_685)) begin
            b_13_fu_224 <= b_19_fu_537_p7;
        end else if ((1'b1 == ap_condition_677)) begin
            b_13_fu_224 <= b_20_fu_445_p8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1054)) begin
        if ((icmp_ln155_reg_1579 == 1'd1)) begin
            b_1_fu_176 <= l_24_fu_1206_p9;
        end else if (((icmp_ln164_reg_1583 == 1'd1) & (icmp_ln155_reg_1579 == 1'd0))) begin
            b_1_fu_176 <= 64'd0;
        end else if ((1'b1 == ap_condition_86)) begin
            b_1_fu_176 <= b_21_fu_1037_p9;
        end else if ((1'b1 == ap_condition_229)) begin
            b_1_fu_176 <= 64'd9223372036854775808;
        end else if ((1'b1 == ap_condition_79)) begin
            b_1_fu_176 <= b_15_fu_885_p3;
        end else if ((1'b1 == ap_condition_72)) begin
            b_1_fu_176 <= b_16_fu_801_p4;
        end else if ((1'b1 == ap_condition_65)) begin
            b_1_fu_176 <= b_17_fu_715_p5;
        end else if ((1'b1 == ap_condition_58)) begin
            b_1_fu_176 <= b_18_fu_627_p6;
        end else if ((1'b1 == ap_condition_51)) begin
            b_1_fu_176 <= b_19_fu_537_p7;
        end else if ((1'b1 == ap_condition_45)) begin
            b_1_fu_176 <= b_20_fu_445_p8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1057)) begin
        if ((icmp_ln155_reg_1579 == 1'd1)) begin
            b_2_fu_180 <= l_24_fu_1206_p9;
        end else if (((icmp_ln164_reg_1583 == 1'd1) & (icmp_ln155_reg_1579 == 1'd0))) begin
            b_2_fu_180 <= 64'd0;
        end else if ((1'b1 == ap_condition_86)) begin
            b_2_fu_180 <= b_21_fu_1037_p9;
        end else if ((1'b1 == ap_condition_229)) begin
            b_2_fu_180 <= 64'd9223372036854775808;
        end else if ((1'b1 == ap_condition_79)) begin
            b_2_fu_180 <= b_15_fu_885_p3;
        end else if ((1'b1 == ap_condition_72)) begin
            b_2_fu_180 <= b_16_fu_801_p4;
        end else if ((1'b1 == ap_condition_65)) begin
            b_2_fu_180 <= b_17_fu_715_p5;
        end else if ((1'b1 == ap_condition_58)) begin
            b_2_fu_180 <= b_18_fu_627_p6;
        end else if ((1'b1 == ap_condition_51)) begin
            b_2_fu_180 <= b_19_fu_537_p7;
        end else if ((1'b1 == ap_condition_45)) begin
            b_2_fu_180 <= b_20_fu_445_p8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1060)) begin
        if ((icmp_ln155_reg_1579 == 1'd1)) begin
            b_3_fu_184 <= l_24_fu_1206_p9;
        end else if (((icmp_ln164_reg_1583 == 1'd1) & (icmp_ln155_reg_1579 == 1'd0))) begin
            b_3_fu_184 <= 64'd0;
        end else if ((1'b1 == ap_condition_86)) begin
            b_3_fu_184 <= b_21_fu_1037_p9;
        end else if ((1'b1 == ap_condition_229)) begin
            b_3_fu_184 <= 64'd9223372036854775808;
        end else if ((1'b1 == ap_condition_79)) begin
            b_3_fu_184 <= b_15_fu_885_p3;
        end else if ((1'b1 == ap_condition_72)) begin
            b_3_fu_184 <= b_16_fu_801_p4;
        end else if ((1'b1 == ap_condition_65)) begin
            b_3_fu_184 <= b_17_fu_715_p5;
        end else if ((1'b1 == ap_condition_58)) begin
            b_3_fu_184 <= b_18_fu_627_p6;
        end else if ((1'b1 == ap_condition_51)) begin
            b_3_fu_184 <= b_19_fu_537_p7;
        end else if ((1'b1 == ap_condition_45)) begin
            b_3_fu_184 <= b_20_fu_445_p8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1063)) begin
        if ((icmp_ln155_reg_1579 == 1'd1)) begin
            b_4_fu_188 <= l_24_fu_1206_p9;
        end else if (((icmp_ln164_reg_1583 == 1'd1) & (icmp_ln155_reg_1579 == 1'd0))) begin
            b_4_fu_188 <= 64'd0;
        end else if ((1'b1 == ap_condition_86)) begin
            b_4_fu_188 <= b_21_fu_1037_p9;
        end else if ((1'b1 == ap_condition_229)) begin
            b_4_fu_188 <= 64'd9223372036854775808;
        end else if ((1'b1 == ap_condition_79)) begin
            b_4_fu_188 <= b_15_fu_885_p3;
        end else if ((1'b1 == ap_condition_72)) begin
            b_4_fu_188 <= b_16_fu_801_p4;
        end else if ((1'b1 == ap_condition_65)) begin
            b_4_fu_188 <= b_17_fu_715_p5;
        end else if ((1'b1 == ap_condition_58)) begin
            b_4_fu_188 <= b_18_fu_627_p6;
        end else if ((1'b1 == ap_condition_51)) begin
            b_4_fu_188 <= b_19_fu_537_p7;
        end else if ((1'b1 == ap_condition_45)) begin
            b_4_fu_188 <= b_20_fu_445_p8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1066)) begin
        if ((icmp_ln155_reg_1579 == 1'd1)) begin
            b_5_fu_192 <= l_24_fu_1206_p9;
        end else if (((icmp_ln164_reg_1583 == 1'd1) & (icmp_ln155_reg_1579 == 1'd0))) begin
            b_5_fu_192 <= 64'd0;
        end else if ((1'b1 == ap_condition_86)) begin
            b_5_fu_192 <= b_21_fu_1037_p9;
        end else if ((1'b1 == ap_condition_229)) begin
            b_5_fu_192 <= 64'd9223372036854775808;
        end else if ((1'b1 == ap_condition_79)) begin
            b_5_fu_192 <= b_15_fu_885_p3;
        end else if ((1'b1 == ap_condition_72)) begin
            b_5_fu_192 <= b_16_fu_801_p4;
        end else if ((1'b1 == ap_condition_65)) begin
            b_5_fu_192 <= b_17_fu_715_p5;
        end else if ((1'b1 == ap_condition_58)) begin
            b_5_fu_192 <= b_18_fu_627_p6;
        end else if ((1'b1 == ap_condition_51)) begin
            b_5_fu_192 <= b_19_fu_537_p7;
        end else if ((1'b1 == ap_condition_45)) begin
            b_5_fu_192 <= b_20_fu_445_p8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1069)) begin
        if ((icmp_ln155_reg_1579 == 1'd1)) begin
            b_6_fu_196 <= l_24_fu_1206_p9;
        end else if (((icmp_ln164_reg_1583 == 1'd1) & (icmp_ln155_reg_1579 == 1'd0))) begin
            b_6_fu_196 <= 64'd0;
        end else if ((1'b1 == ap_condition_86)) begin
            b_6_fu_196 <= b_21_fu_1037_p9;
        end else if ((1'b1 == ap_condition_229)) begin
            b_6_fu_196 <= 64'd9223372036854775808;
        end else if ((1'b1 == ap_condition_79)) begin
            b_6_fu_196 <= b_15_fu_885_p3;
        end else if ((1'b1 == ap_condition_72)) begin
            b_6_fu_196 <= b_16_fu_801_p4;
        end else if ((1'b1 == ap_condition_65)) begin
            b_6_fu_196 <= b_17_fu_715_p5;
        end else if ((1'b1 == ap_condition_58)) begin
            b_6_fu_196 <= b_18_fu_627_p6;
        end else if ((1'b1 == ap_condition_51)) begin
            b_6_fu_196 <= b_19_fu_537_p7;
        end else if ((1'b1 == ap_condition_45)) begin
            b_6_fu_196 <= b_20_fu_445_p8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1072)) begin
        if ((icmp_ln155_reg_1579 == 1'd1)) begin
            b_7_fu_200 <= l_24_fu_1206_p9;
        end else if (((icmp_ln164_reg_1583 == 1'd1) & (icmp_ln155_reg_1579 == 1'd0))) begin
            b_7_fu_200 <= 64'd0;
        end else if ((1'b1 == ap_condition_86)) begin
            b_7_fu_200 <= b_21_fu_1037_p9;
        end else if ((1'b1 == ap_condition_229)) begin
            b_7_fu_200 <= 64'd9223372036854775808;
        end else if ((1'b1 == ap_condition_79)) begin
            b_7_fu_200 <= b_15_fu_885_p3;
        end else if ((1'b1 == ap_condition_72)) begin
            b_7_fu_200 <= b_16_fu_801_p4;
        end else if ((1'b1 == ap_condition_65)) begin
            b_7_fu_200 <= b_17_fu_715_p5;
        end else if ((1'b1 == ap_condition_58)) begin
            b_7_fu_200 <= b_18_fu_627_p6;
        end else if ((1'b1 == ap_condition_51)) begin
            b_7_fu_200 <= b_19_fu_537_p7;
        end else if ((1'b1 == ap_condition_45)) begin
            b_7_fu_200 <= b_20_fu_445_p8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1075)) begin
        if ((icmp_ln155_reg_1579 == 1'd1)) begin
            b_8_fu_204 <= l_24_fu_1206_p9;
        end else if (((icmp_ln164_reg_1583 == 1'd1) & (icmp_ln155_reg_1579 == 1'd0))) begin
            b_8_fu_204 <= 64'd0;
        end else if ((1'b1 == ap_condition_86)) begin
            b_8_fu_204 <= b_21_fu_1037_p9;
        end else if ((1'b1 == ap_condition_229)) begin
            b_8_fu_204 <= 64'd9223372036854775808;
        end else if ((1'b1 == ap_condition_79)) begin
            b_8_fu_204 <= b_15_fu_885_p3;
        end else if ((1'b1 == ap_condition_72)) begin
            b_8_fu_204 <= b_16_fu_801_p4;
        end else if ((1'b1 == ap_condition_65)) begin
            b_8_fu_204 <= b_17_fu_715_p5;
        end else if ((1'b1 == ap_condition_58)) begin
            b_8_fu_204 <= b_18_fu_627_p6;
        end else if ((1'b1 == ap_condition_51)) begin
            b_8_fu_204 <= b_19_fu_537_p7;
        end else if ((1'b1 == ap_condition_45)) begin
            b_8_fu_204 <= b_20_fu_445_p8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1078)) begin
        if ((icmp_ln155_reg_1579 == 1'd1)) begin
            b_9_fu_208 <= l_24_fu_1206_p9;
        end else if (((icmp_ln164_reg_1583 == 1'd1) & (icmp_ln155_reg_1579 == 1'd0))) begin
            b_9_fu_208 <= 64'd0;
        end else if ((1'b1 == ap_condition_86)) begin
            b_9_fu_208 <= b_21_fu_1037_p9;
        end else if ((1'b1 == ap_condition_229)) begin
            b_9_fu_208 <= 64'd9223372036854775808;
        end else if ((1'b1 == ap_condition_79)) begin
            b_9_fu_208 <= b_15_fu_885_p3;
        end else if ((1'b1 == ap_condition_72)) begin
            b_9_fu_208 <= b_16_fu_801_p4;
        end else if ((1'b1 == ap_condition_65)) begin
            b_9_fu_208 <= b_17_fu_715_p5;
        end else if ((1'b1 == ap_condition_58)) begin
            b_9_fu_208 <= b_18_fu_627_p6;
        end else if ((1'b1 == ap_condition_51)) begin
            b_9_fu_208 <= b_19_fu_537_p7;
        end else if ((1'b1 == ap_condition_45)) begin
            b_9_fu_208 <= b_20_fu_445_p8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1081)) begin
        if ((icmp_ln155_reg_1579 == 1'd1)) begin
            b_fu_172 <= l_24_fu_1206_p9;
        end else if ((1'b1 == ap_condition_86)) begin
            b_fu_172 <= b_21_fu_1037_p9;
        end else if ((1'b1 == ap_condition_229)) begin
            b_fu_172 <= 64'd9223372036854775808;
        end else if ((1'b1 == ap_condition_79)) begin
            b_fu_172 <= b_15_fu_885_p3;
        end else if ((1'b1 == ap_condition_72)) begin
            b_fu_172 <= b_16_fu_801_p4;
        end else if ((1'b1 == ap_condition_65)) begin
            b_fu_172 <= b_17_fu_715_p5;
        end else if ((1'b1 == ap_condition_58)) begin
            b_fu_172 <= b_18_fu_627_p6;
        end else if ((1'b1 == ap_condition_51)) begin
            b_fu_172 <= b_19_fu_537_p7;
        end else if ((1'b1 == ap_condition_45)) begin
            b_fu_172 <= b_20_fu_445_p8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln153_fu_412_p2 == 1'd0))) begin
            i_fu_168 <= add_ln153_fu_418_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_168 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        i_1_reg_1572 <= ap_sig_allocacmp_i_1;
        icmp_ln155_reg_1579 <= icmp_ln155_fu_424_p2;
        icmp_ln164_reg_1583 <= icmp_ln164_fu_430_p2;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln153_fu_412_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_i_1 = 4'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_168;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready == 1'b1) & (icmp_ln153_fu_412_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        b_10_out_ap_vld = 1'b1;
    end else begin
        b_10_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready == 1'b1) & (icmp_ln153_fu_412_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        b_11_out_ap_vld = 1'b1;
    end else begin
        b_11_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready == 1'b1) & (icmp_ln153_fu_412_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        b_12_out_ap_vld = 1'b1;
    end else begin
        b_12_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready == 1'b1) & (icmp_ln153_fu_412_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        b_13_out_ap_vld = 1'b1;
    end else begin
        b_13_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready == 1'b1) & (icmp_ln153_fu_412_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        b_1_out_ap_vld = 1'b1;
    end else begin
        b_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready == 1'b1) & (icmp_ln153_fu_412_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        b_2_out_ap_vld = 1'b1;
    end else begin
        b_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready == 1'b1) & (icmp_ln153_fu_412_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        b_3_out_ap_vld = 1'b1;
    end else begin
        b_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready == 1'b1) & (icmp_ln153_fu_412_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        b_4_out_ap_vld = 1'b1;
    end else begin
        b_4_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready == 1'b1) & (icmp_ln153_fu_412_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        b_5_out_ap_vld = 1'b1;
    end else begin
        b_5_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready == 1'b1) & (icmp_ln153_fu_412_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        b_6_out_ap_vld = 1'b1;
    end else begin
        b_6_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready == 1'b1) & (icmp_ln153_fu_412_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        b_7_out_ap_vld = 1'b1;
    end else begin
        b_7_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready == 1'b1) & (icmp_ln153_fu_412_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        b_8_out_ap_vld = 1'b1;
    end else begin
        b_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready == 1'b1) & (icmp_ln153_fu_412_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        b_9_out_ap_vld = 1'b1;
    end else begin
        b_9_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready == 1'b1) & (icmp_ln153_fu_412_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        b_out_ap_vld = 1'b1;
    end else begin
        b_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln155_reg_1579 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_grp1)) | ((ap_predicate_op292_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_grp1)) | ((ap_predicate_op233_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_grp1)) | ((ap_predicate_op201_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_grp1)) | ((ap_predicate_op168_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_grp1)) | ((ap_predicate_op134_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_grp1)) | ((ap_predicate_op99_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_grp1)) 
    | ((ap_predicate_op63_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_grp1)))) begin
        core_msg_strm_blk_n = core_msg_strm_empty_n;
    end else begin
        core_msg_strm_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((icmp_ln155_reg_1579 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1)) | ((ap_predicate_op292_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1)) | ((ap_predicate_op233_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1)) | ((ap_predicate_op201_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1)) | ((ap_predicate_op168_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1)) | ((ap_predicate_op134_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1)) | ((ap_predicate_op99_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) 
    & (1'b0 == ap_block_pp0_stage0_11001_grp1)) | ((ap_predicate_op63_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1)))) begin
        core_msg_strm_read = 1'b1;
    end else begin
        core_msg_strm_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln153_fu_418_p2 = (ap_sig_allocacmp_i_1 + 4'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp1));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp1));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1_grp1 = (((icmp_ln155_reg_1579 == 1'd1) & (core_msg_strm_empty_n == 1'b0)) | ((ap_predicate_op292_read_state2 == 1'b1) & (core_msg_strm_empty_n == 1'b0)) | ((ap_predicate_op233_read_state2 == 1'b1) & (core_msg_strm_empty_n == 1'b0)) | ((ap_predicate_op201_read_state2 == 1'b1) & (core_msg_strm_empty_n == 1'b0)) | ((ap_predicate_op168_read_state2 == 1'b1) & (core_msg_strm_empty_n == 1'b0)) | ((ap_predicate_op134_read_state2 == 1'b1) & (core_msg_strm_empty_n == 1'b0)) | ((ap_predicate_op99_read_state2 == 1'b1) & (core_msg_strm_empty_n == 1'b0)) | ((ap_predicate_op63_read_state2 == 1'b1) & (core_msg_strm_empty_n == 1'b0)));
end

always @ (*) begin
    ap_condition_1026 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_1_reg_1572 == 4'd11) & (1'b0 == ap_block_pp0_stage0_11001_grp1));
end

always @ (*) begin
    ap_condition_1029 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_1_reg_1572 == 4'd12) & (1'b0 == ap_block_pp0_stage0_11001_grp1));
end

always @ (*) begin
    ap_condition_1054 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_1_reg_1572 == 4'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1));
end

always @ (*) begin
    ap_condition_1057 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_1_reg_1572 == 4'd2) & (1'b0 == ap_block_pp0_stage0_11001_grp1));
end

always @ (*) begin
    ap_condition_1060 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_1_reg_1572 == 4'd3) & (1'b0 == ap_block_pp0_stage0_11001_grp1));
end

always @ (*) begin
    ap_condition_1063 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_1_reg_1572 == 4'd4) & (1'b0 == ap_block_pp0_stage0_11001_grp1));
end

always @ (*) begin
    ap_condition_1066 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_1_reg_1572 == 4'd5) & (1'b0 == ap_block_pp0_stage0_11001_grp1));
end

always @ (*) begin
    ap_condition_1069 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_1_reg_1572 == 4'd6) & (1'b0 == ap_block_pp0_stage0_11001_grp1));
end

always @ (*) begin
    ap_condition_1072 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_1_reg_1572 == 4'd7) & (1'b0 == ap_block_pp0_stage0_11001_grp1));
end

always @ (*) begin
    ap_condition_1075 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_1_reg_1572 == 4'd8) & (1'b0 == ap_block_pp0_stage0_11001_grp1));
end

always @ (*) begin
    ap_condition_1078 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_1_reg_1572 == 4'd9) & (1'b0 == ap_block_pp0_stage0_11001_grp1));
end

always @ (*) begin
    ap_condition_1081 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_1_reg_1572 == 4'd0) & (1'b0 == ap_block_pp0_stage0_11001_grp1));
end

always @ (*) begin
    ap_condition_206 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1));
end

always @ (*) begin
    ap_condition_229 = ((len_read_reg_1568 == 3'd0) & (icmp_ln164_reg_1583 == 1'd0) & (icmp_ln155_reg_1579 == 1'd0));
end

always @ (*) begin
    ap_condition_45 = ((len == 3'd6) & (icmp_ln164_reg_1583 == 1'd0) & (icmp_ln155_reg_1579 == 1'd0));
end

always @ (*) begin
    ap_condition_51 = ((len == 3'd5) & (icmp_ln164_reg_1583 == 1'd0) & (icmp_ln155_reg_1579 == 1'd0));
end

always @ (*) begin
    ap_condition_58 = ((len == 3'd4) & (icmp_ln164_reg_1583 == 1'd0) & (icmp_ln155_reg_1579 == 1'd0));
end

always @ (*) begin
    ap_condition_65 = ((len == 3'd3) & (icmp_ln164_reg_1583 == 1'd0) & (icmp_ln155_reg_1579 == 1'd0));
end

always @ (*) begin
    ap_condition_677 = ((((len == 3'd6) & (icmp_ln164_reg_1583 == 1'd0) & (icmp_ln155_reg_1579 == 1'd0) & (i_1_reg_1572 == 4'd14)) | ((len == 3'd6) & (icmp_ln164_reg_1583 == 1'd0) & (icmp_ln155_reg_1579 == 1'd0) & (i_1_reg_1572 == 4'd15))) | ((len == 3'd6) & (icmp_ln164_reg_1583 == 1'd0) & (icmp_ln155_reg_1579 == 1'd0) & (i_1_reg_1572 == 4'd13)));
end

always @ (*) begin
    ap_condition_685 = ((((len == 3'd5) & (icmp_ln164_reg_1583 == 1'd0) & (icmp_ln155_reg_1579 == 1'd0) & (i_1_reg_1572 == 4'd14)) | ((len == 3'd5) & (icmp_ln164_reg_1583 == 1'd0) & (icmp_ln155_reg_1579 == 1'd0) & (i_1_reg_1572 == 4'd15))) | ((len == 3'd5) & (icmp_ln164_reg_1583 == 1'd0) & (icmp_ln155_reg_1579 == 1'd0) & (i_1_reg_1572 == 4'd13)));
end

always @ (*) begin
    ap_condition_692 = ((((len == 3'd4) & (icmp_ln164_reg_1583 == 1'd0) & (icmp_ln155_reg_1579 == 1'd0) & (i_1_reg_1572 == 4'd14)) | ((len == 3'd4) & (icmp_ln164_reg_1583 == 1'd0) & (icmp_ln155_reg_1579 == 1'd0) & (i_1_reg_1572 == 4'd15))) | ((len == 3'd4) & (icmp_ln164_reg_1583 == 1'd0) & (icmp_ln155_reg_1579 == 1'd0) & (i_1_reg_1572 == 4'd13)));
end

always @ (*) begin
    ap_condition_699 = ((((len == 3'd3) & (icmp_ln164_reg_1583 == 1'd0) & (icmp_ln155_reg_1579 == 1'd0) & (i_1_reg_1572 == 4'd14)) | ((len == 3'd3) & (icmp_ln164_reg_1583 == 1'd0) & (icmp_ln155_reg_1579 == 1'd0) & (i_1_reg_1572 == 4'd15))) | ((len == 3'd3) & (icmp_ln164_reg_1583 == 1'd0) & (icmp_ln155_reg_1579 == 1'd0) & (i_1_reg_1572 == 4'd13)));
end

always @ (*) begin
    ap_condition_706 = ((((len == 3'd2) & (icmp_ln164_reg_1583 == 1'd0) & (icmp_ln155_reg_1579 == 1'd0) & (i_1_reg_1572 == 4'd14)) | ((len == 3'd2) & (icmp_ln164_reg_1583 == 1'd0) & (icmp_ln155_reg_1579 == 1'd0) & (i_1_reg_1572 == 4'd15))) | ((len == 3'd2) & (icmp_ln164_reg_1583 == 1'd0) & (icmp_ln155_reg_1579 == 1'd0) & (i_1_reg_1572 == 4'd13)));
end

always @ (*) begin
    ap_condition_713 = ((((len == 3'd1) & (icmp_ln164_reg_1583 == 1'd0) & (icmp_ln155_reg_1579 == 1'd0) & (i_1_reg_1572 == 4'd14)) | ((len == 3'd1) & (icmp_ln164_reg_1583 == 1'd0) & (icmp_ln155_reg_1579 == 1'd0) & (i_1_reg_1572 == 4'd15))) | ((len == 3'd1) & (icmp_ln164_reg_1583 == 1'd0) & (icmp_ln155_reg_1579 == 1'd0) & (i_1_reg_1572 == 4'd13)));
end

always @ (*) begin
    ap_condition_72 = ((len == 3'd2) & (icmp_ln164_reg_1583 == 1'd0) & (icmp_ln155_reg_1579 == 1'd0));
end

always @ (*) begin
    ap_condition_720 = ((((len_read_reg_1568 == 3'd0) & (icmp_ln164_reg_1583 == 1'd0) & (icmp_ln155_reg_1579 == 1'd0) & (i_1_reg_1572 == 4'd14)) | ((len_read_reg_1568 == 3'd0) & (icmp_ln164_reg_1583 == 1'd0) & (icmp_ln155_reg_1579 == 1'd0) & (i_1_reg_1572 == 4'd15))) | ((len_read_reg_1568 == 3'd0) & (icmp_ln164_reg_1583 == 1'd0) & (icmp_ln155_reg_1579 == 1'd0) & (i_1_reg_1572 == 4'd13)));
end

always @ (*) begin
    ap_condition_727 = ((((len == 3'd7) & (icmp_ln164_reg_1583 == 1'd0) & (icmp_ln155_reg_1579 == 1'd0) & (i_1_reg_1572 == 4'd14)) | ((len == 3'd7) & (icmp_ln164_reg_1583 == 1'd0) & (icmp_ln155_reg_1579 == 1'd0) & (i_1_reg_1572 == 4'd15))) | ((len == 3'd7) & (icmp_ln164_reg_1583 == 1'd0) & (icmp_ln155_reg_1579 == 1'd0) & (i_1_reg_1572 == 4'd13)));
end

always @ (*) begin
    ap_condition_736 = (((((icmp_ln164_reg_1583 == 1'd1) & (icmp_ln155_reg_1579 == 1'd0) & (i_1_reg_1572 == 4'd14)) | ((icmp_ln164_reg_1583 == 1'd1) & (icmp_ln155_reg_1579 == 1'd0) & (i_1_reg_1572 == 4'd15))) | ((icmp_ln164_reg_1583 == 1'd1) & (icmp_ln155_reg_1579 == 1'd0) & (i_1_reg_1572 == 4'd13))) | ((icmp_ln164_reg_1583 == 1'd1) & (icmp_ln155_reg_1579 == 1'd0) & (i_1_reg_1572 == 4'd0)));
end

always @ (*) begin
    ap_condition_743 = ((((icmp_ln155_reg_1579 == 1'd1) & (i_1_reg_1572 == 4'd14)) | ((icmp_ln155_reg_1579 == 1'd1) & (i_1_reg_1572 == 4'd15))) | ((icmp_ln155_reg_1579 == 1'd1) & (i_1_reg_1572 == 4'd13)));
end

always @ (*) begin
    ap_condition_79 = ((len == 3'd1) & (icmp_ln164_reg_1583 == 1'd0) & (icmp_ln155_reg_1579 == 1'd0));
end

always @ (*) begin
    ap_condition_86 = ((len == 3'd7) & (icmp_ln164_reg_1583 == 1'd0) & (icmp_ln155_reg_1579 == 1'd0));
end

always @ (*) begin
    ap_condition_999 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_1_reg_1572 == 4'd10) & (1'b0 == ap_block_pp0_stage0_11001_grp1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

always @ (*) begin
    ap_predicate_op134_read_state2 = ((len == 3'd4) & (icmp_ln164_reg_1583 == 1'd0) & (icmp_ln155_reg_1579 == 1'd0));
end

always @ (*) begin
    ap_predicate_op168_read_state2 = ((len == 3'd3) & (icmp_ln164_reg_1583 == 1'd0) & (icmp_ln155_reg_1579 == 1'd0));
end

always @ (*) begin
    ap_predicate_op201_read_state2 = ((len == 3'd2) & (icmp_ln164_reg_1583 == 1'd0) & (icmp_ln155_reg_1579 == 1'd0));
end

always @ (*) begin
    ap_predicate_op233_read_state2 = ((len == 3'd1) & (icmp_ln164_reg_1583 == 1'd0) & (icmp_ln155_reg_1579 == 1'd0));
end

always @ (*) begin
    ap_predicate_op292_read_state2 = ((len == 3'd7) & (icmp_ln164_reg_1583 == 1'd0) & (icmp_ln155_reg_1579 == 1'd0));
end

always @ (*) begin
    ap_predicate_op63_read_state2 = ((len == 3'd6) & (icmp_ln164_reg_1583 == 1'd0) & (icmp_ln155_reg_1579 == 1'd0));
end

always @ (*) begin
    ap_predicate_op99_read_state2 = ((len == 3'd5) & (icmp_ln164_reg_1583 == 1'd0) & (icmp_ln155_reg_1579 == 1'd0));
end

assign ap_ready = ap_ready_sig;

assign b_10_out = b_10_fu_212;

assign b_11_out = b_11_fu_216;

assign b_12_out = b_12_fu_220;

assign b_13_out = b_13_fu_224;

assign b_15_fu_885_p3 = {{trunc_ln177_fu_881_p1}, {56'd36028797018963968}};

assign b_16_fu_801_p4 = {{{trunc_ln184_fu_797_p1}, {grp_fu_344_p4}}, {48'd140737488355328}};

assign b_17_fu_715_p5 = {{{{trunc_ln191_fu_711_p1}, {grp_fu_344_p4}}, {grp_fu_354_p4}}, {40'd549755813888}};

assign b_18_fu_627_p6 = {{{{{trunc_ln198_fu_623_p1}, {grp_fu_344_p4}}, {grp_fu_354_p4}}, {grp_fu_364_p4}}, {32'd2147483648}};

assign b_19_fu_537_p7 = {{{{{{trunc_ln206_fu_533_p1}, {grp_fu_344_p4}}, {grp_fu_354_p4}}, {grp_fu_364_p4}}, {grp_fu_384_p4}}, {24'd8388608}};

assign b_1_out = b_1_fu_176;

assign b_20_fu_445_p8 = {{{{{{{trunc_ln214_fu_441_p1}, {grp_fu_344_p4}}, {grp_fu_354_p4}}, {grp_fu_364_p4}}, {grp_fu_384_p4}}, {grp_fu_374_p4}}, {16'd32768}};

assign b_21_fu_1037_p9 = {{{{{{{{trunc_ln223_fu_1033_p1}, {grp_fu_344_p4}}, {grp_fu_354_p4}}, {grp_fu_364_p4}}, {grp_fu_384_p4}}, {grp_fu_374_p4}}, {grp_fu_394_p4}}, {8'd128}};

assign b_2_out = b_2_fu_180;

assign b_3_out = b_3_fu_184;

assign b_4_out = b_4_fu_188;

assign b_5_out = b_5_fu_192;

assign b_6_out = b_6_fu_196;

assign b_7_out = b_7_fu_200;

assign b_8_out = b_8_fu_204;

assign b_9_out = b_9_fu_208;

assign b_out = b_fu_172;

assign empty_fu_1192_p1 = core_msg_strm_dout[7:0];

assign grp_fu_344_p4 = {{core_msg_strm_dout[15:8]}};

assign grp_fu_354_p4 = {{core_msg_strm_dout[23:16]}};

assign grp_fu_364_p4 = {{core_msg_strm_dout[31:24]}};

assign grp_fu_374_p4 = {{core_msg_strm_dout[47:40]}};

assign grp_fu_384_p4 = {{core_msg_strm_dout[39:32]}};

assign grp_fu_394_p4 = {{core_msg_strm_dout[55:48]}};

assign icmp_ln153_fu_412_p2 = ((ap_sig_allocacmp_i_1 == 4'd14) ? 1'b1 : 1'b0);

assign icmp_ln155_fu_424_p2 = ((ap_sig_allocacmp_i_1 < shr_i2380_cast) ? 1'b1 : 1'b0);

assign icmp_ln164_fu_430_p2 = ((ap_sig_allocacmp_i_1 > shr_i2380_cast) ? 1'b1 : 1'b0);

assign l_24_fu_1206_p9 = {{{{{{{{empty_fu_1192_p1}, {grp_fu_344_p4}}, {grp_fu_354_p4}}, {grp_fu_364_p4}}, {grp_fu_384_p4}}, {grp_fu_374_p4}}, {grp_fu_394_p4}}, {p_s_fu_1196_p4}};

assign len_read_reg_1568 = len;

assign p_s_fu_1196_p4 = {{core_msg_strm_dout[63:56]}};

assign trunc_ln177_fu_881_p1 = core_msg_strm_dout[7:0];

assign trunc_ln184_fu_797_p1 = core_msg_strm_dout[7:0];

assign trunc_ln191_fu_711_p1 = core_msg_strm_dout[7:0];

assign trunc_ln198_fu_623_p1 = core_msg_strm_dout[7:0];

assign trunc_ln206_fu_533_p1 = core_msg_strm_dout[7:0];

assign trunc_ln214_fu_441_p1 = core_msg_strm_dout[7:0];

assign trunc_ln223_fu_1033_p1 = core_msg_strm_dout[7:0];

endmodule //test_preProcessing_64u_Pipeline_LOOP_COPY_TAIL_AND_PAD_1
