// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module test_preProcessing_64u_Pipeline_LOOP_GEN_FULL_BLKS (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        core_msg_strm_dout,
        core_msg_strm_empty_n,
        core_msg_strm_read,
        core_msg_strm_num_data_valid,
        core_msg_strm_fifo_cap,
        blk_strm_din,
        blk_strm_full_n,
        blk_strm_write,
        blk_strm_num_data_valid,
        blk_strm_fifo_cap,
        tmp_1
);

parameter    ap_ST_fsm_pp0_stage0 = 16'd1;
parameter    ap_ST_fsm_pp0_stage1 = 16'd2;
parameter    ap_ST_fsm_pp0_stage2 = 16'd4;
parameter    ap_ST_fsm_pp0_stage3 = 16'd8;
parameter    ap_ST_fsm_pp0_stage4 = 16'd16;
parameter    ap_ST_fsm_pp0_stage5 = 16'd32;
parameter    ap_ST_fsm_pp0_stage6 = 16'd64;
parameter    ap_ST_fsm_pp0_stage7 = 16'd128;
parameter    ap_ST_fsm_pp0_stage8 = 16'd256;
parameter    ap_ST_fsm_pp0_stage9 = 16'd512;
parameter    ap_ST_fsm_pp0_stage10 = 16'd1024;
parameter    ap_ST_fsm_pp0_stage11 = 16'd2048;
parameter    ap_ST_fsm_pp0_stage12 = 16'd4096;
parameter    ap_ST_fsm_pp0_stage13 = 16'd8192;
parameter    ap_ST_fsm_pp0_stage14 = 16'd16384;
parameter    ap_ST_fsm_pp0_stage15 = 16'd32768;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] core_msg_strm_dout;
input   core_msg_strm_empty_n;
output   core_msg_strm_read;
input  [6:0] core_msg_strm_num_data_valid;
input  [6:0] core_msg_strm_fifo_cap;
output  [1023:0] blk_strm_din;
input   blk_strm_full_n;
output   blk_strm_write;
input  [5:0] blk_strm_num_data_valid;
input  [5:0] blk_strm_fifo_cap;
input  [120:0] tmp_1;

reg ap_idle;
reg core_msg_strm_read;
reg blk_strm_write;

(* fsm_encoding = "none" *) reg   [15:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
reg    ap_block_state18_pp0_stage1_iter1_grp16;
reg    ap_block_pp0_stage1_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
wire   [0:0] icmp_ln97_fu_181_p2;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_pp0_stage15;
reg   [0:0] icmp_ln97_reg_414;
reg    ap_block_state16_pp0_stage15_iter0_grp14;
reg    ap_block_pp0_stage15_subdone;
reg    core_msg_strm_blk_n;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_grp1;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3_grp2;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_pp0_stage4_grp3;
wire    ap_CS_fsm_pp0_stage5;
wire    ap_block_pp0_stage5_grp4;
wire    ap_CS_fsm_pp0_stage6;
wire    ap_block_pp0_stage6_grp5;
wire    ap_CS_fsm_pp0_stage7;
wire    ap_block_pp0_stage7_grp6;
wire    ap_CS_fsm_pp0_stage8;
wire    ap_block_pp0_stage8_grp7;
wire    ap_CS_fsm_pp0_stage9;
wire    ap_block_pp0_stage9_grp8;
wire    ap_CS_fsm_pp0_stage10;
wire    ap_block_pp0_stage10_grp9;
wire    ap_CS_fsm_pp0_stage11;
wire    ap_block_pp0_stage11_grp10;
wire    ap_CS_fsm_pp0_stage12;
wire    ap_block_pp0_stage12_grp11;
wire    ap_CS_fsm_pp0_stage13;
wire    ap_block_pp0_stage13_grp12;
wire    ap_CS_fsm_pp0_stage14;
wire    ap_block_pp0_stage14_grp13;
wire    ap_block_pp0_stage15_grp14;
wire    ap_block_pp0_stage0_grp15;
wire    ap_block_pp0_stage1_grp16;
reg    blk_strm_blk_n;
wire    ap_block_pp0_stage0_11001_grp0;
reg    ap_block_pp0_stage0_subdone_grp0_done_reg;
wire    ap_block_pp0_stage0_subdone_grp0;
reg    ap_block_pp0_stage0_subdone;
reg    ap_block_pp0_stage1_11001;
wire   [7:0] empty_fu_197_p1;
reg   [7:0] empty_reg_418;
reg    ap_block_state3_pp0_stage2_iter0_grp1;
reg    ap_block_pp0_stage2_11001_grp1;
wire   [7:0] grp_fu_103_p4;
reg   [7:0] p_7_reg_423;
wire   [7:0] grp_fu_113_p4;
reg   [7:0] p_1_reg_428;
wire   [7:0] grp_fu_123_p4;
reg   [7:0] p_6_reg_433;
wire   [7:0] grp_fu_133_p4;
reg   [7:0] p_2_reg_438;
wire   [7:0] grp_fu_143_p4;
reg   [7:0] p_5_reg_443;
wire   [7:0] grp_fu_153_p4;
reg   [7:0] p_3_reg_448;
wire   [7:0] grp_fu_163_p4;
reg   [7:0] p_4_reg_453;
wire   [7:0] empty_51_fu_201_p1;
reg   [7:0] empty_51_reg_458;
reg    ap_block_state4_pp0_stage3_iter0_grp2;
reg    ap_block_pp0_stage3_11001_grp2;
reg   [7:0] p_8_reg_463;
reg   [7:0] p_9_reg_468;
reg   [7:0] p_s_reg_473;
reg   [7:0] p_10_reg_478;
reg   [7:0] p_11_reg_483;
reg   [7:0] p_12_reg_488;
reg   [7:0] p_13_reg_493;
wire   [7:0] empty_52_fu_205_p1;
reg   [7:0] empty_52_reg_498;
reg    ap_block_state5_pp0_stage4_iter0_grp3;
reg    ap_block_pp0_stage4_11001_grp3;
reg   [7:0] p_14_reg_503;
reg   [7:0] p_15_reg_508;
reg   [7:0] p_16_reg_513;
reg   [7:0] p_17_reg_518;
reg   [7:0] p_18_reg_523;
reg   [7:0] p_19_reg_528;
reg   [7:0] p_20_reg_533;
wire   [7:0] empty_53_fu_209_p1;
reg   [7:0] empty_53_reg_538;
reg    ap_block_state6_pp0_stage5_iter0_grp4;
reg    ap_block_pp0_stage5_11001_grp4;
reg   [7:0] p_21_reg_543;
reg   [7:0] p_22_reg_548;
reg   [7:0] p_23_reg_553;
reg   [7:0] p_24_reg_558;
reg   [7:0] p_25_reg_563;
reg   [7:0] p_26_reg_568;
reg   [7:0] p_27_reg_573;
wire   [7:0] empty_54_fu_213_p1;
reg   [7:0] empty_54_reg_578;
reg    ap_block_state7_pp0_stage6_iter0_grp5;
reg    ap_block_pp0_stage6_11001_grp5;
reg   [7:0] p_28_reg_583;
reg   [7:0] p_29_reg_588;
reg   [7:0] p_30_reg_593;
reg   [7:0] p_31_reg_598;
reg   [7:0] p_32_reg_603;
reg   [7:0] p_33_reg_608;
reg   [7:0] p_34_reg_613;
wire   [7:0] empty_55_fu_217_p1;
reg   [7:0] empty_55_reg_618;
reg    ap_block_state8_pp0_stage7_iter0_grp6;
reg    ap_block_pp0_stage7_11001_grp6;
reg   [7:0] p_35_reg_623;
reg   [7:0] p_36_reg_628;
reg   [7:0] p_37_reg_633;
reg   [7:0] p_38_reg_638;
reg   [7:0] p_39_reg_643;
reg   [7:0] p_40_reg_648;
reg   [7:0] p_41_reg_653;
wire   [7:0] empty_56_fu_221_p1;
reg   [7:0] empty_56_reg_658;
reg    ap_block_state9_pp0_stage8_iter0_grp7;
reg    ap_block_pp0_stage8_11001_grp7;
reg   [7:0] p_42_reg_663;
reg   [7:0] p_43_reg_668;
reg   [7:0] p_44_reg_673;
reg   [7:0] p_45_reg_678;
reg   [7:0] p_46_reg_683;
reg   [7:0] p_47_reg_688;
reg   [7:0] p_48_reg_693;
wire   [7:0] empty_57_fu_225_p1;
reg   [7:0] empty_57_reg_698;
reg    ap_block_state10_pp0_stage9_iter0_grp8;
reg    ap_block_pp0_stage9_11001_grp8;
reg   [7:0] p_49_reg_703;
reg   [7:0] p_50_reg_708;
reg   [7:0] p_51_reg_713;
reg   [7:0] p_52_reg_718;
reg   [7:0] p_53_reg_723;
reg   [7:0] p_54_reg_728;
reg   [7:0] p_55_reg_733;
wire   [7:0] empty_58_fu_229_p1;
reg   [7:0] empty_58_reg_738;
reg    ap_block_state11_pp0_stage10_iter0_grp9;
reg    ap_block_pp0_stage10_11001_grp9;
reg   [7:0] p_56_reg_743;
reg   [7:0] p_57_reg_748;
reg   [7:0] p_58_reg_753;
reg   [7:0] p_59_reg_758;
reg   [7:0] p_60_reg_763;
reg   [7:0] p_61_reg_768;
reg   [7:0] p_62_reg_773;
wire   [7:0] empty_59_fu_233_p1;
reg   [7:0] empty_59_reg_778;
reg    ap_block_state12_pp0_stage11_iter0_grp10;
reg    ap_block_pp0_stage11_11001_grp10;
reg   [7:0] p_63_reg_783;
reg   [7:0] p_64_reg_788;
reg   [7:0] p_65_reg_793;
reg   [7:0] p_66_reg_798;
reg   [7:0] p_67_reg_803;
reg   [7:0] p_68_reg_808;
reg   [7:0] p_69_reg_813;
wire   [7:0] empty_60_fu_237_p1;
reg   [7:0] empty_60_reg_818;
reg    ap_block_state13_pp0_stage12_iter0_grp11;
reg    ap_block_pp0_stage12_11001_grp11;
reg   [7:0] p_70_reg_823;
reg   [7:0] p_71_reg_828;
reg   [7:0] p_72_reg_833;
reg   [7:0] p_73_reg_838;
reg   [7:0] p_74_reg_843;
reg   [7:0] p_75_reg_848;
reg   [7:0] p_76_reg_853;
wire   [7:0] empty_61_fu_241_p1;
reg   [7:0] empty_61_reg_858;
reg    ap_block_state14_pp0_stage13_iter0_grp12;
reg    ap_block_pp0_stage13_11001_grp12;
reg   [7:0] p_77_reg_863;
reg   [7:0] p_78_reg_868;
reg   [7:0] p_79_reg_873;
reg   [7:0] p_80_reg_878;
reg   [7:0] p_81_reg_883;
reg   [7:0] p_82_reg_888;
reg   [7:0] p_83_reg_893;
wire   [7:0] empty_62_fu_245_p1;
reg   [7:0] empty_62_reg_898;
reg    ap_block_state15_pp0_stage14_iter0_grp13;
reg    ap_block_pp0_stage14_11001_grp13;
reg   [7:0] p_84_reg_903;
reg   [7:0] p_85_reg_908;
reg   [7:0] p_86_reg_913;
reg   [7:0] p_87_reg_918;
reg   [7:0] p_88_reg_923;
reg   [7:0] p_89_reg_928;
reg   [7:0] p_90_reg_933;
wire   [7:0] empty_63_fu_249_p1;
reg   [7:0] empty_63_reg_938;
reg    ap_block_pp0_stage15_11001_grp14;
reg   [7:0] p_91_reg_943;
reg   [7:0] p_92_reg_948;
reg   [7:0] p_93_reg_953;
reg   [7:0] p_94_reg_958;
reg   [7:0] p_95_reg_963;
reg   [7:0] p_96_reg_968;
reg   [7:0] p_97_reg_973;
wire   [7:0] empty_64_fu_253_p1;
reg   [7:0] empty_64_reg_978;
reg    ap_block_state17_pp0_stage0_iter1_grp15;
reg    ap_block_pp0_stage0_11001_grp15;
reg   [7:0] p_98_reg_983;
reg   [7:0] p_99_reg_988;
reg   [7:0] p_100_reg_993;
reg   [7:0] p_101_reg_998;
reg   [7:0] p_102_reg_1003;
reg   [7:0] p_103_reg_1008;
reg   [7:0] p_104_reg_1013;
reg   [120:0] j_fu_80;
wire   [120:0] j_2_fu_186_p2;
wire    ap_loop_init;
wire    ap_block_pp0_stage1;
reg    ap_block_pp0_stage1_11001_grp16;
reg    ap_block_pp0_stage1_01001_grp16;
wire   [7:0] empty_65_fu_257_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [15:0] ap_NS_fsm;
reg    ap_idle_pp0_1to1;
reg    ap_block_pp0_stage2_subdone;
reg    ap_block_pp0_stage3_subdone;
reg    ap_block_pp0_stage4_subdone;
reg    ap_block_pp0_stage5_subdone;
reg    ap_block_pp0_stage6_subdone;
reg    ap_block_pp0_stage7_subdone;
reg    ap_block_pp0_stage8_subdone;
reg    ap_block_pp0_stage9_subdone;
reg    ap_block_pp0_stage10_subdone;
reg    ap_block_pp0_stage11_subdone;
reg    ap_block_pp0_stage12_subdone;
reg    ap_block_pp0_stage13_subdone;
reg    ap_block_pp0_stage14_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 16'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp0_done_reg = 1'b0;
#0 j_fu_80 = 121'd0;
#0 ap_done_reg = 1'b0;
end

test_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp0)) begin
                ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
            ap_enable_reg_pp0_iter0_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage15_subdone) & (1'b1 == ap_CS_fsm_pp0_stage15))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        j_fu_80 <= 121'd0;
    end else if (((icmp_ln97_fu_181_p2 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        j_fu_80 <= j_2_fu_186_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001_grp2) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        empty_51_reg_458 <= empty_51_fu_201_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_11001_grp3) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        empty_52_reg_498 <= empty_52_fu_205_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage5_11001_grp4) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        empty_53_reg_538 <= empty_53_fu_209_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage6_11001_grp5) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        empty_54_reg_578 <= empty_54_fu_213_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage7_11001_grp6) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        empty_55_reg_618 <= empty_55_fu_217_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage8_11001_grp7) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
        empty_56_reg_658 <= empty_56_fu_221_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage9_11001_grp8) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
        empty_57_reg_698 <= empty_57_fu_225_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage10_11001_grp9) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        empty_58_reg_738 <= empty_58_fu_229_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage11_11001_grp10) & (1'b1 == ap_CS_fsm_pp0_stage11))) begin
        empty_59_reg_778 <= empty_59_fu_233_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage12_11001_grp11) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
        empty_60_reg_818 <= empty_60_fu_237_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage13_11001_grp12) & (1'b1 == ap_CS_fsm_pp0_stage13))) begin
        empty_61_reg_858 <= empty_61_fu_241_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage14_11001_grp13) & (1'b1 == ap_CS_fsm_pp0_stage14))) begin
        empty_62_reg_898 <= empty_62_fu_245_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage15_11001_grp14) & (1'b1 == ap_CS_fsm_pp0_stage15))) begin
        empty_63_reg_938 <= empty_63_fu_249_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp15) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_64_reg_978 <= empty_64_fu_253_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        empty_reg_418 <= empty_fu_197_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        icmp_ln97_reg_414 <= icmp_ln97_fu_181_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp15) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_100_reg_993 <= {{core_msg_strm_dout[55:48]}};
        p_101_reg_998 <= {{core_msg_strm_dout[23:16]}};
        p_102_reg_1003 <= {{core_msg_strm_dout[47:40]}};
        p_103_reg_1008 <= {{core_msg_strm_dout[31:24]}};
        p_104_reg_1013 <= {{core_msg_strm_dout[39:32]}};
        p_98_reg_983 <= {{core_msg_strm_dout[63:56]}};
        p_99_reg_988 <= {{core_msg_strm_dout[15:8]}};
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001_grp2) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        p_10_reg_478 <= {{core_msg_strm_dout[23:16]}};
        p_11_reg_483 <= {{core_msg_strm_dout[47:40]}};
        p_12_reg_488 <= {{core_msg_strm_dout[31:24]}};
        p_13_reg_493 <= {{core_msg_strm_dout[39:32]}};
        p_8_reg_463 <= {{core_msg_strm_dout[63:56]}};
        p_9_reg_468 <= {{core_msg_strm_dout[15:8]}};
        p_s_reg_473 <= {{core_msg_strm_dout[55:48]}};
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_11001_grp3) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        p_14_reg_503 <= {{core_msg_strm_dout[63:56]}};
        p_15_reg_508 <= {{core_msg_strm_dout[15:8]}};
        p_16_reg_513 <= {{core_msg_strm_dout[55:48]}};
        p_17_reg_518 <= {{core_msg_strm_dout[23:16]}};
        p_18_reg_523 <= {{core_msg_strm_dout[47:40]}};
        p_19_reg_528 <= {{core_msg_strm_dout[31:24]}};
        p_20_reg_533 <= {{core_msg_strm_dout[39:32]}};
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        p_1_reg_428 <= {{core_msg_strm_dout[15:8]}};
        p_2_reg_438 <= {{core_msg_strm_dout[23:16]}};
        p_3_reg_448 <= {{core_msg_strm_dout[31:24]}};
        p_4_reg_453 <= {{core_msg_strm_dout[39:32]}};
        p_5_reg_443 <= {{core_msg_strm_dout[47:40]}};
        p_6_reg_433 <= {{core_msg_strm_dout[55:48]}};
        p_7_reg_423 <= {{core_msg_strm_dout[63:56]}};
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage5_11001_grp4) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        p_21_reg_543 <= {{core_msg_strm_dout[63:56]}};
        p_22_reg_548 <= {{core_msg_strm_dout[15:8]}};
        p_23_reg_553 <= {{core_msg_strm_dout[55:48]}};
        p_24_reg_558 <= {{core_msg_strm_dout[23:16]}};
        p_25_reg_563 <= {{core_msg_strm_dout[47:40]}};
        p_26_reg_568 <= {{core_msg_strm_dout[31:24]}};
        p_27_reg_573 <= {{core_msg_strm_dout[39:32]}};
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage6_11001_grp5) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        p_28_reg_583 <= {{core_msg_strm_dout[63:56]}};
        p_29_reg_588 <= {{core_msg_strm_dout[15:8]}};
        p_30_reg_593 <= {{core_msg_strm_dout[55:48]}};
        p_31_reg_598 <= {{core_msg_strm_dout[23:16]}};
        p_32_reg_603 <= {{core_msg_strm_dout[47:40]}};
        p_33_reg_608 <= {{core_msg_strm_dout[31:24]}};
        p_34_reg_613 <= {{core_msg_strm_dout[39:32]}};
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage7_11001_grp6) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        p_35_reg_623 <= {{core_msg_strm_dout[63:56]}};
        p_36_reg_628 <= {{core_msg_strm_dout[15:8]}};
        p_37_reg_633 <= {{core_msg_strm_dout[55:48]}};
        p_38_reg_638 <= {{core_msg_strm_dout[23:16]}};
        p_39_reg_643 <= {{core_msg_strm_dout[47:40]}};
        p_40_reg_648 <= {{core_msg_strm_dout[31:24]}};
        p_41_reg_653 <= {{core_msg_strm_dout[39:32]}};
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage8_11001_grp7) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
        p_42_reg_663 <= {{core_msg_strm_dout[63:56]}};
        p_43_reg_668 <= {{core_msg_strm_dout[15:8]}};
        p_44_reg_673 <= {{core_msg_strm_dout[55:48]}};
        p_45_reg_678 <= {{core_msg_strm_dout[23:16]}};
        p_46_reg_683 <= {{core_msg_strm_dout[47:40]}};
        p_47_reg_688 <= {{core_msg_strm_dout[31:24]}};
        p_48_reg_693 <= {{core_msg_strm_dout[39:32]}};
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage9_11001_grp8) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
        p_49_reg_703 <= {{core_msg_strm_dout[63:56]}};
        p_50_reg_708 <= {{core_msg_strm_dout[15:8]}};
        p_51_reg_713 <= {{core_msg_strm_dout[55:48]}};
        p_52_reg_718 <= {{core_msg_strm_dout[23:16]}};
        p_53_reg_723 <= {{core_msg_strm_dout[47:40]}};
        p_54_reg_728 <= {{core_msg_strm_dout[31:24]}};
        p_55_reg_733 <= {{core_msg_strm_dout[39:32]}};
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage10_11001_grp9) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        p_56_reg_743 <= {{core_msg_strm_dout[63:56]}};
        p_57_reg_748 <= {{core_msg_strm_dout[15:8]}};
        p_58_reg_753 <= {{core_msg_strm_dout[55:48]}};
        p_59_reg_758 <= {{core_msg_strm_dout[23:16]}};
        p_60_reg_763 <= {{core_msg_strm_dout[47:40]}};
        p_61_reg_768 <= {{core_msg_strm_dout[31:24]}};
        p_62_reg_773 <= {{core_msg_strm_dout[39:32]}};
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage11_11001_grp10) & (1'b1 == ap_CS_fsm_pp0_stage11))) begin
        p_63_reg_783 <= {{core_msg_strm_dout[63:56]}};
        p_64_reg_788 <= {{core_msg_strm_dout[15:8]}};
        p_65_reg_793 <= {{core_msg_strm_dout[55:48]}};
        p_66_reg_798 <= {{core_msg_strm_dout[23:16]}};
        p_67_reg_803 <= {{core_msg_strm_dout[47:40]}};
        p_68_reg_808 <= {{core_msg_strm_dout[31:24]}};
        p_69_reg_813 <= {{core_msg_strm_dout[39:32]}};
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage12_11001_grp11) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
        p_70_reg_823 <= {{core_msg_strm_dout[63:56]}};
        p_71_reg_828 <= {{core_msg_strm_dout[15:8]}};
        p_72_reg_833 <= {{core_msg_strm_dout[55:48]}};
        p_73_reg_838 <= {{core_msg_strm_dout[23:16]}};
        p_74_reg_843 <= {{core_msg_strm_dout[47:40]}};
        p_75_reg_848 <= {{core_msg_strm_dout[31:24]}};
        p_76_reg_853 <= {{core_msg_strm_dout[39:32]}};
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage13_11001_grp12) & (1'b1 == ap_CS_fsm_pp0_stage13))) begin
        p_77_reg_863 <= {{core_msg_strm_dout[63:56]}};
        p_78_reg_868 <= {{core_msg_strm_dout[15:8]}};
        p_79_reg_873 <= {{core_msg_strm_dout[55:48]}};
        p_80_reg_878 <= {{core_msg_strm_dout[23:16]}};
        p_81_reg_883 <= {{core_msg_strm_dout[47:40]}};
        p_82_reg_888 <= {{core_msg_strm_dout[31:24]}};
        p_83_reg_893 <= {{core_msg_strm_dout[39:32]}};
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage14_11001_grp13) & (1'b1 == ap_CS_fsm_pp0_stage14))) begin
        p_84_reg_903 <= {{core_msg_strm_dout[63:56]}};
        p_85_reg_908 <= {{core_msg_strm_dout[15:8]}};
        p_86_reg_913 <= {{core_msg_strm_dout[55:48]}};
        p_87_reg_918 <= {{core_msg_strm_dout[23:16]}};
        p_88_reg_923 <= {{core_msg_strm_dout[47:40]}};
        p_89_reg_928 <= {{core_msg_strm_dout[31:24]}};
        p_90_reg_933 <= {{core_msg_strm_dout[39:32]}};
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage15_11001_grp14) & (1'b1 == ap_CS_fsm_pp0_stage15))) begin
        p_91_reg_943 <= {{core_msg_strm_dout[63:56]}};
        p_92_reg_948 <= {{core_msg_strm_dout[15:8]}};
        p_93_reg_953 <= {{core_msg_strm_dout[55:48]}};
        p_94_reg_958 <= {{core_msg_strm_dout[23:16]}};
        p_95_reg_963 <= {{core_msg_strm_dout[47:40]}};
        p_96_reg_968 <= {{core_msg_strm_dout[31:24]}};
        p_97_reg_973 <= {{core_msg_strm_dout[39:32]}};
    end
end

always @ (*) begin
    if (((icmp_ln97_fu_181_p2 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage15_subdone) & (1'b1 == ap_CS_fsm_pp0_stage15))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_grp16) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        blk_strm_blk_n = blk_strm_full_n;
    end else begin
        blk_strm_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001_grp16) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        blk_strm_write = 1'b1;
    end else begin
        blk_strm_write = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln97_reg_414 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage15_grp14) & (1'b1 == ap_CS_fsm_pp0_stage15)) | ((icmp_ln97_reg_414 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage14_grp13) & (1'b1 == ap_CS_fsm_pp0_stage14)) | ((icmp_ln97_reg_414 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage13_grp12) & (1'b1 == ap_CS_fsm_pp0_stage13)) | ((icmp_ln97_reg_414 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage12_grp11) & (1'b1 == ap_CS_fsm_pp0_stage12)) | ((icmp_ln97_reg_414 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage11_grp10) & (1'b1 == ap_CS_fsm_pp0_stage11)) | ((icmp_ln97_reg_414 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage10_grp9) & (1'b1 == ap_CS_fsm_pp0_stage10)) | ((icmp_ln97_reg_414 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage9_grp8) & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((icmp_ln97_reg_414 
    == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage8_grp7) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((icmp_ln97_reg_414 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage7_grp6) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((icmp_ln97_reg_414 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage6_grp5) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((icmp_ln97_reg_414 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage5_grp4) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((icmp_ln97_reg_414 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_grp3) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((icmp_ln97_reg_414 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_grp2) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((icmp_ln97_reg_414 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_grp1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((icmp_ln97_reg_414 == 1'd0) & (1'b0 == ap_block_pp0_stage0_grp15) 
    & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_grp16) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        core_msg_strm_blk_n = core_msg_strm_empty_n;
    end else begin
        core_msg_strm_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((icmp_ln97_reg_414 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage15_11001_grp14) & (1'b1 == ap_CS_fsm_pp0_stage15)) | ((icmp_ln97_reg_414 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage14_11001_grp13) & (1'b1 == ap_CS_fsm_pp0_stage14)) | ((icmp_ln97_reg_414 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage13_11001_grp12) & (1'b1 == ap_CS_fsm_pp0_stage13)) | ((icmp_ln97_reg_414 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage12_11001_grp11) & (1'b1 == ap_CS_fsm_pp0_stage12)) | ((icmp_ln97_reg_414 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage11_11001_grp10) & (1'b1 == ap_CS_fsm_pp0_stage11)) | ((icmp_ln97_reg_414 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage10_11001_grp9) & (1'b1 == ap_CS_fsm_pp0_stage10)) | ((icmp_ln97_reg_414 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage9_11001_grp8) & (1'b1 
    == ap_CS_fsm_pp0_stage9)) | ((icmp_ln97_reg_414 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage8_11001_grp7) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((icmp_ln97_reg_414 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage7_11001_grp6) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((icmp_ln97_reg_414 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage6_11001_grp5) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((icmp_ln97_reg_414 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage5_11001_grp4) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((icmp_ln97_reg_414 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_11001_grp3) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((icmp_ln97_reg_414 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001_grp2) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((icmp_ln97_reg_414 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001_grp1) 
    & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((icmp_ln97_reg_414 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001_grp15) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001_grp16) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        core_msg_strm_read = 1'b1;
    end else begin
        core_msg_strm_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_idle_pp0_1to1 == 1'b1) & (ap_start_int == 1'b0)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        ap_ST_fsm_pp0_stage6 : begin
            if ((1'b0 == ap_block_pp0_stage6_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end
        end
        ap_ST_fsm_pp0_stage7 : begin
            if ((1'b0 == ap_block_pp0_stage7_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end
        end
        ap_ST_fsm_pp0_stage8 : begin
            if ((1'b0 == ap_block_pp0_stage8_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage8;
            end
        end
        ap_ST_fsm_pp0_stage9 : begin
            if ((1'b0 == ap_block_pp0_stage9_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage9;
            end
        end
        ap_ST_fsm_pp0_stage10 : begin
            if ((1'b0 == ap_block_pp0_stage10_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage10;
            end
        end
        ap_ST_fsm_pp0_stage11 : begin
            if ((1'b0 == ap_block_pp0_stage11_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage11;
            end
        end
        ap_ST_fsm_pp0_stage12 : begin
            if ((1'b0 == ap_block_pp0_stage12_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage12;
            end
        end
        ap_ST_fsm_pp0_stage13 : begin
            if ((1'b0 == ap_block_pp0_stage13_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage13;
            end
        end
        ap_ST_fsm_pp0_stage14 : begin
            if ((1'b0 == ap_block_pp0_stage14_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage14;
            end
        end
        ap_ST_fsm_pp0_stage15 : begin
            if ((1'b0 == ap_block_pp0_stage15_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage15;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage10 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_pp0_stage11 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_pp0_stage12 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_pp0_stage13 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_pp0_stage14 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_pp0_stage15 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp0_stage6 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp0_stage7 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_pp0_stage8 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_pp0_stage9 = ap_CS_fsm[32'd9];

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp15 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state17_pp0_stage0_iter1_grp15));
end

assign ap_block_pp0_stage0_grp15 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state17_pp0_stage0_iter1_grp15));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage10_11001_grp9 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state11_pp0_stage10_iter0_grp9));
end

assign ap_block_pp0_stage10_grp9 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage10_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state11_pp0_stage10_iter0_grp9));
end

always @ (*) begin
    ap_block_pp0_stage11_11001_grp10 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state12_pp0_stage11_iter0_grp10));
end

assign ap_block_pp0_stage11_grp10 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage11_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state12_pp0_stage11_iter0_grp10));
end

always @ (*) begin
    ap_block_pp0_stage12_11001_grp11 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state13_pp0_stage12_iter0_grp11));
end

assign ap_block_pp0_stage12_grp11 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage12_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state13_pp0_stage12_iter0_grp11));
end

always @ (*) begin
    ap_block_pp0_stage13_11001_grp12 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state14_pp0_stage13_iter0_grp12));
end

assign ap_block_pp0_stage13_grp12 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage13_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state14_pp0_stage13_iter0_grp12));
end

always @ (*) begin
    ap_block_pp0_stage14_11001_grp13 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state15_pp0_stage14_iter0_grp13));
end

assign ap_block_pp0_stage14_grp13 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage14_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state15_pp0_stage14_iter0_grp13));
end

always @ (*) begin
    ap_block_pp0_stage15_11001_grp14 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state16_pp0_stage15_iter0_grp14));
end

assign ap_block_pp0_stage15_grp14 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage15_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state16_pp0_stage15_iter0_grp14));
end

always @ (*) begin
    ap_block_pp0_stage1_01001_grp16 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state18_pp0_stage1_iter1_grp16));
end

always @ (*) begin
    ap_block_pp0_stage1_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state18_pp0_stage1_iter1_grp16));
end

always @ (*) begin
    ap_block_pp0_stage1_11001_grp16 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state18_pp0_stage1_iter1_grp16));
end

assign ap_block_pp0_stage1_grp16 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state18_pp0_stage1_iter1_grp16));
end

always @ (*) begin
    ap_block_pp0_stage2_11001_grp1 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state3_pp0_stage2_iter0_grp1));
end

assign ap_block_pp0_stage2_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state3_pp0_stage2_iter0_grp1));
end

always @ (*) begin
    ap_block_pp0_stage3_11001_grp2 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state4_pp0_stage3_iter0_grp2));
end

assign ap_block_pp0_stage3_grp2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state4_pp0_stage3_iter0_grp2));
end

always @ (*) begin
    ap_block_pp0_stage4_11001_grp3 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state5_pp0_stage4_iter0_grp3));
end

assign ap_block_pp0_stage4_grp3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage4_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state5_pp0_stage4_iter0_grp3));
end

always @ (*) begin
    ap_block_pp0_stage5_11001_grp4 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state6_pp0_stage5_iter0_grp4));
end

assign ap_block_pp0_stage5_grp4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage5_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state6_pp0_stage5_iter0_grp4));
end

always @ (*) begin
    ap_block_pp0_stage6_11001_grp5 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state7_pp0_stage6_iter0_grp5));
end

assign ap_block_pp0_stage6_grp5 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage6_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state7_pp0_stage6_iter0_grp5));
end

always @ (*) begin
    ap_block_pp0_stage7_11001_grp6 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state8_pp0_stage7_iter0_grp6));
end

assign ap_block_pp0_stage7_grp6 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage7_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state8_pp0_stage7_iter0_grp6));
end

always @ (*) begin
    ap_block_pp0_stage8_11001_grp7 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state9_pp0_stage8_iter0_grp7));
end

assign ap_block_pp0_stage8_grp7 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage8_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state9_pp0_stage8_iter0_grp7));
end

always @ (*) begin
    ap_block_pp0_stage9_11001_grp8 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state10_pp0_stage9_iter0_grp8));
end

assign ap_block_pp0_stage9_grp8 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage9_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state10_pp0_stage9_iter0_grp8));
end

always @ (*) begin
    ap_block_state10_pp0_stage9_iter0_grp8 = ((icmp_ln97_reg_414 == 1'd0) & (core_msg_strm_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state11_pp0_stage10_iter0_grp9 = ((icmp_ln97_reg_414 == 1'd0) & (core_msg_strm_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state12_pp0_stage11_iter0_grp10 = ((icmp_ln97_reg_414 == 1'd0) & (core_msg_strm_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state13_pp0_stage12_iter0_grp11 = ((icmp_ln97_reg_414 == 1'd0) & (core_msg_strm_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state14_pp0_stage13_iter0_grp12 = ((icmp_ln97_reg_414 == 1'd0) & (core_msg_strm_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state15_pp0_stage14_iter0_grp13 = ((icmp_ln97_reg_414 == 1'd0) & (core_msg_strm_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state16_pp0_stage15_iter0_grp14 = ((icmp_ln97_reg_414 == 1'd0) & (core_msg_strm_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state17_pp0_stage0_iter1_grp15 = ((icmp_ln97_reg_414 == 1'd0) & (core_msg_strm_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state18_pp0_stage1_iter1_grp16 = ((blk_strm_full_n == 1'b0) | (core_msg_strm_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state3_pp0_stage2_iter0_grp1 = ((icmp_ln97_reg_414 == 1'd0) & (core_msg_strm_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state4_pp0_stage3_iter0_grp2 = ((icmp_ln97_reg_414 == 1'd0) & (core_msg_strm_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state5_pp0_stage4_iter0_grp3 = ((icmp_ln97_reg_414 == 1'd0) & (core_msg_strm_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state6_pp0_stage5_iter0_grp4 = ((icmp_ln97_reg_414 == 1'd0) & (core_msg_strm_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state7_pp0_stage6_iter0_grp5 = ((icmp_ln97_reg_414 == 1'd0) & (core_msg_strm_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state8_pp0_stage7_iter0_grp6 = ((icmp_ln97_reg_414 == 1'd0) & (core_msg_strm_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state9_pp0_stage8_iter0_grp7 = ((icmp_ln97_reg_414 == 1'd0) & (core_msg_strm_empty_n == 1'b0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign ap_ready = ap_ready_sig;

assign blk_strm_din = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{empty_65_fu_257_p1}, {grp_fu_113_p4}}, {grp_fu_133_p4}}, {grp_fu_153_p4}}, {grp_fu_163_p4}}, {grp_fu_143_p4}}, {grp_fu_123_p4}}, {grp_fu_103_p4}}, {empty_64_reg_978}}, {p_99_reg_988}}, {p_101_reg_998}}, {p_103_reg_1008}}, {p_104_reg_1013}}, {p_102_reg_1003}}, {p_100_reg_993}}, {p_98_reg_983}}, {empty_63_reg_938}}, {p_92_reg_948}}, {p_94_reg_958}}, {p_96_reg_968}}, {p_97_reg_973}}, {p_95_reg_963}}, {p_93_reg_953}}, {p_91_reg_943}}, {empty_62_reg_898}}, {p_85_reg_908}}, {p_87_reg_918}}, {p_89_reg_928}}, {p_90_reg_933}}, {p_88_reg_923}}, {p_86_reg_913}}, {p_84_reg_903}}, {empty_61_reg_858}}, {p_78_reg_868}}, {p_80_reg_878}}, {p_82_reg_888}}, {p_83_reg_893}}, {p_81_reg_883}}, {p_79_reg_873}}, {p_77_reg_863}}, {empty_60_reg_818}}, {p_71_reg_828}}, {p_73_reg_838}}, {p_75_reg_848}}, {p_76_reg_853}}, {p_74_reg_843}}, {p_72_reg_833}}, {p_70_reg_823}}, {empty_59_reg_778}}, {p_64_reg_788}}, {p_66_reg_798}}, 
    {p_68_reg_808}}, {p_69_reg_813}}, {p_67_reg_803}}, {p_65_reg_793}}, {p_63_reg_783}}, {empty_58_reg_738}}, {p_57_reg_748}}, {p_59_reg_758}}, {p_61_reg_768}}, {p_62_reg_773}}, {p_60_reg_763}}, {p_58_reg_753}}, {p_56_reg_743}}, {empty_57_reg_698}}, {p_50_reg_708}}, {p_52_reg_718}}, {p_54_reg_728}}, {p_55_reg_733}}, {p_53_reg_723}}, {p_51_reg_713}}, {p_49_reg_703}}, {empty_56_reg_658}}, {p_43_reg_668}}, {p_45_reg_678}}, {p_47_reg_688}}, {p_48_reg_693}}, {p_46_reg_683}}, {p_44_reg_673}}, {p_42_reg_663}}, {empty_55_reg_618}}, {p_36_reg_628}}, {p_38_reg_638}}, {p_40_reg_648}}, {p_41_reg_653}}, {p_39_reg_643}}, {p_37_reg_633}}, {p_35_reg_623}}, {empty_54_reg_578}}, {p_29_reg_588}}, {p_31_reg_598}}, {p_33_reg_608}}, {p_34_reg_613}}, {p_32_reg_603}}, {p_30_reg_593}}, {p_28_reg_583}}, {empty_53_reg_538}}, {p_22_reg_548}}, {p_24_reg_558}}, {p_26_reg_568}}, {p_27_reg_573}}, {p_25_reg_563}}, {p_23_reg_553}}, {p_21_reg_543}}, {empty_52_reg_498}}, {p_15_reg_508}}, {p_17_reg_518}}, {p_19_reg_528}}, {p_20_reg_533}}, {p_18_reg_523}}, 
    {p_16_reg_513}}, {p_14_reg_503}}, {empty_51_reg_458}}, {p_9_reg_468}}, {p_10_reg_478}}, {p_12_reg_488}}, {p_13_reg_493}}, {p_11_reg_483}}, {p_s_reg_473}}, {p_8_reg_463}}, {empty_reg_418}}, {p_1_reg_428}}, {p_2_reg_438}}, {p_3_reg_448}}, {p_4_reg_453}}, {p_5_reg_443}}, {p_6_reg_433}}, {p_7_reg_423}};

assign empty_51_fu_201_p1 = core_msg_strm_dout[7:0];

assign empty_52_fu_205_p1 = core_msg_strm_dout[7:0];

assign empty_53_fu_209_p1 = core_msg_strm_dout[7:0];

assign empty_54_fu_213_p1 = core_msg_strm_dout[7:0];

assign empty_55_fu_217_p1 = core_msg_strm_dout[7:0];

assign empty_56_fu_221_p1 = core_msg_strm_dout[7:0];

assign empty_57_fu_225_p1 = core_msg_strm_dout[7:0];

assign empty_58_fu_229_p1 = core_msg_strm_dout[7:0];

assign empty_59_fu_233_p1 = core_msg_strm_dout[7:0];

assign empty_60_fu_237_p1 = core_msg_strm_dout[7:0];

assign empty_61_fu_241_p1 = core_msg_strm_dout[7:0];

assign empty_62_fu_245_p1 = core_msg_strm_dout[7:0];

assign empty_63_fu_249_p1 = core_msg_strm_dout[7:0];

assign empty_64_fu_253_p1 = core_msg_strm_dout[7:0];

assign empty_65_fu_257_p1 = core_msg_strm_dout[7:0];

assign empty_fu_197_p1 = core_msg_strm_dout[7:0];

assign grp_fu_103_p4 = {{core_msg_strm_dout[63:56]}};

assign grp_fu_113_p4 = {{core_msg_strm_dout[15:8]}};

assign grp_fu_123_p4 = {{core_msg_strm_dout[55:48]}};

assign grp_fu_133_p4 = {{core_msg_strm_dout[23:16]}};

assign grp_fu_143_p4 = {{core_msg_strm_dout[47:40]}};

assign grp_fu_153_p4 = {{core_msg_strm_dout[31:24]}};

assign grp_fu_163_p4 = {{core_msg_strm_dout[39:32]}};

assign icmp_ln97_fu_181_p2 = ((j_fu_80 == tmp_1) ? 1'b1 : 1'b0);

assign j_2_fu_186_p2 = (j_fu_80 + 121'd1);

endmodule //test_preProcessing_64u_Pipeline_LOOP_GEN_FULL_BLKS
