// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module test_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        w_strm_dout,
        w_strm_empty_n,
        w_strm_read,
        w_strm_num_data_valid,
        w_strm_fifo_cap,
        mul_ln685,
        add_ln7788_out,
        add_ln7788_out_ap_vld,
        add_ln7797_out,
        add_ln7797_out_ap_vld,
        add_ln7806_out,
        add_ln7806_out_ap_vld,
        add_ln7815_out,
        add_ln7815_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] w_strm_dout;
input   w_strm_empty_n;
output   w_strm_read;
input  [5:0] w_strm_num_data_valid;
input  [5:0] w_strm_fifo_cap;
input  [134:0] mul_ln685;
output  [63:0] add_ln7788_out;
output   add_ln7788_out_ap_vld;
output  [63:0] add_ln7797_out;
output   add_ln7797_out_ap_vld;
output  [63:0] add_ln7806_out;
output   add_ln7806_out_ap_vld;
output  [63:0] add_ln7815_out;
output   add_ln7815_out_ap_vld;

reg ap_idle;
reg w_strm_read;
reg add_ln7788_out_ap_vld;
reg add_ln7797_out_ap_vld;
reg add_ln7806_out_ap_vld;
reg add_ln7815_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
reg   [0:0] icmp_ln735_reg_1830;
reg    ap_block_state3_pp0_stage0_iter2_grp1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln735_fu_675_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    w_strm_blk_n;
wire    ap_block_pp0_stage0_grp1;
reg   [63:0] b_24_reg_568;
reg   [63:0] a_3_reg_580;
wire    ap_block_pp0_stage0_11001_grp0;
wire    ap_block_pp0_stage0_subdone_grp0;
reg    ap_block_pp0_stage0_11001;
wire   [63:0] select_ln735_8_fu_830_p3;
reg    ap_block_pp0_stage0_11001_grp1;
wire   [63:0] a_2_fu_1470_p2;
wire    ap_loop_init;
reg   [63:0] d_2_fu_432;
wire   [63:0] select_ln735_7_fu_822_p3;
reg   [63:0] d_1_fu_436;
wire   [63:0] select_ln735_6_fu_814_p3;
reg   [63:0] g_1_fu_440;
wire   [63:0] select_ln735_4_fu_798_p3;
reg   [63:0] f_1_fu_444;
wire   [63:0] e_3_fu_1398_p2;
reg   [63:0] h_2_fu_448;
wire   [63:0] select_ln735_3_fu_790_p3;
reg   [63:0] h_1_fu_452;
wire   [63:0] select_ln735_2_fu_782_p3;
reg   [6:0] t_fu_456;
wire   [6:0] add_ln749_fu_1476_p2;
reg   [63:0] add_ln7851_fu_460;
wire   [63:0] add_ln785_fu_1524_p2;
reg   [63:0] add_ln7842_fu_464;
wire   [63:0] add_ln784_fu_1518_p2;
reg   [63:0] add_ln7833_fu_468;
wire   [63:0] add_ln783_fu_1512_p2;
reg   [63:0] add_ln7824_fu_472;
wire   [63:0] add_ln782_fu_1506_p2;
reg   [63:0] add_ln7815_fu_476;
wire   [63:0] add_ln781_fu_1500_p2;
reg   [63:0] add_ln7806_fu_480;
wire   [63:0] add_ln780_fu_1494_p2;
reg   [63:0] add_ln7797_fu_484;
wire   [63:0] add_ln779_fu_1488_p2;
reg   [63:0] add_ln7788_fu_488;
wire   [63:0] add_ln778_fu_1482_p2;
reg   [63:0] a_fu_492;
wire   [63:0] select_ln735_16_fu_894_p3;
reg   [63:0] b_fu_496;
wire   [63:0] select_ln735_15_fu_886_p3;
reg   [63:0] c_fu_500;
wire   [63:0] select_ln735_14_fu_878_p3;
reg   [63:0] d_fu_504;
wire   [63:0] select_ln735_13_fu_870_p3;
reg   [63:0] e_fu_508;
wire   [63:0] select_ln735_12_fu_862_p3;
reg   [63:0] f_fu_512;
wire   [63:0] select_ln735_11_fu_854_p3;
reg   [63:0] g_fu_516;
wire   [63:0] select_ln735_10_fu_846_p3;
reg   [63:0] h_fu_520;
wire   [63:0] select_ln735_9_fu_838_p3;
reg   [134:0] indvar_flatten_fu_524;
wire   [134:0] add_ln735_fu_680_p2;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_01001_grp1;
wire   [0:0] icmp_ln749_fu_760_p2;
wire   [63:0] tmp_s_fu_944_p161;
wire   [6:0] select_ln735_fu_766_p3;
wire   [13:0] trunc_ln387_fu_912_p1;
wire   [49:0] lshr_ln_fu_902_p4;
wire   [17:0] trunc_ln387_4_fu_926_p1;
wire   [45:0] lshr_ln387_4_fu_916_p4;
wire   [63:0] xor_ln755_fu_1272_p2;
wire   [40:0] trunc_ln387_5_fu_940_p1;
wire   [22:0] lshr_ln387_5_fu_930_p4;
wire   [63:0] and_ln755_fu_1294_p2;
wire   [63:0] and_ln755_1_fu_1300_p2;
wire   [63:0] or_ln755_1_fu_1286_p3;
wire   [63:0] or_ln_fu_1278_p3;
wire   [63:0] xor_ln755_2_fu_1320_p2;
wire   [63:0] or_ln755_2_fu_1306_p3;
wire   [63:0] select_ln735_1_fu_774_p3;
wire   [63:0] xor_ln755_1_fu_1314_p2;
wire   [63:0] tmp_s_fu_944_p163;
wire   [63:0] add_ln755_1_fu_1338_p2;
wire   [63:0] xor_ln755_3_fu_1326_p2;
wire   [63:0] add_ln755_2_fu_1344_p2;
wire   [63:0] add_ln755_fu_1332_p2;
wire   [63:0] T1_fu_1350_p2;
wire   [63:0] select_ln735_5_fu_806_p3;
wire   [63:0] xor_ln764_fu_1404_p2;
wire   [27:0] trunc_ln387_6_fu_1366_p1;
wire   [35:0] lshr_ln387_6_fu_1356_p4;
wire   [33:0] trunc_ln387_7_fu_1380_p1;
wire   [29:0] lshr_ln387_7_fu_1370_p4;
wire   [63:0] and_ln764_fu_1410_p2;
wire   [63:0] and_ln764_1_fu_1416_p2;
wire   [38:0] trunc_ln387_8_fu_1394_p1;
wire   [24:0] lshr_ln387_8_fu_1384_p4;
wire   [63:0] or_ln764_1_fu_1430_p3;
wire   [63:0] or_ln764_2_fu_1444_p3;
wire   [63:0] xor_ln764_2_fu_1452_p2;
wire   [63:0] or_ln7_fu_1422_p3;
wire   [63:0] xor_ln764_1_fu_1438_p2;
wire   [63:0] add_ln764_fu_1464_p2;
wire   [63:0] xor_ln764_3_fu_1458_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [6:0] tmp_s_fu_944_p1;
wire   [6:0] tmp_s_fu_944_p3;
wire   [6:0] tmp_s_fu_944_p5;
wire   [6:0] tmp_s_fu_944_p7;
wire   [6:0] tmp_s_fu_944_p9;
wire   [6:0] tmp_s_fu_944_p11;
wire   [6:0] tmp_s_fu_944_p13;
wire   [6:0] tmp_s_fu_944_p15;
wire   [6:0] tmp_s_fu_944_p17;
wire   [6:0] tmp_s_fu_944_p19;
wire   [6:0] tmp_s_fu_944_p21;
wire   [6:0] tmp_s_fu_944_p23;
wire   [6:0] tmp_s_fu_944_p25;
wire   [6:0] tmp_s_fu_944_p27;
wire   [6:0] tmp_s_fu_944_p29;
wire   [6:0] tmp_s_fu_944_p31;
wire   [6:0] tmp_s_fu_944_p33;
wire   [6:0] tmp_s_fu_944_p35;
wire   [6:0] tmp_s_fu_944_p37;
wire   [6:0] tmp_s_fu_944_p39;
wire   [6:0] tmp_s_fu_944_p41;
wire   [6:0] tmp_s_fu_944_p43;
wire   [6:0] tmp_s_fu_944_p45;
wire   [6:0] tmp_s_fu_944_p47;
wire   [6:0] tmp_s_fu_944_p49;
wire   [6:0] tmp_s_fu_944_p51;
wire   [6:0] tmp_s_fu_944_p53;
wire   [6:0] tmp_s_fu_944_p55;
wire   [6:0] tmp_s_fu_944_p57;
wire   [6:0] tmp_s_fu_944_p59;
wire   [6:0] tmp_s_fu_944_p61;
wire   [6:0] tmp_s_fu_944_p63;
wire   [6:0] tmp_s_fu_944_p65;
wire   [6:0] tmp_s_fu_944_p67;
wire   [6:0] tmp_s_fu_944_p69;
wire   [6:0] tmp_s_fu_944_p71;
wire   [6:0] tmp_s_fu_944_p73;
wire   [6:0] tmp_s_fu_944_p75;
wire   [6:0] tmp_s_fu_944_p77;
wire   [6:0] tmp_s_fu_944_p79;
wire   [6:0] tmp_s_fu_944_p81;
wire   [6:0] tmp_s_fu_944_p83;
wire   [6:0] tmp_s_fu_944_p85;
wire   [6:0] tmp_s_fu_944_p87;
wire   [6:0] tmp_s_fu_944_p89;
wire   [6:0] tmp_s_fu_944_p91;
wire   [6:0] tmp_s_fu_944_p93;
wire   [6:0] tmp_s_fu_944_p95;
wire   [6:0] tmp_s_fu_944_p97;
wire   [6:0] tmp_s_fu_944_p99;
wire   [6:0] tmp_s_fu_944_p101;
wire   [6:0] tmp_s_fu_944_p103;
wire   [6:0] tmp_s_fu_944_p105;
wire   [6:0] tmp_s_fu_944_p107;
wire   [6:0] tmp_s_fu_944_p109;
wire   [6:0] tmp_s_fu_944_p111;
wire   [6:0] tmp_s_fu_944_p113;
wire   [6:0] tmp_s_fu_944_p115;
wire   [6:0] tmp_s_fu_944_p117;
wire   [6:0] tmp_s_fu_944_p119;
wire   [6:0] tmp_s_fu_944_p121;
wire   [6:0] tmp_s_fu_944_p123;
wire   [6:0] tmp_s_fu_944_p125;
wire   [6:0] tmp_s_fu_944_p127;
wire  signed [6:0] tmp_s_fu_944_p129;
wire  signed [6:0] tmp_s_fu_944_p131;
wire  signed [6:0] tmp_s_fu_944_p133;
wire  signed [6:0] tmp_s_fu_944_p135;
wire  signed [6:0] tmp_s_fu_944_p137;
wire  signed [6:0] tmp_s_fu_944_p139;
wire  signed [6:0] tmp_s_fu_944_p141;
wire  signed [6:0] tmp_s_fu_944_p143;
wire  signed [6:0] tmp_s_fu_944_p145;
wire  signed [6:0] tmp_s_fu_944_p147;
wire  signed [6:0] tmp_s_fu_944_p149;
wire  signed [6:0] tmp_s_fu_944_p151;
wire  signed [6:0] tmp_s_fu_944_p153;
wire  signed [6:0] tmp_s_fu_944_p155;
wire  signed [6:0] tmp_s_fu_944_p157;
wire  signed [6:0] tmp_s_fu_944_p159;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 d_2_fu_432 = 64'd0;
#0 d_1_fu_436 = 64'd0;
#0 g_1_fu_440 = 64'd0;
#0 f_1_fu_444 = 64'd0;
#0 h_2_fu_448 = 64'd0;
#0 h_1_fu_452 = 64'd0;
#0 t_fu_456 = 7'd0;
#0 add_ln7851_fu_460 = 64'd0;
#0 add_ln7842_fu_464 = 64'd0;
#0 add_ln7833_fu_468 = 64'd0;
#0 add_ln7824_fu_472 = 64'd0;
#0 add_ln7815_fu_476 = 64'd0;
#0 add_ln7806_fu_480 = 64'd0;
#0 add_ln7797_fu_484 = 64'd0;
#0 add_ln7788_fu_488 = 64'd0;
#0 a_fu_492 = 64'd0;
#0 b_fu_496 = 64'd0;
#0 c_fu_500 = 64'd0;
#0 d_fu_504 = 64'd0;
#0 e_fu_508 = 64'd0;
#0 f_fu_512 = 64'd0;
#0 g_fu_516 = 64'd0;
#0 h_fu_520 = 64'd0;
#0 indvar_flatten_fu_524 = 135'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) test_sparsemux_161_7_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 7'h0 ),
    .din0_WIDTH( 64 ),
    .CASE1( 7'h1 ),
    .din1_WIDTH( 64 ),
    .CASE2( 7'h2 ),
    .din2_WIDTH( 64 ),
    .CASE3( 7'h3 ),
    .din3_WIDTH( 64 ),
    .CASE4( 7'h4 ),
    .din4_WIDTH( 64 ),
    .CASE5( 7'h5 ),
    .din5_WIDTH( 64 ),
    .CASE6( 7'h6 ),
    .din6_WIDTH( 64 ),
    .CASE7( 7'h7 ),
    .din7_WIDTH( 64 ),
    .CASE8( 7'h8 ),
    .din8_WIDTH( 64 ),
    .CASE9( 7'h9 ),
    .din9_WIDTH( 64 ),
    .CASE10( 7'hA ),
    .din10_WIDTH( 64 ),
    .CASE11( 7'hB ),
    .din11_WIDTH( 64 ),
    .CASE12( 7'hC ),
    .din12_WIDTH( 64 ),
    .CASE13( 7'hD ),
    .din13_WIDTH( 64 ),
    .CASE14( 7'hE ),
    .din14_WIDTH( 64 ),
    .CASE15( 7'hF ),
    .din15_WIDTH( 64 ),
    .CASE16( 7'h10 ),
    .din16_WIDTH( 64 ),
    .CASE17( 7'h11 ),
    .din17_WIDTH( 64 ),
    .CASE18( 7'h12 ),
    .din18_WIDTH( 64 ),
    .CASE19( 7'h13 ),
    .din19_WIDTH( 64 ),
    .CASE20( 7'h14 ),
    .din20_WIDTH( 64 ),
    .CASE21( 7'h15 ),
    .din21_WIDTH( 64 ),
    .CASE22( 7'h16 ),
    .din22_WIDTH( 64 ),
    .CASE23( 7'h17 ),
    .din23_WIDTH( 64 ),
    .CASE24( 7'h18 ),
    .din24_WIDTH( 64 ),
    .CASE25( 7'h19 ),
    .din25_WIDTH( 64 ),
    .CASE26( 7'h1A ),
    .din26_WIDTH( 64 ),
    .CASE27( 7'h1B ),
    .din27_WIDTH( 64 ),
    .CASE28( 7'h1C ),
    .din28_WIDTH( 64 ),
    .CASE29( 7'h1D ),
    .din29_WIDTH( 64 ),
    .CASE30( 7'h1E ),
    .din30_WIDTH( 64 ),
    .CASE31( 7'h1F ),
    .din31_WIDTH( 64 ),
    .CASE32( 7'h20 ),
    .din32_WIDTH( 64 ),
    .CASE33( 7'h21 ),
    .din33_WIDTH( 64 ),
    .CASE34( 7'h22 ),
    .din34_WIDTH( 64 ),
    .CASE35( 7'h23 ),
    .din35_WIDTH( 64 ),
    .CASE36( 7'h24 ),
    .din36_WIDTH( 64 ),
    .CASE37( 7'h25 ),
    .din37_WIDTH( 64 ),
    .CASE38( 7'h26 ),
    .din38_WIDTH( 64 ),
    .CASE39( 7'h27 ),
    .din39_WIDTH( 64 ),
    .CASE40( 7'h28 ),
    .din40_WIDTH( 64 ),
    .CASE41( 7'h29 ),
    .din41_WIDTH( 64 ),
    .CASE42( 7'h2A ),
    .din42_WIDTH( 64 ),
    .CASE43( 7'h2B ),
    .din43_WIDTH( 64 ),
    .CASE44( 7'h2C ),
    .din44_WIDTH( 64 ),
    .CASE45( 7'h2D ),
    .din45_WIDTH( 64 ),
    .CASE46( 7'h2E ),
    .din46_WIDTH( 64 ),
    .CASE47( 7'h2F ),
    .din47_WIDTH( 64 ),
    .CASE48( 7'h30 ),
    .din48_WIDTH( 64 ),
    .CASE49( 7'h31 ),
    .din49_WIDTH( 64 ),
    .CASE50( 7'h32 ),
    .din50_WIDTH( 64 ),
    .CASE51( 7'h33 ),
    .din51_WIDTH( 64 ),
    .CASE52( 7'h34 ),
    .din52_WIDTH( 64 ),
    .CASE53( 7'h35 ),
    .din53_WIDTH( 64 ),
    .CASE54( 7'h36 ),
    .din54_WIDTH( 64 ),
    .CASE55( 7'h37 ),
    .din55_WIDTH( 64 ),
    .CASE56( 7'h38 ),
    .din56_WIDTH( 64 ),
    .CASE57( 7'h39 ),
    .din57_WIDTH( 64 ),
    .CASE58( 7'h3A ),
    .din58_WIDTH( 64 ),
    .CASE59( 7'h3B ),
    .din59_WIDTH( 64 ),
    .CASE60( 7'h3C ),
    .din60_WIDTH( 64 ),
    .CASE61( 7'h3D ),
    .din61_WIDTH( 64 ),
    .CASE62( 7'h3E ),
    .din62_WIDTH( 64 ),
    .CASE63( 7'h3F ),
    .din63_WIDTH( 64 ),
    .CASE64( 7'h40 ),
    .din64_WIDTH( 64 ),
    .CASE65( 7'h41 ),
    .din65_WIDTH( 64 ),
    .CASE66( 7'h42 ),
    .din66_WIDTH( 64 ),
    .CASE67( 7'h43 ),
    .din67_WIDTH( 64 ),
    .CASE68( 7'h44 ),
    .din68_WIDTH( 64 ),
    .CASE69( 7'h45 ),
    .din69_WIDTH( 64 ),
    .CASE70( 7'h46 ),
    .din70_WIDTH( 64 ),
    .CASE71( 7'h47 ),
    .din71_WIDTH( 64 ),
    .CASE72( 7'h48 ),
    .din72_WIDTH( 64 ),
    .CASE73( 7'h49 ),
    .din73_WIDTH( 64 ),
    .CASE74( 7'h4A ),
    .din74_WIDTH( 64 ),
    .CASE75( 7'h4B ),
    .din75_WIDTH( 64 ),
    .CASE76( 7'h4C ),
    .din76_WIDTH( 64 ),
    .CASE77( 7'h4D ),
    .din77_WIDTH( 64 ),
    .CASE78( 7'h4E ),
    .din78_WIDTH( 64 ),
    .CASE79( 7'h4F ),
    .din79_WIDTH( 64 ),
    .def_WIDTH( 64 ),
    .sel_WIDTH( 7 ),
    .dout_WIDTH( 64 ))
sparsemux_161_7_64_1_1_U119(
    .din0(64'd4794697086780616226),
    .din1(64'd8158064640168781261),
    .din2(64'd13096744586834688815),
    .din3(64'd16840607885511220156),
    .din4(64'd4131703408338449720),
    .din5(64'd6480981068601479193),
    .din6(64'd10538285296894168987),
    .din7(64'd12329834152419229976),
    .din8(64'd15566598209576043074),
    .din9(64'd1334009975649890238),
    .din10(64'd2608012711638119052),
    .din11(64'd6128411473006802146),
    .din12(64'd8268148722764581231),
    .din13(64'd9286055187155687089),
    .din14(64'd11230858885718282805),
    .din15(64'd13951009754708518548),
    .din16(64'd16472876342353939154),
    .din17(64'd17275323862435702243),
    .din18(64'd1135362057144423861),
    .din19(64'd2597628984639134821),
    .din20(64'd3308224258029322869),
    .din21(64'd5365058923640841347),
    .din22(64'd6679025012923562964),
    .din23(64'd8573033837759648693),
    .din24(64'd10970295158949994411),
    .din25(64'd12119686244451234320),
    .din26(64'd12683024718118986047),
    .din27(64'd13788192230050041572),
    .din28(64'd14330467153632333762),
    .din29(64'd15395433587784984357),
    .din30(64'd489312712824947311),
    .din31(64'd1452737877330783856),
    .din32(64'd2861767655752347644),
    .din33(64'd3322285676063803686),
    .din34(64'd5560940570517711597),
    .din35(64'd5996557281743188959),
    .din36(64'd7280758554555802590),
    .din37(64'd8532644243296465576),
    .din38(64'd9350256976987008742),
    .din39(64'd10552545826968843579),
    .din40(64'd11727347734174303076),
    .din41(64'd12113106623233404929),
    .din42(64'd14000437183269869457),
    .din43(64'd14369950271660146224),
    .din44(64'd15101387698204529176),
    .din45(64'd15463397548674623760),
    .din46(64'd17586052441742319658),
    .din47(64'd1182934255886127544),
    .din48(64'd1847814050463011016),
    .din49(64'd2177327727835720531),
    .din50(64'd2830643537854262169),
    .din51(64'd3796741975233480872),
    .din52(64'd4115178125766777443),
    .din53(64'd5681478168544905931),
    .din54(64'd6601373596472566643),
    .din55(64'd7507060721942968483),
    .din56(64'd8399075790359081724),
    .din57(64'd8693463985226723168),
    .din58(64'd9568029438360202098),
    .din59(64'd10144078919501101548),
    .din60(64'd10430055236837252648),
    .din61(64'd11840083180663258601),
    .din62(64'd13761210420658862357),
    .din63(64'd14299343276471374635),
    .din64(64'd14566680578165727644),
    .din65(64'd15097957966210449927),
    .din66(64'd16922976911328602910),
    .din67(64'd17689382322260857208),
    .din68(64'd500013540394364858),
    .din69(64'd748580250866718886),
    .din70(64'd1242879168328830382),
    .din71(64'd1977374033974150939),
    .din72(64'd2944078676154940804),
    .din73(64'd3659926193048069267),
    .din74(64'd4368137639120453308),
    .din75(64'd4836135668995329356),
    .din76(64'd5532061633213252278),
    .din77(64'd6448918945643986474),
    .din78(64'd6902733635092675308),
    .din79(64'd7801388544844847127),
    .def(tmp_s_fu_944_p161),
    .sel(select_ln735_fu_766_p3),
    .dout(tmp_s_fu_944_p163)
);

test_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (icmp_ln735_reg_1830 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        a_3_reg_580 <= a_2_fu_1470_p2;
    end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        a_3_reg_580 <= 64'd2463787394917988140;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            a_fu_492 <= 64'd2463787394917988140;
        end else if (((icmp_ln735_reg_1830 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            a_fu_492 <= select_ln735_16_fu_894_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (icmp_ln735_reg_1830 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        b_24_reg_568 <= select_ln735_8_fu_830_p3;
    end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        b_24_reg_568 <= 64'd11481187982095705282;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            b_fu_496 <= 64'd11481187982095705282;
        end else if (((icmp_ln735_reg_1830 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            b_fu_496 <= select_ln735_15_fu_886_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            c_fu_500 <= 64'd2563595384472711505;
        end else if (((icmp_ln735_reg_1830 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            c_fu_500 <= select_ln735_14_fu_878_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            d_1_fu_436 <= 64'd10824532655140301501;
        end else if (((icmp_ln735_reg_1830 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            d_1_fu_436 <= select_ln735_6_fu_814_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            d_2_fu_432 <= 64'd2563595384472711505;
        end else if (((icmp_ln735_reg_1830 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            d_2_fu_432 <= select_ln735_7_fu_822_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            d_fu_504 <= 64'd10824532655140301501;
        end else if (((icmp_ln735_reg_1830 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            d_fu_504 <= select_ln735_13_fu_870_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            e_fu_508 <= 64'd10819967247969091555;
        end else if (((icmp_ln735_reg_1830 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            e_fu_508 <= select_ln735_12_fu_862_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            f_1_fu_444 <= 64'd10819967247969091555;
        end else if (((icmp_ln735_reg_1830 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            f_1_fu_444 <= e_3_fu_1398_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            f_fu_512 <= 64'd13717434660681038226;
        end else if (((icmp_ln735_reg_1830 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            f_fu_512 <= select_ln735_11_fu_854_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            g_1_fu_440 <= 64'd13717434660681038226;
        end else if (((icmp_ln735_reg_1830 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            g_1_fu_440 <= select_ln735_4_fu_798_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            g_fu_516 <= 64'd3098927326965381290;
        end else if (((icmp_ln735_reg_1830 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            g_fu_516 <= select_ln735_10_fu_846_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            h_1_fu_452 <= 64'd1060366662362279074;
        end else if (((icmp_ln735_reg_1830 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            h_1_fu_452 <= select_ln735_2_fu_782_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            h_2_fu_448 <= 64'd3098927326965381290;
        end else if (((icmp_ln735_reg_1830 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            h_2_fu_448 <= select_ln735_3_fu_790_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            h_fu_520 <= 64'd1060366662362279074;
        end else if (((icmp_ln735_reg_1830 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            h_fu_520 <= select_ln735_9_fu_838_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_524 <= 135'd0;
        end else if (((icmp_ln735_fu_675_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten_fu_524 <= add_ln735_fu_680_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            t_fu_456 <= 7'd0;
        end else if (((icmp_ln735_reg_1830 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            t_fu_456 <= add_ln749_fu_1476_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (icmp_ln735_reg_1830 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        add_ln7788_fu_488 <= add_ln778_fu_1482_p2;
        add_ln7797_fu_484 <= add_ln779_fu_1488_p2;
        add_ln7806_fu_480 <= add_ln780_fu_1494_p2;
        add_ln7815_fu_476 <= add_ln781_fu_1500_p2;
        add_ln7824_fu_472 <= add_ln782_fu_1506_p2;
        add_ln7833_fu_468 <= add_ln783_fu_1512_p2;
        add_ln7842_fu_464 <= add_ln784_fu_1518_p2;
        add_ln7851_fu_460 <= add_ln785_fu_1524_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln735_reg_1830 <= icmp_ln735_fu_675_p2;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln735_fu_675_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln7788_out_ap_vld = 1'b1;
    end else begin
        add_ln7788_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln735_fu_675_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln7797_out_ap_vld = 1'b1;
    end else begin
        add_ln7797_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln735_fu_675_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln7806_out_ap_vld = 1'b1;
    end else begin
        add_ln7806_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln735_fu_675_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln7815_out_ap_vld = 1'b1;
    end else begin
        add_ln7815_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln735_fu_675_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (icmp_ln735_reg_1830 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        w_strm_blk_n = w_strm_empty_n;
    end else begin
        w_strm_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (icmp_ln735_reg_1830 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        w_strm_read = 1'b1;
    end else begin
        w_strm_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign T1_fu_1350_p2 = (add_ln755_2_fu_1344_p2 + add_ln755_fu_1332_p2);

assign a_2_fu_1470_p2 = (add_ln764_fu_1464_p2 + xor_ln764_3_fu_1458_p2);

assign add_ln735_fu_680_p2 = (indvar_flatten_fu_524 + 135'd1);

assign add_ln749_fu_1476_p2 = (select_ln735_fu_766_p3 + 7'd1);

assign add_ln755_1_fu_1338_p2 = (xor_ln755_1_fu_1314_p2 + tmp_s_fu_944_p163);

assign add_ln755_2_fu_1344_p2 = (add_ln755_1_fu_1338_p2 + xor_ln755_3_fu_1326_p2);

assign add_ln755_fu_1332_p2 = (w_strm_dout + select_ln735_1_fu_774_p3);

assign add_ln764_fu_1464_p2 = (T1_fu_1350_p2 + xor_ln764_1_fu_1438_p2);

assign add_ln7788_out = add_ln7788_fu_488;

assign add_ln778_fu_1482_p2 = (a_2_fu_1470_p2 + select_ln735_16_fu_894_p3);

assign add_ln7797_out = add_ln7797_fu_484;

assign add_ln779_fu_1488_p2 = (select_ln735_8_fu_830_p3 + select_ln735_15_fu_886_p3);

assign add_ln7806_out = add_ln7806_fu_480;

assign add_ln780_fu_1494_p2 = (select_ln735_7_fu_822_p3 + select_ln735_14_fu_878_p3);

assign add_ln7815_out = add_ln7815_fu_476;

assign add_ln781_fu_1500_p2 = (select_ln735_6_fu_814_p3 + select_ln735_13_fu_870_p3);

assign add_ln782_fu_1506_p2 = (e_3_fu_1398_p2 + select_ln735_12_fu_862_p3);

assign add_ln783_fu_1512_p2 = (select_ln735_4_fu_798_p3 + select_ln735_11_fu_854_p3);

assign add_ln784_fu_1518_p2 = (select_ln735_3_fu_790_p3 + select_ln735_10_fu_846_p3);

assign add_ln785_fu_1524_p2 = (select_ln735_2_fu_782_p3 + select_ln735_9_fu_838_p3);

assign and_ln755_1_fu_1300_p2 = (xor_ln755_fu_1272_p2 & select_ln735_2_fu_782_p3);

assign and_ln755_fu_1294_p2 = (select_ln735_4_fu_798_p3 & select_ln735_3_fu_790_p3);

assign and_ln764_1_fu_1416_p2 = (select_ln735_7_fu_822_p3 & select_ln735_6_fu_814_p3);

assign and_ln764_fu_1410_p2 = (xor_ln764_fu_1404_p2 & select_ln735_8_fu_830_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2_grp1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2_grp1));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2_grp1));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2_grp1));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2_grp1 = ((icmp_ln735_reg_1830 == 1'd0) & (w_strm_empty_n == 1'b0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_ready = ap_ready_sig;

assign e_3_fu_1398_p2 = (T1_fu_1350_p2 + select_ln735_5_fu_806_p3);

assign icmp_ln735_fu_675_p2 = ((indvar_flatten_fu_524 == mul_ln685) ? 1'b1 : 1'b0);

assign icmp_ln749_fu_760_p2 = ((t_fu_456 == 7'd80) ? 1'b1 : 1'b0);

assign lshr_ln387_4_fu_916_p4 = {{select_ln735_4_fu_798_p3[63:18]}};

assign lshr_ln387_5_fu_930_p4 = {{select_ln735_4_fu_798_p3[63:41]}};

assign lshr_ln387_6_fu_1356_p4 = {{select_ln735_8_fu_830_p3[63:28]}};

assign lshr_ln387_7_fu_1370_p4 = {{select_ln735_8_fu_830_p3[63:34]}};

assign lshr_ln387_8_fu_1384_p4 = {{select_ln735_8_fu_830_p3[63:39]}};

assign lshr_ln_fu_902_p4 = {{select_ln735_4_fu_798_p3[63:14]}};

assign or_ln755_1_fu_1286_p3 = {{trunc_ln387_4_fu_926_p1}, {lshr_ln387_4_fu_916_p4}};

assign or_ln755_2_fu_1306_p3 = {{trunc_ln387_5_fu_940_p1}, {lshr_ln387_5_fu_930_p4}};

assign or_ln764_1_fu_1430_p3 = {{trunc_ln387_7_fu_1380_p1}, {lshr_ln387_7_fu_1370_p4}};

assign or_ln764_2_fu_1444_p3 = {{trunc_ln387_8_fu_1394_p1}, {lshr_ln387_8_fu_1384_p4}};

assign or_ln7_fu_1422_p3 = {{trunc_ln387_6_fu_1366_p1}, {lshr_ln387_6_fu_1356_p4}};

assign or_ln_fu_1278_p3 = {{trunc_ln387_fu_912_p1}, {lshr_ln_fu_902_p4}};

assign select_ln735_10_fu_846_p3 = ((icmp_ln749_fu_760_p2[0:0] == 1'b1) ? add_ln7842_fu_464 : g_fu_516);

assign select_ln735_11_fu_854_p3 = ((icmp_ln749_fu_760_p2[0:0] == 1'b1) ? add_ln7833_fu_468 : f_fu_512);

assign select_ln735_12_fu_862_p3 = ((icmp_ln749_fu_760_p2[0:0] == 1'b1) ? add_ln7824_fu_472 : e_fu_508);

assign select_ln735_13_fu_870_p3 = ((icmp_ln749_fu_760_p2[0:0] == 1'b1) ? add_ln7815_fu_476 : d_fu_504);

assign select_ln735_14_fu_878_p3 = ((icmp_ln749_fu_760_p2[0:0] == 1'b1) ? add_ln7806_fu_480 : c_fu_500);

assign select_ln735_15_fu_886_p3 = ((icmp_ln749_fu_760_p2[0:0] == 1'b1) ? add_ln7797_fu_484 : b_fu_496);

assign select_ln735_16_fu_894_p3 = ((icmp_ln749_fu_760_p2[0:0] == 1'b1) ? add_ln7788_fu_488 : a_fu_492);

assign select_ln735_1_fu_774_p3 = ((icmp_ln749_fu_760_p2[0:0] == 1'b1) ? add_ln7851_fu_460 : h_1_fu_452);

assign select_ln735_2_fu_782_p3 = ((icmp_ln749_fu_760_p2[0:0] == 1'b1) ? add_ln7842_fu_464 : h_2_fu_448);

assign select_ln735_3_fu_790_p3 = ((icmp_ln749_fu_760_p2[0:0] == 1'b1) ? add_ln7833_fu_468 : g_1_fu_440);

assign select_ln735_4_fu_798_p3 = ((icmp_ln749_fu_760_p2[0:0] == 1'b1) ? add_ln7824_fu_472 : f_1_fu_444);

assign select_ln735_5_fu_806_p3 = ((icmp_ln749_fu_760_p2[0:0] == 1'b1) ? add_ln7815_fu_476 : d_1_fu_436);

assign select_ln735_6_fu_814_p3 = ((icmp_ln749_fu_760_p2[0:0] == 1'b1) ? add_ln7806_fu_480 : d_2_fu_432);

assign select_ln735_7_fu_822_p3 = ((icmp_ln749_fu_760_p2[0:0] == 1'b1) ? add_ln7797_fu_484 : b_24_reg_568);

assign select_ln735_8_fu_830_p3 = ((icmp_ln749_fu_760_p2[0:0] == 1'b1) ? add_ln7788_fu_488 : a_3_reg_580);

assign select_ln735_9_fu_838_p3 = ((icmp_ln749_fu_760_p2[0:0] == 1'b1) ? add_ln7851_fu_460 : h_fu_520);

assign select_ln735_fu_766_p3 = ((icmp_ln749_fu_760_p2[0:0] == 1'b1) ? 7'd0 : t_fu_456);

assign tmp_s_fu_944_p161 = 'bx;

assign trunc_ln387_4_fu_926_p1 = select_ln735_4_fu_798_p3[17:0];

assign trunc_ln387_5_fu_940_p1 = select_ln735_4_fu_798_p3[40:0];

assign trunc_ln387_6_fu_1366_p1 = select_ln735_8_fu_830_p3[27:0];

assign trunc_ln387_7_fu_1380_p1 = select_ln735_8_fu_830_p3[33:0];

assign trunc_ln387_8_fu_1394_p1 = select_ln735_8_fu_830_p3[38:0];

assign trunc_ln387_fu_912_p1 = select_ln735_4_fu_798_p3[13:0];

assign xor_ln755_1_fu_1314_p2 = (and_ln755_fu_1294_p2 ^ and_ln755_1_fu_1300_p2);

assign xor_ln755_2_fu_1320_p2 = (or_ln_fu_1278_p3 ^ or_ln755_1_fu_1286_p3);

assign xor_ln755_3_fu_1326_p2 = (xor_ln755_2_fu_1320_p2 ^ or_ln755_2_fu_1306_p3);

assign xor_ln755_fu_1272_p2 = (select_ln735_4_fu_798_p3 ^ 64'd18446744073709551615);

assign xor_ln764_1_fu_1438_p2 = (and_ln764_fu_1410_p2 ^ and_ln764_1_fu_1416_p2);

assign xor_ln764_2_fu_1452_p2 = (or_ln764_2_fu_1444_p3 ^ or_ln764_1_fu_1430_p3);

assign xor_ln764_3_fu_1458_p2 = (xor_ln764_2_fu_1452_p2 ^ or_ln7_fu_1422_p3);

assign xor_ln764_fu_1404_p2 = (select_ln735_7_fu_822_p3 ^ select_ln735_6_fu_814_p3);

endmodule //test_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS
