-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity test_SHA512Digest_64u_256u_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    w_strm_dout : IN STD_LOGIC_VECTOR (63 downto 0);
    w_strm_empty_n : IN STD_LOGIC;
    w_strm_read : OUT STD_LOGIC;
    w_strm_num_data_valid : IN STD_LOGIC_VECTOR (5 downto 0);
    w_strm_fifo_cap : IN STD_LOGIC_VECTOR (5 downto 0);
    nblk_strm2_dout : IN STD_LOGIC_VECTOR (127 downto 0);
    nblk_strm2_empty_n : IN STD_LOGIC;
    nblk_strm2_read : OUT STD_LOGIC;
    nblk_strm2_num_data_valid : IN STD_LOGIC_VECTOR (5 downto 0);
    nblk_strm2_fifo_cap : IN STD_LOGIC_VECTOR (5 downto 0);
    end_nblk_strm2_dout : IN STD_LOGIC_VECTOR (0 downto 0);
    end_nblk_strm2_empty_n : IN STD_LOGIC;
    end_nblk_strm2_read : OUT STD_LOGIC;
    end_nblk_strm2_num_data_valid : IN STD_LOGIC_VECTOR (5 downto 0);
    end_nblk_strm2_fifo_cap : IN STD_LOGIC_VECTOR (5 downto 0);
    core_digest_strm_din : OUT STD_LOGIC_VECTOR (255 downto 0);
    core_digest_strm_full_n : IN STD_LOGIC;
    core_digest_strm_write : OUT STD_LOGIC;
    core_digest_strm_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    core_digest_strm_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    core_end_digest_strm_din : OUT STD_LOGIC_VECTOR (0 downto 0);
    core_end_digest_strm_full_n : IN STD_LOGIC;
    core_end_digest_strm_write : OUT STD_LOGIC;
    core_end_digest_strm_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    core_end_digest_strm_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0) );
end;


architecture behav of test_SHA512Digest_64u_256u_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_38 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_37 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110111";
    constant ap_const_lv32_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal nblk_strm2_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal end_nblk_strm2_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal core_digest_strm_blk_n : STD_LOGIC;
    signal core_end_digest_strm_blk_n : STD_LOGIC;
    signal ap_block_state1 : BOOLEAN;
    signal blkNum_reg_615 : STD_LOGIC_VECTOR (127 downto 0);
    signal ap_block_state2 : BOOLEAN;
    signal add_ln685_fu_178_p2 : STD_LOGIC_VECTOR (134 downto 0);
    signal add_ln685_reg_621 : STD_LOGIC_VECTOR (134 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_block_state5 : BOOLEAN;
    signal grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_ap_start : STD_LOGIC;
    signal grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_ap_done : STD_LOGIC;
    signal grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_ap_idle : STD_LOGIC;
    signal grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_ap_ready : STD_LOGIC;
    signal grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_w_strm_read : STD_LOGIC;
    signal grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_add_ln7788_out : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_add_ln7788_out_ap_vld : STD_LOGIC;
    signal grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_add_ln7797_out : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_add_ln7797_out_ap_vld : STD_LOGIC;
    signal grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_add_ln7806_out : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_add_ln7806_out_ap_vld : STD_LOGIC;
    signal grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_add_ln7815_out : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_add_ln7815_out_ap_vld : STD_LOGIC;
    signal end_3_reg_136 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal tmp_1_fu_156_p3 : STD_LOGIC_VECTOR (133 downto 0);
    signal tmp_2_fu_167_p3 : STD_LOGIC_VECTOR (131 downto 0);
    signal zext_ln685_fu_163_p1 : STD_LOGIC_VECTOR (134 downto 0);
    signal zext_ln685_1_fu_174_p1 : STD_LOGIC_VECTOR (134 downto 0);
    signal byte7_3_fu_453_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln816_3_fu_507_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln815_7_fu_497_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln815_6_fu_487_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_43_fu_477_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_42_fu_467_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_41_fu_457_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal byte0_3_fu_443_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal byte7_2_fu_379_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln816_2_fu_433_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln815_5_fu_423_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln815_4_fu_413_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_40_fu_403_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_39_fu_393_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_38_fu_383_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal byte0_2_fu_369_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal byte7_1_fu_305_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln816_1_fu_359_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln815_3_fu_349_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln815_2_fu_339_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_37_fu_329_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_36_fu_319_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_35_fu_309_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal byte0_1_fu_295_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal byte7_fu_231_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln1_fu_285_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln815_1_fu_275_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln_fu_265_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_34_fu_255_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_33_fu_245_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_s_fu_235_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal byte0_fu_221_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component test_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        w_strm_dout : IN STD_LOGIC_VECTOR (63 downto 0);
        w_strm_empty_n : IN STD_LOGIC;
        w_strm_read : OUT STD_LOGIC;
        w_strm_num_data_valid : IN STD_LOGIC_VECTOR (5 downto 0);
        w_strm_fifo_cap : IN STD_LOGIC_VECTOR (5 downto 0);
        mul_ln685 : IN STD_LOGIC_VECTOR (134 downto 0);
        add_ln7788_out : OUT STD_LOGIC_VECTOR (63 downto 0);
        add_ln7788_out_ap_vld : OUT STD_LOGIC;
        add_ln7797_out : OUT STD_LOGIC_VECTOR (63 downto 0);
        add_ln7797_out_ap_vld : OUT STD_LOGIC;
        add_ln7806_out : OUT STD_LOGIC_VECTOR (63 downto 0);
        add_ln7806_out_ap_vld : OUT STD_LOGIC;
        add_ln7815_out : OUT STD_LOGIC_VECTOR (63 downto 0);
        add_ln7815_out_ap_vld : OUT STD_LOGIC );
    end component;



begin
    grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145 : component test_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_ap_start,
        ap_done => grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_ap_done,
        ap_idle => grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_ap_idle,
        ap_ready => grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_ap_ready,
        w_strm_dout => w_strm_dout,
        w_strm_empty_n => w_strm_empty_n,
        w_strm_read => grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_w_strm_read,
        w_strm_num_data_valid => ap_const_lv6_0,
        w_strm_fifo_cap => ap_const_lv6_0,
        mul_ln685 => add_ln685_reg_621,
        add_ln7788_out => grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_add_ln7788_out,
        add_ln7788_out_ap_vld => grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_add_ln7788_out_ap_vld,
        add_ln7797_out => grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_add_ln7797_out,
        add_ln7797_out_ap_vld => grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_add_ln7797_out_ap_vld,
        add_ln7806_out => grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_add_ln7806_out,
        add_ln7806_out_ap_vld => grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_add_ln7806_out_ap_vld,
        add_ln7815_out => grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_add_ln7815_out,
        add_ln7815_out_ap_vld => grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_add_ln7815_out_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_state2) and (end_3_reg_136 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_ap_ready = ap_const_logic_1)) then 
                    grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                    add_ln685_reg_621(134 downto 4) <= add_ln685_fu_178_p2(134 downto 4);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state2) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                blkNum_reg_615 <= nblk_strm2_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_boolean_0 = ap_block_state5) and (ap_const_logic_1 = ap_CS_fsm_state5)))) then
                end_3_reg_136 <= end_nblk_strm2_dout;
            end if;
        end if;
    end process;
    add_ln685_reg_621(3 downto 0) <= "0000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state5, ap_block_state1, ap_block_state2, ap_block_state5, grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_ap_done, end_3_reg_136, ap_CS_fsm_state4)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_boolean_0 = ap_block_state2) and (end_3_reg_136 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                elsif (((ap_const_boolean_0 = ap_block_state2) and (end_3_reg_136 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if (((ap_const_boolean_0 = ap_block_state5) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    add_ln685_fu_178_p2 <= std_logic_vector(unsigned(zext_ln685_fu_163_p1) + unsigned(zext_ln685_1_fu_174_p1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(ap_block_state2)
    begin
        if ((ap_const_boolean_1 = ap_block_state2)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_ap_done)
    begin
        if ((grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state5_blk_assign_proc : process(ap_block_state5)
    begin
        if ((ap_const_boolean_1 = ap_block_state5)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, end_nblk_strm2_empty_n)
    begin
                ap_block_state1 <= ((end_nblk_strm2_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0));
    end process;


    ap_block_state2_assign_proc : process(nblk_strm2_empty_n, core_end_digest_strm_full_n, end_3_reg_136)
    begin
                ap_block_state2 <= (((end_3_reg_136 = ap_const_lv1_1) and (core_end_digest_strm_full_n = ap_const_logic_0)) or ((end_3_reg_136 = ap_const_lv1_0) and (nblk_strm2_empty_n = ap_const_logic_0)));
    end process;


    ap_block_state5_assign_proc : process(end_nblk_strm2_empty_n, core_digest_strm_full_n, core_end_digest_strm_full_n)
    begin
                ap_block_state5 <= ((core_end_digest_strm_full_n = ap_const_logic_0) or (core_digest_strm_full_n = ap_const_logic_0) or (end_nblk_strm2_empty_n = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state2, ap_block_state2, end_3_reg_136)
    begin
        if (((ap_const_boolean_0 = ap_block_state2) and (end_3_reg_136 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, ap_block_state2, end_3_reg_136)
    begin
        if (((ap_const_boolean_0 = ap_block_state2) and (end_3_reg_136 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    byte0_1_fu_295_p4 <= grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_add_ln7797_out(63 downto 56);
    byte0_2_fu_369_p4 <= grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_add_ln7806_out(63 downto 56);
    byte0_3_fu_443_p4 <= grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_add_ln7815_out(63 downto 56);
    byte0_fu_221_p4 <= grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_add_ln7788_out(63 downto 56);
    byte7_1_fu_305_p1 <= grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_add_ln7797_out(8 - 1 downto 0);
    byte7_2_fu_379_p1 <= grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_add_ln7806_out(8 - 1 downto 0);
    byte7_3_fu_453_p1 <= grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_add_ln7815_out(8 - 1 downto 0);
    byte7_fu_231_p1 <= grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_add_ln7788_out(8 - 1 downto 0);

    core_digest_strm_blk_n_assign_proc : process(core_digest_strm_full_n, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            core_digest_strm_blk_n <= core_digest_strm_full_n;
        else 
            core_digest_strm_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    core_digest_strm_din <= (((((((((((((((((((((((((((((((byte7_3_fu_453_p1 & trunc_ln816_3_fu_507_p4) & trunc_ln815_7_fu_497_p4) & trunc_ln815_6_fu_487_p4) & tmp_43_fu_477_p4) & tmp_42_fu_467_p4) & tmp_41_fu_457_p4) & byte0_3_fu_443_p4) & byte7_2_fu_379_p1) & trunc_ln816_2_fu_433_p4) & trunc_ln815_5_fu_423_p4) & trunc_ln815_4_fu_413_p4) & tmp_40_fu_403_p4) & tmp_39_fu_393_p4) & tmp_38_fu_383_p4) & byte0_2_fu_369_p4) & byte7_1_fu_305_p1) & trunc_ln816_1_fu_359_p4) & trunc_ln815_3_fu_349_p4) & trunc_ln815_2_fu_339_p4) & tmp_37_fu_329_p4) & tmp_36_fu_319_p4) & tmp_35_fu_309_p4) & byte0_1_fu_295_p4) & byte7_fu_231_p1) & trunc_ln1_fu_285_p4) & trunc_ln815_1_fu_275_p4) & trunc_ln_fu_265_p4) & tmp_34_fu_255_p4) & tmp_33_fu_245_p4) & tmp_s_fu_235_p4) & byte0_fu_221_p4);

    core_digest_strm_write_assign_proc : process(ap_CS_fsm_state5, ap_block_state5)
    begin
        if (((ap_const_boolean_0 = ap_block_state5) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            core_digest_strm_write <= ap_const_logic_1;
        else 
            core_digest_strm_write <= ap_const_logic_0;
        end if; 
    end process;


    core_end_digest_strm_blk_n_assign_proc : process(core_end_digest_strm_full_n, ap_CS_fsm_state2, ap_CS_fsm_state5, end_3_reg_136)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or ((end_3_reg_136 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            core_end_digest_strm_blk_n <= core_end_digest_strm_full_n;
        else 
            core_end_digest_strm_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    core_end_digest_strm_din_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state5, ap_block_state2, ap_block_state5, end_3_reg_136)
    begin
        if (((ap_const_boolean_0 = ap_block_state5) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            core_end_digest_strm_din <= ap_const_lv1_0;
        elsif (((ap_const_boolean_0 = ap_block_state2) and (end_3_reg_136 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            core_end_digest_strm_din <= ap_const_lv1_1;
        else 
            core_end_digest_strm_din <= "X";
        end if; 
    end process;


    core_end_digest_strm_write_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state5, ap_block_state2, ap_block_state5, end_3_reg_136)
    begin
        if ((((ap_const_boolean_0 = ap_block_state5) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((ap_const_boolean_0 = ap_block_state2) and (end_3_reg_136 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            core_end_digest_strm_write <= ap_const_logic_1;
        else 
            core_end_digest_strm_write <= ap_const_logic_0;
        end if; 
    end process;


    end_nblk_strm2_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, end_nblk_strm2_empty_n, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            end_nblk_strm2_blk_n <= end_nblk_strm2_empty_n;
        else 
            end_nblk_strm2_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    end_nblk_strm2_read_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state5, ap_block_state1, ap_block_state5)
    begin
        if ((((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_boolean_0 = ap_block_state5) and (ap_const_logic_1 = ap_CS_fsm_state5)))) then 
            end_nblk_strm2_read <= ap_const_logic_1;
        else 
            end_nblk_strm2_read <= ap_const_logic_0;
        end if; 
    end process;

    grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_ap_start <= grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_ap_start_reg;

    nblk_strm2_blk_n_assign_proc : process(nblk_strm2_empty_n, ap_CS_fsm_state2, end_3_reg_136)
    begin
        if (((end_3_reg_136 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            nblk_strm2_blk_n <= nblk_strm2_empty_n;
        else 
            nblk_strm2_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    nblk_strm2_read_assign_proc : process(ap_CS_fsm_state2, ap_block_state2, end_3_reg_136)
    begin
        if (((ap_const_boolean_0 = ap_block_state2) and (end_3_reg_136 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            nblk_strm2_read <= ap_const_logic_1;
        else 
            nblk_strm2_read <= ap_const_logic_0;
        end if; 
    end process;

    tmp_1_fu_156_p3 <= (blkNum_reg_615 & ap_const_lv6_0);
    tmp_2_fu_167_p3 <= (blkNum_reg_615 & ap_const_lv4_0);
    tmp_33_fu_245_p4 <= grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_add_ln7788_out(47 downto 40);
    tmp_34_fu_255_p4 <= grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_add_ln7788_out(39 downto 32);
    tmp_35_fu_309_p4 <= grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_add_ln7797_out(55 downto 48);
    tmp_36_fu_319_p4 <= grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_add_ln7797_out(47 downto 40);
    tmp_37_fu_329_p4 <= grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_add_ln7797_out(39 downto 32);
    tmp_38_fu_383_p4 <= grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_add_ln7806_out(55 downto 48);
    tmp_39_fu_393_p4 <= grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_add_ln7806_out(47 downto 40);
    tmp_40_fu_403_p4 <= grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_add_ln7806_out(39 downto 32);
    tmp_41_fu_457_p4 <= grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_add_ln7815_out(55 downto 48);
    tmp_42_fu_467_p4 <= grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_add_ln7815_out(47 downto 40);
    tmp_43_fu_477_p4 <= grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_add_ln7815_out(39 downto 32);
    tmp_s_fu_235_p4 <= grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_add_ln7788_out(55 downto 48);
    trunc_ln1_fu_285_p4 <= grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_add_ln7788_out(15 downto 8);
    trunc_ln815_1_fu_275_p4 <= grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_add_ln7788_out(23 downto 16);
    trunc_ln815_2_fu_339_p4 <= grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_add_ln7797_out(31 downto 24);
    trunc_ln815_3_fu_349_p4 <= grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_add_ln7797_out(23 downto 16);
    trunc_ln815_4_fu_413_p4 <= grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_add_ln7806_out(31 downto 24);
    trunc_ln815_5_fu_423_p4 <= grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_add_ln7806_out(23 downto 16);
    trunc_ln815_6_fu_487_p4 <= grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_add_ln7815_out(31 downto 24);
    trunc_ln815_7_fu_497_p4 <= grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_add_ln7815_out(23 downto 16);
    trunc_ln816_1_fu_359_p4 <= grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_add_ln7797_out(15 downto 8);
    trunc_ln816_2_fu_433_p4 <= grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_add_ln7806_out(15 downto 8);
    trunc_ln816_3_fu_507_p4 <= grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_add_ln7815_out(15 downto 8);
    trunc_ln_fu_265_p4 <= grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_add_ln7788_out(31 downto 24);
    w_strm_read <= grp_SHA512Digest_Pipeline_LOOP_SHA1_DIGEST_NBLK_LOOP_SHA1_UPDATE_80_ROUNDS_fu_145_w_strm_read;
    zext_ln685_1_fu_174_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_fu_167_p3),135));
    zext_ln685_fu_163_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_fu_156_p3),135));
end behav;
