-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity test_axis_to_core is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    msg_strm_TDATA : IN STD_LOGIC_VECTOR (63 downto 0);
    msg_strm_TVALID : IN STD_LOGIC;
    msg_strm_TREADY : OUT STD_LOGIC;
    msg_strm_TKEEP : IN STD_LOGIC_VECTOR (7 downto 0);
    msg_strm_TSTRB : IN STD_LOGIC_VECTOR (7 downto 0);
    msg_strm_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    msg_strm_TDEST : IN STD_LOGIC_VECTOR (2 downto 0);
    msg_len : IN STD_LOGIC_VECTOR (127 downto 0);
    core_msg_strm_din : OUT STD_LOGIC_VECTOR (63 downto 0);
    core_msg_strm_full_n : IN STD_LOGIC;
    core_msg_strm_write : OUT STD_LOGIC;
    core_msg_strm_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    core_msg_strm_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    core_len_strm_din : OUT STD_LOGIC_VECTOR (127 downto 0);
    core_len_strm_full_n : IN STD_LOGIC;
    core_len_strm_write : OUT STD_LOGIC;
    core_len_strm_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    core_len_strm_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    core_end_len_strm_din : OUT STD_LOGIC_VECTOR (0 downto 0);
    core_end_len_strm_full_n : IN STD_LOGIC;
    core_end_len_strm_write : OUT STD_LOGIC;
    core_end_len_strm_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    core_end_len_strm_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0) );
end;


architecture behav of test_axis_to_core is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv129_lc_1 : STD_LOGIC_VECTOR (128 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000111";
    constant ap_const_lv32_80 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal core_len_strm_blk_n : STD_LOGIC;
    signal core_end_len_strm_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal trunc_ln_reg_164 : STD_LOGIC_VECTOR (125 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal grp_axis_to_core_Pipeline_FEED_LOOP_fu_85_ap_start : STD_LOGIC;
    signal grp_axis_to_core_Pipeline_FEED_LOOP_fu_85_ap_done : STD_LOGIC;
    signal grp_axis_to_core_Pipeline_FEED_LOOP_fu_85_ap_idle : STD_LOGIC;
    signal grp_axis_to_core_Pipeline_FEED_LOOP_fu_85_ap_ready : STD_LOGIC;
    signal grp_axis_to_core_Pipeline_FEED_LOOP_fu_85_core_msg_strm_din : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_axis_to_core_Pipeline_FEED_LOOP_fu_85_core_msg_strm_write : STD_LOGIC;
    signal grp_axis_to_core_Pipeline_FEED_LOOP_fu_85_msg_strm_TREADY : STD_LOGIC;
    signal grp_axis_to_core_Pipeline_FEED_LOOP_fu_85_ap_start_reg : STD_LOGIC := '0';
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_NS_fsm_state2 : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal zext_ln65_fu_102_p1 : STD_LOGIC_VECTOR (128 downto 0);
    signal add_ln65_fu_106_p2 : STD_LOGIC_VECTOR (128 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal regslice_both_msg_strm_V_data_V_U_apdone_blk : STD_LOGIC;
    signal msg_strm_TDATA_int_regslice : STD_LOGIC_VECTOR (63 downto 0);
    signal msg_strm_TVALID_int_regslice : STD_LOGIC;
    signal msg_strm_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_msg_strm_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_msg_strm_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal msg_strm_TKEEP_int_regslice : STD_LOGIC_VECTOR (7 downto 0);
    signal regslice_both_msg_strm_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_msg_strm_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_msg_strm_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal msg_strm_TSTRB_int_regslice : STD_LOGIC_VECTOR (7 downto 0);
    signal regslice_both_msg_strm_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_msg_strm_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_msg_strm_V_last_V_U_apdone_blk : STD_LOGIC;
    signal msg_strm_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_msg_strm_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_msg_strm_V_last_V_U_ack_in : STD_LOGIC;
    signal regslice_both_msg_strm_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal msg_strm_TDEST_int_regslice : STD_LOGIC_VECTOR (2 downto 0);
    signal regslice_both_msg_strm_V_dest_V_U_vld_out : STD_LOGIC;
    signal regslice_both_msg_strm_V_dest_V_U_ack_in : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component test_axis_to_core_Pipeline_FEED_LOOP IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        msg_strm_TVALID : IN STD_LOGIC;
        core_msg_strm_din : OUT STD_LOGIC_VECTOR (63 downto 0);
        core_msg_strm_full_n : IN STD_LOGIC;
        core_msg_strm_write : OUT STD_LOGIC;
        core_msg_strm_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        core_msg_strm_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        trunc_ln : IN STD_LOGIC_VECTOR (125 downto 0);
        msg_strm_TDATA : IN STD_LOGIC_VECTOR (63 downto 0);
        msg_strm_TREADY : OUT STD_LOGIC;
        msg_strm_TKEEP : IN STD_LOGIC_VECTOR (7 downto 0);
        msg_strm_TSTRB : IN STD_LOGIC_VECTOR (7 downto 0);
        msg_strm_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        msg_strm_TDEST : IN STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component test_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    grp_axis_to_core_Pipeline_FEED_LOOP_fu_85 : component test_axis_to_core_Pipeline_FEED_LOOP
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_axis_to_core_Pipeline_FEED_LOOP_fu_85_ap_start,
        ap_done => grp_axis_to_core_Pipeline_FEED_LOOP_fu_85_ap_done,
        ap_idle => grp_axis_to_core_Pipeline_FEED_LOOP_fu_85_ap_idle,
        ap_ready => grp_axis_to_core_Pipeline_FEED_LOOP_fu_85_ap_ready,
        msg_strm_TVALID => msg_strm_TVALID_int_regslice,
        core_msg_strm_din => grp_axis_to_core_Pipeline_FEED_LOOP_fu_85_core_msg_strm_din,
        core_msg_strm_full_n => core_msg_strm_full_n,
        core_msg_strm_write => grp_axis_to_core_Pipeline_FEED_LOOP_fu_85_core_msg_strm_write,
        core_msg_strm_num_data_valid => ap_const_lv7_0,
        core_msg_strm_fifo_cap => ap_const_lv7_0,
        trunc_ln => trunc_ln_reg_164,
        msg_strm_TDATA => msg_strm_TDATA_int_regslice,
        msg_strm_TREADY => grp_axis_to_core_Pipeline_FEED_LOOP_fu_85_msg_strm_TREADY,
        msg_strm_TKEEP => msg_strm_TKEEP_int_regslice,
        msg_strm_TSTRB => msg_strm_TSTRB_int_regslice,
        msg_strm_TLAST => msg_strm_TLAST_int_regslice,
        msg_strm_TDEST => msg_strm_TDEST_int_regslice);

    regslice_both_msg_strm_V_data_V_U : component test_regslice_both
    generic map (
        DataWidth => 64)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => msg_strm_TDATA,
        vld_in => msg_strm_TVALID,
        ack_in => regslice_both_msg_strm_V_data_V_U_ack_in,
        data_out => msg_strm_TDATA_int_regslice,
        vld_out => msg_strm_TVALID_int_regslice,
        ack_out => msg_strm_TREADY_int_regslice,
        apdone_blk => regslice_both_msg_strm_V_data_V_U_apdone_blk);

    regslice_both_msg_strm_V_keep_V_U : component test_regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => msg_strm_TKEEP,
        vld_in => msg_strm_TVALID,
        ack_in => regslice_both_msg_strm_V_keep_V_U_ack_in,
        data_out => msg_strm_TKEEP_int_regslice,
        vld_out => regslice_both_msg_strm_V_keep_V_U_vld_out,
        ack_out => msg_strm_TREADY_int_regslice,
        apdone_blk => regslice_both_msg_strm_V_keep_V_U_apdone_blk);

    regslice_both_msg_strm_V_strb_V_U : component test_regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => msg_strm_TSTRB,
        vld_in => msg_strm_TVALID,
        ack_in => regslice_both_msg_strm_V_strb_V_U_ack_in,
        data_out => msg_strm_TSTRB_int_regslice,
        vld_out => regslice_both_msg_strm_V_strb_V_U_vld_out,
        ack_out => msg_strm_TREADY_int_regslice,
        apdone_blk => regslice_both_msg_strm_V_strb_V_U_apdone_blk);

    regslice_both_msg_strm_V_last_V_U : component test_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => msg_strm_TLAST,
        vld_in => msg_strm_TVALID,
        ack_in => regslice_both_msg_strm_V_last_V_U_ack_in,
        data_out => msg_strm_TLAST_int_regslice,
        vld_out => regslice_both_msg_strm_V_last_V_U_vld_out,
        ack_out => msg_strm_TREADY_int_regslice,
        apdone_blk => regslice_both_msg_strm_V_last_V_U_apdone_blk);

    regslice_both_msg_strm_V_dest_V_U : component test_regslice_both
    generic map (
        DataWidth => 3)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => msg_strm_TDEST,
        vld_in => msg_strm_TVALID,
        ack_in => regslice_both_msg_strm_V_dest_V_U_ack_in,
        data_out => msg_strm_TDEST_int_regslice,
        vld_out => regslice_both_msg_strm_V_dest_V_U_vld_out,
        ack_out => msg_strm_TREADY_int_regslice,
        apdone_blk => regslice_both_msg_strm_V_dest_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((core_end_len_strm_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_axis_to_core_Pipeline_FEED_LOOP_fu_85_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_axis_to_core_Pipeline_FEED_LOOP_fu_85_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_logic_1 = ap_NS_fsm_state2))) then 
                    grp_axis_to_core_Pipeline_FEED_LOOP_fu_85_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_axis_to_core_Pipeline_FEED_LOOP_fu_85_ap_ready = ap_const_logic_1)) then 
                    grp_axis_to_core_Pipeline_FEED_LOOP_fu_85_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                trunc_ln_reg_164 <= add_ln65_fu_106_p2(128 downto 3);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, core_end_len_strm_full_n, ap_CS_fsm_state4, ap_block_state1, grp_axis_to_core_Pipeline_FEED_LOOP_fu_85_ap_done, ap_CS_fsm_state3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((grp_axis_to_core_Pipeline_FEED_LOOP_fu_85_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if (((core_end_len_strm_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    add_ln65_fu_106_p2 <= std_logic_vector(unsigned(zext_ln65_fu_102_p1) + unsigned(ap_const_lv129_lc_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_NS_fsm_state2 <= ap_NS_fsm(1);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_axis_to_core_Pipeline_FEED_LOOP_fu_85_ap_done)
    begin
        if ((grp_axis_to_core_Pipeline_FEED_LOOP_fu_85_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state4_blk_assign_proc : process(core_end_len_strm_full_n)
    begin
        if ((core_end_len_strm_full_n = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg, core_len_strm_full_n, core_end_len_strm_full_n)
    begin
                ap_block_state1 <= ((core_end_len_strm_full_n = ap_const_logic_0) or (core_len_strm_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, core_end_len_strm_full_n, ap_CS_fsm_state4)
    begin
        if (((core_end_len_strm_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;

    core_end_len_strm_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, core_end_len_strm_full_n, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            core_end_len_strm_blk_n <= core_end_len_strm_full_n;
        else 
            core_end_len_strm_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    core_end_len_strm_din_assign_proc : process(ap_CS_fsm_state1, core_end_len_strm_full_n, ap_CS_fsm_state4, ap_block_state1)
    begin
        if (((core_end_len_strm_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            core_end_len_strm_din <= ap_const_lv1_1;
        elsif (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            core_end_len_strm_din <= ap_const_lv1_0;
        else 
            core_end_len_strm_din <= "X";
        end if; 
    end process;


    core_end_len_strm_write_assign_proc : process(ap_CS_fsm_state1, core_end_len_strm_full_n, ap_CS_fsm_state4, ap_block_state1)
    begin
        if ((((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((core_end_len_strm_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4)))) then 
            core_end_len_strm_write <= ap_const_logic_1;
        else 
            core_end_len_strm_write <= ap_const_logic_0;
        end if; 
    end process;


    core_len_strm_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, core_len_strm_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            core_len_strm_blk_n <= core_len_strm_full_n;
        else 
            core_len_strm_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    core_len_strm_din <= msg_len;

    core_len_strm_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            core_len_strm_write <= ap_const_logic_1;
        else 
            core_len_strm_write <= ap_const_logic_0;
        end if; 
    end process;

    core_msg_strm_din <= grp_axis_to_core_Pipeline_FEED_LOOP_fu_85_core_msg_strm_din;
    core_msg_strm_write <= grp_axis_to_core_Pipeline_FEED_LOOP_fu_85_core_msg_strm_write;
    grp_axis_to_core_Pipeline_FEED_LOOP_fu_85_ap_start <= grp_axis_to_core_Pipeline_FEED_LOOP_fu_85_ap_start_reg;

    internal_ap_ready_assign_proc : process(core_end_len_strm_full_n, ap_CS_fsm_state4)
    begin
        if (((core_end_len_strm_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    msg_strm_TREADY <= regslice_both_msg_strm_V_data_V_U_ack_in;

    msg_strm_TREADY_int_regslice_assign_proc : process(grp_axis_to_core_Pipeline_FEED_LOOP_fu_85_msg_strm_TREADY, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            msg_strm_TREADY_int_regslice <= grp_axis_to_core_Pipeline_FEED_LOOP_fu_85_msg_strm_TREADY;
        else 
            msg_strm_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln65_fu_102_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(msg_len),129));
end behav;
