-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity test is
generic (
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 6;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32 );
port (
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    interrupt : OUT STD_LOGIC;
    msg_strm_TDATA : IN STD_LOGIC_VECTOR (63 downto 0);
    msg_strm_TKEEP : IN STD_LOGIC_VECTOR (7 downto 0);
    msg_strm_TSTRB : IN STD_LOGIC_VECTOR (7 downto 0);
    msg_strm_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    msg_strm_TDEST : IN STD_LOGIC_VECTOR (2 downto 0);
    digest_strm_TDATA : OUT STD_LOGIC_VECTOR (255 downto 0);
    digest_strm_TKEEP : OUT STD_LOGIC_VECTOR (31 downto 0);
    digest_strm_TSTRB : OUT STD_LOGIC_VECTOR (31 downto 0);
    digest_strm_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    digest_strm_TDEST : OUT STD_LOGIC_VECTOR (2 downto 0);
    msg_strm_TVALID : IN STD_LOGIC;
    msg_strm_TREADY : OUT STD_LOGIC;
    digest_strm_TVALID : OUT STD_LOGIC;
    digest_strm_TREADY : IN STD_LOGIC );
end;


architecture behav of test is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "test_test,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu3eg-sbva484-1-i,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=7.686488,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=4,HLS_SYN_DSP=0,HLS_SYN_FF=11208,HLS_SYN_LUT=9567,HLS_VERSION=2024_2}";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_rst_n_inv : STD_LOGIC;
    signal msg_len : STD_LOGIC_VECTOR (127 downto 0);
    signal dest_id : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_start : STD_LOGIC;
    signal ap_ready : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal entry_proc_U0_ap_start : STD_LOGIC;
    signal entry_proc_U0_ap_done : STD_LOGIC;
    signal entry_proc_U0_ap_continue : STD_LOGIC;
    signal entry_proc_U0_ap_idle : STD_LOGIC;
    signal entry_proc_U0_ap_ready : STD_LOGIC;
    signal entry_proc_U0_start_out : STD_LOGIC;
    signal entry_proc_U0_start_write : STD_LOGIC;
    signal entry_proc_U0_dest_id_c_din : STD_LOGIC_VECTOR (1 downto 0);
    signal entry_proc_U0_dest_id_c_write : STD_LOGIC;
    signal axis_to_core_U0_ap_start : STD_LOGIC;
    signal axis_to_core_U0_ap_done : STD_LOGIC;
    signal axis_to_core_U0_ap_continue : STD_LOGIC;
    signal axis_to_core_U0_ap_idle : STD_LOGIC;
    signal axis_to_core_U0_ap_ready : STD_LOGIC;
    signal axis_to_core_U0_start_out : STD_LOGIC;
    signal axis_to_core_U0_start_write : STD_LOGIC;
    signal axis_to_core_U0_msg_strm_TREADY : STD_LOGIC;
    signal axis_to_core_U0_core_msg_strm_din : STD_LOGIC_VECTOR (63 downto 0);
    signal axis_to_core_U0_core_msg_strm_write : STD_LOGIC;
    signal axis_to_core_U0_core_len_strm_din : STD_LOGIC_VECTOR (127 downto 0);
    signal axis_to_core_U0_core_len_strm_write : STD_LOGIC;
    signal axis_to_core_U0_core_end_len_strm_din : STD_LOGIC_VECTOR (0 downto 0);
    signal axis_to_core_U0_core_end_len_strm_write : STD_LOGIC;
    signal sha512_t_64u_256u_U0_ap_start : STD_LOGIC;
    signal sha512_t_64u_256u_U0_ap_done : STD_LOGIC;
    signal sha512_t_64u_256u_U0_ap_continue : STD_LOGIC;
    signal sha512_t_64u_256u_U0_ap_idle : STD_LOGIC;
    signal sha512_t_64u_256u_U0_ap_ready : STD_LOGIC;
    signal sha512_t_64u_256u_U0_core_msg_strm_read : STD_LOGIC;
    signal sha512_t_64u_256u_U0_core_len_strm_read : STD_LOGIC;
    signal sha512_t_64u_256u_U0_core_end_len_strm_read : STD_LOGIC;
    signal sha512_t_64u_256u_U0_core_digest_strm_din : STD_LOGIC_VECTOR (255 downto 0);
    signal sha512_t_64u_256u_U0_core_digest_strm_write : STD_LOGIC;
    signal sha512_t_64u_256u_U0_core_end_digest_strm_din : STD_LOGIC_VECTOR (0 downto 0);
    signal sha512_t_64u_256u_U0_core_end_digest_strm_write : STD_LOGIC;
    signal core_to_axis_U0_ap_start : STD_LOGIC;
    signal core_to_axis_U0_ap_done : STD_LOGIC;
    signal core_to_axis_U0_ap_continue : STD_LOGIC;
    signal core_to_axis_U0_ap_idle : STD_LOGIC;
    signal core_to_axis_U0_ap_ready : STD_LOGIC;
    signal core_to_axis_U0_core_digest_strm_read : STD_LOGIC;
    signal core_to_axis_U0_core_end_digest_strm_read : STD_LOGIC;
    signal core_to_axis_U0_digest_strm_TDATA : STD_LOGIC_VECTOR (255 downto 0);
    signal core_to_axis_U0_digest_strm_TVALID : STD_LOGIC;
    signal core_to_axis_U0_digest_strm_TKEEP : STD_LOGIC_VECTOR (31 downto 0);
    signal core_to_axis_U0_digest_strm_TSTRB : STD_LOGIC_VECTOR (31 downto 0);
    signal core_to_axis_U0_digest_strm_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal core_to_axis_U0_digest_strm_TDEST : STD_LOGIC_VECTOR (2 downto 0);
    signal core_to_axis_U0_dest_id_read : STD_LOGIC;
    signal dest_id_c_full_n : STD_LOGIC;
    signal dest_id_c_dout : STD_LOGIC_VECTOR (1 downto 0);
    signal dest_id_c_empty_n : STD_LOGIC;
    signal dest_id_c_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal dest_id_c_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal core_msg_strm_full_n : STD_LOGIC;
    signal core_msg_strm_dout : STD_LOGIC_VECTOR (63 downto 0);
    signal core_msg_strm_empty_n : STD_LOGIC;
    signal core_msg_strm_num_data_valid : STD_LOGIC_VECTOR (6 downto 0);
    signal core_msg_strm_fifo_cap : STD_LOGIC_VECTOR (6 downto 0);
    signal core_len_strm_full_n : STD_LOGIC;
    signal core_len_strm_dout : STD_LOGIC_VECTOR (127 downto 0);
    signal core_len_strm_empty_n : STD_LOGIC;
    signal core_len_strm_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal core_len_strm_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal core_end_len_strm_full_n : STD_LOGIC;
    signal core_end_len_strm_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal core_end_len_strm_empty_n : STD_LOGIC;
    signal core_end_len_strm_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal core_end_len_strm_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal core_digest_strm_full_n : STD_LOGIC;
    signal core_digest_strm_dout : STD_LOGIC_VECTOR (255 downto 0);
    signal core_digest_strm_empty_n : STD_LOGIC;
    signal core_digest_strm_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal core_digest_strm_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal core_end_digest_strm_full_n : STD_LOGIC;
    signal core_end_digest_strm_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal core_end_digest_strm_empty_n : STD_LOGIC;
    signal core_end_digest_strm_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal core_end_digest_strm_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_sync_ready : STD_LOGIC;
    signal ap_sync_reg_entry_proc_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_entry_proc_U0_ap_ready : STD_LOGIC;
    signal ap_sync_reg_axis_to_core_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_axis_to_core_U0_ap_ready : STD_LOGIC;
    signal start_for_core_to_axis_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_core_to_axis_U0_full_n : STD_LOGIC;
    signal start_for_core_to_axis_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_core_to_axis_U0_empty_n : STD_LOGIC;
    signal start_for_sha512_t_64u_256u_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_sha512_t_64u_256u_U0_full_n : STD_LOGIC;
    signal start_for_sha512_t_64u_256u_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_sha512_t_64u_256u_U0_empty_n : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component test_entry_proc IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        dest_id : IN STD_LOGIC_VECTOR (1 downto 0);
        dest_id_c_din : OUT STD_LOGIC_VECTOR (1 downto 0);
        dest_id_c_full_n : IN STD_LOGIC;
        dest_id_c_write : OUT STD_LOGIC;
        dest_id_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        dest_id_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component test_axis_to_core IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        msg_strm_TDATA : IN STD_LOGIC_VECTOR (63 downto 0);
        msg_strm_TVALID : IN STD_LOGIC;
        msg_strm_TREADY : OUT STD_LOGIC;
        msg_strm_TKEEP : IN STD_LOGIC_VECTOR (7 downto 0);
        msg_strm_TSTRB : IN STD_LOGIC_VECTOR (7 downto 0);
        msg_strm_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        msg_strm_TDEST : IN STD_LOGIC_VECTOR (2 downto 0);
        msg_len : IN STD_LOGIC_VECTOR (127 downto 0);
        core_msg_strm_din : OUT STD_LOGIC_VECTOR (63 downto 0);
        core_msg_strm_full_n : IN STD_LOGIC;
        core_msg_strm_write : OUT STD_LOGIC;
        core_msg_strm_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        core_msg_strm_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        core_len_strm_din : OUT STD_LOGIC_VECTOR (127 downto 0);
        core_len_strm_full_n : IN STD_LOGIC;
        core_len_strm_write : OUT STD_LOGIC;
        core_len_strm_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        core_len_strm_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        core_end_len_strm_din : OUT STD_LOGIC_VECTOR (0 downto 0);
        core_end_len_strm_full_n : IN STD_LOGIC;
        core_end_len_strm_write : OUT STD_LOGIC;
        core_end_len_strm_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        core_end_len_strm_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component test_sha512_t_64u_256u_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        core_msg_strm_dout : IN STD_LOGIC_VECTOR (63 downto 0);
        core_msg_strm_empty_n : IN STD_LOGIC;
        core_msg_strm_read : OUT STD_LOGIC;
        core_msg_strm_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        core_msg_strm_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        core_len_strm_dout : IN STD_LOGIC_VECTOR (127 downto 0);
        core_len_strm_empty_n : IN STD_LOGIC;
        core_len_strm_read : OUT STD_LOGIC;
        core_len_strm_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        core_len_strm_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        core_end_len_strm_dout : IN STD_LOGIC_VECTOR (0 downto 0);
        core_end_len_strm_empty_n : IN STD_LOGIC;
        core_end_len_strm_read : OUT STD_LOGIC;
        core_end_len_strm_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        core_end_len_strm_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        core_digest_strm_din : OUT STD_LOGIC_VECTOR (255 downto 0);
        core_digest_strm_full_n : IN STD_LOGIC;
        core_digest_strm_write : OUT STD_LOGIC;
        core_digest_strm_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        core_digest_strm_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        core_end_digest_strm_din : OUT STD_LOGIC_VECTOR (0 downto 0);
        core_end_digest_strm_full_n : IN STD_LOGIC;
        core_end_digest_strm_write : OUT STD_LOGIC;
        core_end_digest_strm_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        core_end_digest_strm_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component test_core_to_axis IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        core_digest_strm_dout : IN STD_LOGIC_VECTOR (255 downto 0);
        core_digest_strm_empty_n : IN STD_LOGIC;
        core_digest_strm_read : OUT STD_LOGIC;
        core_digest_strm_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        core_digest_strm_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        core_end_digest_strm_dout : IN STD_LOGIC_VECTOR (0 downto 0);
        core_end_digest_strm_empty_n : IN STD_LOGIC;
        core_end_digest_strm_read : OUT STD_LOGIC;
        core_end_digest_strm_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        core_end_digest_strm_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        digest_strm_TDATA : OUT STD_LOGIC_VECTOR (255 downto 0);
        digest_strm_TVALID : OUT STD_LOGIC;
        digest_strm_TREADY : IN STD_LOGIC;
        digest_strm_TKEEP : OUT STD_LOGIC_VECTOR (31 downto 0);
        digest_strm_TSTRB : OUT STD_LOGIC_VECTOR (31 downto 0);
        digest_strm_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        digest_strm_TDEST : OUT STD_LOGIC_VECTOR (2 downto 0);
        dest_id_dout : IN STD_LOGIC_VECTOR (1 downto 0);
        dest_id_empty_n : IN STD_LOGIC;
        dest_id_read : OUT STD_LOGIC;
        dest_id_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        dest_id_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component test_fifo_w2_d4_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (1 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (1 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component test_fifo_w64_d64_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (63 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (63 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (6 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (6 downto 0) );
    end component;


    component test_fifo_w128_d4_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (127 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (127 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component test_fifo_w1_d4_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component test_fifo_w256_d4_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (255 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (255 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component test_start_for_core_to_axis_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component test_start_for_sha512_t_64u_256u_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component test_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        msg_len : OUT STD_LOGIC_VECTOR (127 downto 0);
        dest_id : OUT STD_LOGIC_VECTOR (1 downto 0);
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;



begin
    control_s_axi_U : component test_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        msg_len => msg_len,
        dest_id => dest_id,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    entry_proc_U0 : component test_entry_proc
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => entry_proc_U0_ap_start,
        start_full_n => start_for_core_to_axis_U0_full_n,
        ap_done => entry_proc_U0_ap_done,
        ap_continue => entry_proc_U0_ap_continue,
        ap_idle => entry_proc_U0_ap_idle,
        ap_ready => entry_proc_U0_ap_ready,
        start_out => entry_proc_U0_start_out,
        start_write => entry_proc_U0_start_write,
        dest_id => dest_id,
        dest_id_c_din => entry_proc_U0_dest_id_c_din,
        dest_id_c_full_n => dest_id_c_full_n,
        dest_id_c_write => entry_proc_U0_dest_id_c_write,
        dest_id_c_num_data_valid => dest_id_c_num_data_valid,
        dest_id_c_fifo_cap => dest_id_c_fifo_cap);

    axis_to_core_U0 : component test_axis_to_core
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => axis_to_core_U0_ap_start,
        start_full_n => start_for_sha512_t_64u_256u_U0_full_n,
        ap_done => axis_to_core_U0_ap_done,
        ap_continue => axis_to_core_U0_ap_continue,
        ap_idle => axis_to_core_U0_ap_idle,
        ap_ready => axis_to_core_U0_ap_ready,
        start_out => axis_to_core_U0_start_out,
        start_write => axis_to_core_U0_start_write,
        msg_strm_TDATA => msg_strm_TDATA,
        msg_strm_TVALID => msg_strm_TVALID,
        msg_strm_TREADY => axis_to_core_U0_msg_strm_TREADY,
        msg_strm_TKEEP => msg_strm_TKEEP,
        msg_strm_TSTRB => msg_strm_TSTRB,
        msg_strm_TLAST => msg_strm_TLAST,
        msg_strm_TDEST => msg_strm_TDEST,
        msg_len => msg_len,
        core_msg_strm_din => axis_to_core_U0_core_msg_strm_din,
        core_msg_strm_full_n => core_msg_strm_full_n,
        core_msg_strm_write => axis_to_core_U0_core_msg_strm_write,
        core_msg_strm_num_data_valid => core_msg_strm_num_data_valid,
        core_msg_strm_fifo_cap => core_msg_strm_fifo_cap,
        core_len_strm_din => axis_to_core_U0_core_len_strm_din,
        core_len_strm_full_n => core_len_strm_full_n,
        core_len_strm_write => axis_to_core_U0_core_len_strm_write,
        core_len_strm_num_data_valid => core_len_strm_num_data_valid,
        core_len_strm_fifo_cap => core_len_strm_fifo_cap,
        core_end_len_strm_din => axis_to_core_U0_core_end_len_strm_din,
        core_end_len_strm_full_n => core_end_len_strm_full_n,
        core_end_len_strm_write => axis_to_core_U0_core_end_len_strm_write,
        core_end_len_strm_num_data_valid => core_end_len_strm_num_data_valid,
        core_end_len_strm_fifo_cap => core_end_len_strm_fifo_cap);

    sha512_t_64u_256u_U0 : component test_sha512_t_64u_256u_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => sha512_t_64u_256u_U0_ap_start,
        ap_done => sha512_t_64u_256u_U0_ap_done,
        ap_continue => sha512_t_64u_256u_U0_ap_continue,
        ap_idle => sha512_t_64u_256u_U0_ap_idle,
        ap_ready => sha512_t_64u_256u_U0_ap_ready,
        core_msg_strm_dout => core_msg_strm_dout,
        core_msg_strm_empty_n => core_msg_strm_empty_n,
        core_msg_strm_read => sha512_t_64u_256u_U0_core_msg_strm_read,
        core_msg_strm_num_data_valid => core_msg_strm_num_data_valid,
        core_msg_strm_fifo_cap => core_msg_strm_fifo_cap,
        core_len_strm_dout => core_len_strm_dout,
        core_len_strm_empty_n => core_len_strm_empty_n,
        core_len_strm_read => sha512_t_64u_256u_U0_core_len_strm_read,
        core_len_strm_num_data_valid => core_len_strm_num_data_valid,
        core_len_strm_fifo_cap => core_len_strm_fifo_cap,
        core_end_len_strm_dout => core_end_len_strm_dout,
        core_end_len_strm_empty_n => core_end_len_strm_empty_n,
        core_end_len_strm_read => sha512_t_64u_256u_U0_core_end_len_strm_read,
        core_end_len_strm_num_data_valid => core_end_len_strm_num_data_valid,
        core_end_len_strm_fifo_cap => core_end_len_strm_fifo_cap,
        core_digest_strm_din => sha512_t_64u_256u_U0_core_digest_strm_din,
        core_digest_strm_full_n => core_digest_strm_full_n,
        core_digest_strm_write => sha512_t_64u_256u_U0_core_digest_strm_write,
        core_digest_strm_num_data_valid => core_digest_strm_num_data_valid,
        core_digest_strm_fifo_cap => core_digest_strm_fifo_cap,
        core_end_digest_strm_din => sha512_t_64u_256u_U0_core_end_digest_strm_din,
        core_end_digest_strm_full_n => core_end_digest_strm_full_n,
        core_end_digest_strm_write => sha512_t_64u_256u_U0_core_end_digest_strm_write,
        core_end_digest_strm_num_data_valid => core_end_digest_strm_num_data_valid,
        core_end_digest_strm_fifo_cap => core_end_digest_strm_fifo_cap);

    core_to_axis_U0 : component test_core_to_axis
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => core_to_axis_U0_ap_start,
        ap_done => core_to_axis_U0_ap_done,
        ap_continue => core_to_axis_U0_ap_continue,
        ap_idle => core_to_axis_U0_ap_idle,
        ap_ready => core_to_axis_U0_ap_ready,
        core_digest_strm_dout => core_digest_strm_dout,
        core_digest_strm_empty_n => core_digest_strm_empty_n,
        core_digest_strm_read => core_to_axis_U0_core_digest_strm_read,
        core_digest_strm_num_data_valid => core_digest_strm_num_data_valid,
        core_digest_strm_fifo_cap => core_digest_strm_fifo_cap,
        core_end_digest_strm_dout => core_end_digest_strm_dout,
        core_end_digest_strm_empty_n => core_end_digest_strm_empty_n,
        core_end_digest_strm_read => core_to_axis_U0_core_end_digest_strm_read,
        core_end_digest_strm_num_data_valid => core_end_digest_strm_num_data_valid,
        core_end_digest_strm_fifo_cap => core_end_digest_strm_fifo_cap,
        digest_strm_TDATA => core_to_axis_U0_digest_strm_TDATA,
        digest_strm_TVALID => core_to_axis_U0_digest_strm_TVALID,
        digest_strm_TREADY => digest_strm_TREADY,
        digest_strm_TKEEP => core_to_axis_U0_digest_strm_TKEEP,
        digest_strm_TSTRB => core_to_axis_U0_digest_strm_TSTRB,
        digest_strm_TLAST => core_to_axis_U0_digest_strm_TLAST,
        digest_strm_TDEST => core_to_axis_U0_digest_strm_TDEST,
        dest_id_dout => dest_id_c_dout,
        dest_id_empty_n => dest_id_c_empty_n,
        dest_id_read => core_to_axis_U0_dest_id_read,
        dest_id_num_data_valid => dest_id_c_num_data_valid,
        dest_id_fifo_cap => dest_id_c_fifo_cap);

    dest_id_c_U : component test_fifo_w2_d4_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => entry_proc_U0_dest_id_c_din,
        if_full_n => dest_id_c_full_n,
        if_write => entry_proc_U0_dest_id_c_write,
        if_dout => dest_id_c_dout,
        if_empty_n => dest_id_c_empty_n,
        if_read => core_to_axis_U0_dest_id_read,
        if_num_data_valid => dest_id_c_num_data_valid,
        if_fifo_cap => dest_id_c_fifo_cap);

    core_msg_strm_U : component test_fifo_w64_d64_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => axis_to_core_U0_core_msg_strm_din,
        if_full_n => core_msg_strm_full_n,
        if_write => axis_to_core_U0_core_msg_strm_write,
        if_dout => core_msg_strm_dout,
        if_empty_n => core_msg_strm_empty_n,
        if_read => sha512_t_64u_256u_U0_core_msg_strm_read,
        if_num_data_valid => core_msg_strm_num_data_valid,
        if_fifo_cap => core_msg_strm_fifo_cap);

    core_len_strm_U : component test_fifo_w128_d4_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => axis_to_core_U0_core_len_strm_din,
        if_full_n => core_len_strm_full_n,
        if_write => axis_to_core_U0_core_len_strm_write,
        if_dout => core_len_strm_dout,
        if_empty_n => core_len_strm_empty_n,
        if_read => sha512_t_64u_256u_U0_core_len_strm_read,
        if_num_data_valid => core_len_strm_num_data_valid,
        if_fifo_cap => core_len_strm_fifo_cap);

    core_end_len_strm_U : component test_fifo_w1_d4_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => axis_to_core_U0_core_end_len_strm_din,
        if_full_n => core_end_len_strm_full_n,
        if_write => axis_to_core_U0_core_end_len_strm_write,
        if_dout => core_end_len_strm_dout,
        if_empty_n => core_end_len_strm_empty_n,
        if_read => sha512_t_64u_256u_U0_core_end_len_strm_read,
        if_num_data_valid => core_end_len_strm_num_data_valid,
        if_fifo_cap => core_end_len_strm_fifo_cap);

    core_digest_strm_U : component test_fifo_w256_d4_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => sha512_t_64u_256u_U0_core_digest_strm_din,
        if_full_n => core_digest_strm_full_n,
        if_write => sha512_t_64u_256u_U0_core_digest_strm_write,
        if_dout => core_digest_strm_dout,
        if_empty_n => core_digest_strm_empty_n,
        if_read => core_to_axis_U0_core_digest_strm_read,
        if_num_data_valid => core_digest_strm_num_data_valid,
        if_fifo_cap => core_digest_strm_fifo_cap);

    core_end_digest_strm_U : component test_fifo_w1_d4_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => sha512_t_64u_256u_U0_core_end_digest_strm_din,
        if_full_n => core_end_digest_strm_full_n,
        if_write => sha512_t_64u_256u_U0_core_end_digest_strm_write,
        if_dout => core_end_digest_strm_dout,
        if_empty_n => core_end_digest_strm_empty_n,
        if_read => core_to_axis_U0_core_end_digest_strm_read,
        if_num_data_valid => core_end_digest_strm_num_data_valid,
        if_fifo_cap => core_end_digest_strm_fifo_cap);

    start_for_core_to_axis_U0_U : component test_start_for_core_to_axis_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_core_to_axis_U0_din,
        if_full_n => start_for_core_to_axis_U0_full_n,
        if_write => entry_proc_U0_start_write,
        if_dout => start_for_core_to_axis_U0_dout,
        if_empty_n => start_for_core_to_axis_U0_empty_n,
        if_read => core_to_axis_U0_ap_ready);

    start_for_sha512_t_64u_256u_U0_U : component test_start_for_sha512_t_64u_256u_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_sha512_t_64u_256u_U0_din,
        if_full_n => start_for_sha512_t_64u_256u_U0_full_n,
        if_write => axis_to_core_U0_start_write,
        if_dout => start_for_sha512_t_64u_256u_U0_dout,
        if_empty_n => start_for_sha512_t_64u_256u_U0_empty_n,
        if_read => sha512_t_64u_256u_U0_ap_ready);





    ap_sync_reg_axis_to_core_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_axis_to_core_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_axis_to_core_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_axis_to_core_U0_ap_ready <= ap_sync_axis_to_core_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_entry_proc_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_entry_proc_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_entry_proc_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_entry_proc_U0_ap_ready <= ap_sync_entry_proc_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;

    ap_done <= core_to_axis_U0_ap_done;
    ap_idle <= (sha512_t_64u_256u_U0_ap_idle and entry_proc_U0_ap_idle and core_to_axis_U0_ap_idle and axis_to_core_U0_ap_idle);
    ap_ready <= ap_sync_ready;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    ap_sync_axis_to_core_U0_ap_ready <= (axis_to_core_U0_ap_ready or ap_sync_reg_axis_to_core_U0_ap_ready);
    ap_sync_entry_proc_U0_ap_ready <= (entry_proc_U0_ap_ready or ap_sync_reg_entry_proc_U0_ap_ready);
    ap_sync_ready <= (ap_sync_entry_proc_U0_ap_ready and ap_sync_axis_to_core_U0_ap_ready);
    axis_to_core_U0_ap_continue <= ap_const_logic_1;
    axis_to_core_U0_ap_start <= ((ap_sync_reg_axis_to_core_U0_ap_ready xor ap_const_logic_1) and ap_start);
    core_to_axis_U0_ap_continue <= ap_const_logic_1;
    core_to_axis_U0_ap_start <= start_for_core_to_axis_U0_empty_n;
    digest_strm_TDATA <= core_to_axis_U0_digest_strm_TDATA;
    digest_strm_TDEST <= core_to_axis_U0_digest_strm_TDEST;
    digest_strm_TKEEP <= core_to_axis_U0_digest_strm_TKEEP;
    digest_strm_TLAST <= core_to_axis_U0_digest_strm_TLAST;
    digest_strm_TSTRB <= core_to_axis_U0_digest_strm_TSTRB;
    digest_strm_TVALID <= core_to_axis_U0_digest_strm_TVALID;
    entry_proc_U0_ap_continue <= ap_const_logic_1;
    entry_proc_U0_ap_start <= ((ap_sync_reg_entry_proc_U0_ap_ready xor ap_const_logic_1) and ap_start);
    msg_strm_TREADY <= axis_to_core_U0_msg_strm_TREADY;
    sha512_t_64u_256u_U0_ap_continue <= ap_const_logic_1;
    sha512_t_64u_256u_U0_ap_start <= start_for_sha512_t_64u_256u_U0_empty_n;
    start_for_core_to_axis_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_sha512_t_64u_256u_U0_din <= (0=>ap_const_logic_1, others=>'-');
end behav;
