-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity test_preProcessing_64u_Pipeline_LOOP_COPY_TAIL_AND_PAD_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    core_msg_strm_dout : IN STD_LOGIC_VECTOR (63 downto 0);
    core_msg_strm_empty_n : IN STD_LOGIC;
    core_msg_strm_read : OUT STD_LOGIC;
    core_msg_strm_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    core_msg_strm_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    shr_i2380_cast : IN STD_LOGIC_VECTOR (3 downto 0);
    len : IN STD_LOGIC_VECTOR (2 downto 0);
    b_13_out : OUT STD_LOGIC_VECTOR (63 downto 0);
    b_13_out_ap_vld : OUT STD_LOGIC;
    b_12_out : OUT STD_LOGIC_VECTOR (63 downto 0);
    b_12_out_ap_vld : OUT STD_LOGIC;
    b_11_out : OUT STD_LOGIC_VECTOR (63 downto 0);
    b_11_out_ap_vld : OUT STD_LOGIC;
    b_10_out : OUT STD_LOGIC_VECTOR (63 downto 0);
    b_10_out_ap_vld : OUT STD_LOGIC;
    b_9_out : OUT STD_LOGIC_VECTOR (63 downto 0);
    b_9_out_ap_vld : OUT STD_LOGIC;
    b_8_out : OUT STD_LOGIC_VECTOR (63 downto 0);
    b_8_out_ap_vld : OUT STD_LOGIC;
    b_7_out : OUT STD_LOGIC_VECTOR (63 downto 0);
    b_7_out_ap_vld : OUT STD_LOGIC;
    b_6_out : OUT STD_LOGIC_VECTOR (63 downto 0);
    b_6_out_ap_vld : OUT STD_LOGIC;
    b_5_out : OUT STD_LOGIC_VECTOR (63 downto 0);
    b_5_out_ap_vld : OUT STD_LOGIC;
    b_4_out : OUT STD_LOGIC_VECTOR (63 downto 0);
    b_4_out_ap_vld : OUT STD_LOGIC;
    b_3_out : OUT STD_LOGIC_VECTOR (63 downto 0);
    b_3_out_ap_vld : OUT STD_LOGIC;
    b_2_out : OUT STD_LOGIC_VECTOR (63 downto 0);
    b_2_out_ap_vld : OUT STD_LOGIC;
    b_1_out : OUT STD_LOGIC_VECTOR (63 downto 0);
    b_1_out_ap_vld : OUT STD_LOGIC;
    b_out : OUT STD_LOGIC_VECTOR (63 downto 0);
    b_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of test_preProcessing_64u_Pipeline_LOOP_COPY_TAIL_AND_PAD_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv64_8000000000000000 : STD_LOGIC_VECTOR (63 downto 0) := "1000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv4_B : STD_LOGIC_VECTOR (3 downto 0) := "1011";
    constant ap_const_lv4_C : STD_LOGIC_VECTOR (3 downto 0) := "1100";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv4_E : STD_LOGIC_VECTOR (3 downto 0) := "1110";
    constant ap_const_lv4_D : STD_LOGIC_VECTOR (3 downto 0) := "1101";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_37 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110111";
    constant ap_const_lv16_8000 : STD_LOGIC_VECTOR (15 downto 0) := "1000000000000000";
    constant ap_const_lv24_800000 : STD_LOGIC_VECTOR (23 downto 0) := "100000000000000000000000";
    constant ap_const_lv32_80000000 : STD_LOGIC_VECTOR (31 downto 0) := "10000000000000000000000000000000";
    constant ap_const_lv40_8000000000 : STD_LOGIC_VECTOR (39 downto 0) := "1000000000000000000000000000000000000000";
    constant ap_const_lv48_800000000000 : STD_LOGIC_VECTOR (47 downto 0) := "100000000000000000000000000000000000000000000000";
    constant ap_const_lv56_80000000000000 : STD_LOGIC_VECTOR (55 downto 0) := "10000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv8_80 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv32_38 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal icmp_ln155_reg_1579 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln164_reg_1583 : STD_LOGIC_VECTOR (0 downto 0);
    signal len_read_reg_1568 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_predicate_op63_read_state2 : BOOLEAN;
    signal ap_predicate_op99_read_state2 : BOOLEAN;
    signal ap_predicate_op134_read_state2 : BOOLEAN;
    signal ap_predicate_op168_read_state2 : BOOLEAN;
    signal ap_predicate_op201_read_state2 : BOOLEAN;
    signal ap_predicate_op233_read_state2 : BOOLEAN;
    signal ap_predicate_op292_read_state2 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln153_fu_412_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal core_msg_strm_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal i_1_reg_1572 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln155_fu_424_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln164_fu_430_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_fu_168 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal add_ln153_fu_418_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_1 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal b_fu_172 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal b_20_fu_445_p8 : STD_LOGIC_VECTOR (63 downto 0);
    signal b_19_fu_537_p7 : STD_LOGIC_VECTOR (63 downto 0);
    signal b_18_fu_627_p6 : STD_LOGIC_VECTOR (63 downto 0);
    signal b_17_fu_715_p5 : STD_LOGIC_VECTOR (63 downto 0);
    signal b_16_fu_801_p4 : STD_LOGIC_VECTOR (63 downto 0);
    signal b_15_fu_885_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal b_21_fu_1037_p9 : STD_LOGIC_VECTOR (63 downto 0);
    signal l_24_fu_1206_p9 : STD_LOGIC_VECTOR (63 downto 0);
    signal b_1_fu_176 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal b_2_fu_180 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal b_3_fu_184 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal b_4_fu_188 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal b_5_fu_192 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal b_6_fu_196 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal b_7_fu_200 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal b_8_fu_204 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal b_9_fu_208 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal b_10_fu_212 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal b_11_fu_216 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal b_12_fu_220 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal b_13_fu_224 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal ap_block_pp0_stage0_01001_grp1 : BOOLEAN;
    signal trunc_ln214_fu_441_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_344_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_354_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_364_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_384_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_374_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln206_fu_533_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln198_fu_623_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln191_fu_711_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln184_fu_797_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln177_fu_881_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln223_fu_1033_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_394_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_fu_1192_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_s_fu_1196_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_condition_45 : BOOLEAN;
    signal ap_condition_51 : BOOLEAN;
    signal ap_condition_58 : BOOLEAN;
    signal ap_condition_65 : BOOLEAN;
    signal ap_condition_72 : BOOLEAN;
    signal ap_condition_79 : BOOLEAN;
    signal ap_condition_229 : BOOLEAN;
    signal ap_condition_86 : BOOLEAN;
    signal ap_condition_999 : BOOLEAN;
    signal ap_condition_1026 : BOOLEAN;
    signal ap_condition_1029 : BOOLEAN;
    signal ap_condition_677 : BOOLEAN;
    signal ap_condition_685 : BOOLEAN;
    signal ap_condition_692 : BOOLEAN;
    signal ap_condition_699 : BOOLEAN;
    signal ap_condition_706 : BOOLEAN;
    signal ap_condition_713 : BOOLEAN;
    signal ap_condition_720 : BOOLEAN;
    signal ap_condition_727 : BOOLEAN;
    signal ap_condition_736 : BOOLEAN;
    signal ap_condition_743 : BOOLEAN;
    signal ap_condition_206 : BOOLEAN;
    signal ap_condition_1054 : BOOLEAN;
    signal ap_condition_1057 : BOOLEAN;
    signal ap_condition_1060 : BOOLEAN;
    signal ap_condition_1063 : BOOLEAN;
    signal ap_condition_1066 : BOOLEAN;
    signal ap_condition_1069 : BOOLEAN;
    signal ap_condition_1072 : BOOLEAN;
    signal ap_condition_1075 : BOOLEAN;
    signal ap_condition_1078 : BOOLEAN;
    signal ap_condition_1081 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component test_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component test_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    b_10_fu_212_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_999)) then
                if ((icmp_ln155_reg_1579 = ap_const_lv1_1)) then 
                    b_10_fu_212 <= l_24_fu_1206_p9;
                elsif (((icmp_ln164_reg_1583 = ap_const_lv1_1) and (icmp_ln155_reg_1579 = ap_const_lv1_0))) then 
                    b_10_fu_212 <= ap_const_lv64_0;
                elsif ((ap_const_boolean_1 = ap_condition_86)) then 
                    b_10_fu_212 <= b_21_fu_1037_p9;
                elsif ((ap_const_boolean_1 = ap_condition_229)) then 
                    b_10_fu_212 <= ap_const_lv64_8000000000000000;
                elsif ((ap_const_boolean_1 = ap_condition_79)) then 
                    b_10_fu_212 <= b_15_fu_885_p3;
                elsif ((ap_const_boolean_1 = ap_condition_72)) then 
                    b_10_fu_212 <= b_16_fu_801_p4;
                elsif ((ap_const_boolean_1 = ap_condition_65)) then 
                    b_10_fu_212 <= b_17_fu_715_p5;
                elsif ((ap_const_boolean_1 = ap_condition_58)) then 
                    b_10_fu_212 <= b_18_fu_627_p6;
                elsif ((ap_const_boolean_1 = ap_condition_51)) then 
                    b_10_fu_212 <= b_19_fu_537_p7;
                elsif ((ap_const_boolean_1 = ap_condition_45)) then 
                    b_10_fu_212 <= b_20_fu_445_p8;
                end if;
            end if; 
        end if;
    end process;

    b_11_fu_216_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_1026)) then
                if ((icmp_ln155_reg_1579 = ap_const_lv1_1)) then 
                    b_11_fu_216 <= l_24_fu_1206_p9;
                elsif (((icmp_ln164_reg_1583 = ap_const_lv1_1) and (icmp_ln155_reg_1579 = ap_const_lv1_0))) then 
                    b_11_fu_216 <= ap_const_lv64_0;
                elsif ((ap_const_boolean_1 = ap_condition_86)) then 
                    b_11_fu_216 <= b_21_fu_1037_p9;
                elsif ((ap_const_boolean_1 = ap_condition_229)) then 
                    b_11_fu_216 <= ap_const_lv64_8000000000000000;
                elsif ((ap_const_boolean_1 = ap_condition_79)) then 
                    b_11_fu_216 <= b_15_fu_885_p3;
                elsif ((ap_const_boolean_1 = ap_condition_72)) then 
                    b_11_fu_216 <= b_16_fu_801_p4;
                elsif ((ap_const_boolean_1 = ap_condition_65)) then 
                    b_11_fu_216 <= b_17_fu_715_p5;
                elsif ((ap_const_boolean_1 = ap_condition_58)) then 
                    b_11_fu_216 <= b_18_fu_627_p6;
                elsif ((ap_const_boolean_1 = ap_condition_51)) then 
                    b_11_fu_216 <= b_19_fu_537_p7;
                elsif ((ap_const_boolean_1 = ap_condition_45)) then 
                    b_11_fu_216 <= b_20_fu_445_p8;
                end if;
            end if; 
        end if;
    end process;

    b_12_fu_220_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_1029)) then
                if ((icmp_ln155_reg_1579 = ap_const_lv1_1)) then 
                    b_12_fu_220 <= l_24_fu_1206_p9;
                elsif (((icmp_ln164_reg_1583 = ap_const_lv1_1) and (icmp_ln155_reg_1579 = ap_const_lv1_0))) then 
                    b_12_fu_220 <= ap_const_lv64_0;
                elsif ((ap_const_boolean_1 = ap_condition_86)) then 
                    b_12_fu_220 <= b_21_fu_1037_p9;
                elsif ((ap_const_boolean_1 = ap_condition_229)) then 
                    b_12_fu_220 <= ap_const_lv64_8000000000000000;
                elsif ((ap_const_boolean_1 = ap_condition_79)) then 
                    b_12_fu_220 <= b_15_fu_885_p3;
                elsif ((ap_const_boolean_1 = ap_condition_72)) then 
                    b_12_fu_220 <= b_16_fu_801_p4;
                elsif ((ap_const_boolean_1 = ap_condition_65)) then 
                    b_12_fu_220 <= b_17_fu_715_p5;
                elsif ((ap_const_boolean_1 = ap_condition_58)) then 
                    b_12_fu_220 <= b_18_fu_627_p6;
                elsif ((ap_const_boolean_1 = ap_condition_51)) then 
                    b_12_fu_220 <= b_19_fu_537_p7;
                elsif ((ap_const_boolean_1 = ap_condition_45)) then 
                    b_12_fu_220 <= b_20_fu_445_p8;
                end if;
            end if; 
        end if;
    end process;

    b_13_fu_224_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_206)) then
                if ((ap_const_boolean_1 = ap_condition_743)) then 
                    b_13_fu_224 <= l_24_fu_1206_p9;
                elsif ((ap_const_boolean_1 = ap_condition_736)) then 
                    b_13_fu_224 <= ap_const_lv64_0;
                elsif ((ap_const_boolean_1 = ap_condition_727)) then 
                    b_13_fu_224 <= b_21_fu_1037_p9;
                elsif ((ap_const_boolean_1 = ap_condition_720)) then 
                    b_13_fu_224 <= ap_const_lv64_8000000000000000;
                elsif ((ap_const_boolean_1 = ap_condition_713)) then 
                    b_13_fu_224 <= b_15_fu_885_p3;
                elsif ((ap_const_boolean_1 = ap_condition_706)) then 
                    b_13_fu_224 <= b_16_fu_801_p4;
                elsif ((ap_const_boolean_1 = ap_condition_699)) then 
                    b_13_fu_224 <= b_17_fu_715_p5;
                elsif ((ap_const_boolean_1 = ap_condition_692)) then 
                    b_13_fu_224 <= b_18_fu_627_p6;
                elsif ((ap_const_boolean_1 = ap_condition_685)) then 
                    b_13_fu_224 <= b_19_fu_537_p7;
                elsif ((ap_const_boolean_1 = ap_condition_677)) then 
                    b_13_fu_224 <= b_20_fu_445_p8;
                end if;
            end if; 
        end if;
    end process;

    b_1_fu_176_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_1054)) then
                if ((icmp_ln155_reg_1579 = ap_const_lv1_1)) then 
                    b_1_fu_176 <= l_24_fu_1206_p9;
                elsif (((icmp_ln164_reg_1583 = ap_const_lv1_1) and (icmp_ln155_reg_1579 = ap_const_lv1_0))) then 
                    b_1_fu_176 <= ap_const_lv64_0;
                elsif ((ap_const_boolean_1 = ap_condition_86)) then 
                    b_1_fu_176 <= b_21_fu_1037_p9;
                elsif ((ap_const_boolean_1 = ap_condition_229)) then 
                    b_1_fu_176 <= ap_const_lv64_8000000000000000;
                elsif ((ap_const_boolean_1 = ap_condition_79)) then 
                    b_1_fu_176 <= b_15_fu_885_p3;
                elsif ((ap_const_boolean_1 = ap_condition_72)) then 
                    b_1_fu_176 <= b_16_fu_801_p4;
                elsif ((ap_const_boolean_1 = ap_condition_65)) then 
                    b_1_fu_176 <= b_17_fu_715_p5;
                elsif ((ap_const_boolean_1 = ap_condition_58)) then 
                    b_1_fu_176 <= b_18_fu_627_p6;
                elsif ((ap_const_boolean_1 = ap_condition_51)) then 
                    b_1_fu_176 <= b_19_fu_537_p7;
                elsif ((ap_const_boolean_1 = ap_condition_45)) then 
                    b_1_fu_176 <= b_20_fu_445_p8;
                end if;
            end if; 
        end if;
    end process;

    b_2_fu_180_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_1057)) then
                if ((icmp_ln155_reg_1579 = ap_const_lv1_1)) then 
                    b_2_fu_180 <= l_24_fu_1206_p9;
                elsif (((icmp_ln164_reg_1583 = ap_const_lv1_1) and (icmp_ln155_reg_1579 = ap_const_lv1_0))) then 
                    b_2_fu_180 <= ap_const_lv64_0;
                elsif ((ap_const_boolean_1 = ap_condition_86)) then 
                    b_2_fu_180 <= b_21_fu_1037_p9;
                elsif ((ap_const_boolean_1 = ap_condition_229)) then 
                    b_2_fu_180 <= ap_const_lv64_8000000000000000;
                elsif ((ap_const_boolean_1 = ap_condition_79)) then 
                    b_2_fu_180 <= b_15_fu_885_p3;
                elsif ((ap_const_boolean_1 = ap_condition_72)) then 
                    b_2_fu_180 <= b_16_fu_801_p4;
                elsif ((ap_const_boolean_1 = ap_condition_65)) then 
                    b_2_fu_180 <= b_17_fu_715_p5;
                elsif ((ap_const_boolean_1 = ap_condition_58)) then 
                    b_2_fu_180 <= b_18_fu_627_p6;
                elsif ((ap_const_boolean_1 = ap_condition_51)) then 
                    b_2_fu_180 <= b_19_fu_537_p7;
                elsif ((ap_const_boolean_1 = ap_condition_45)) then 
                    b_2_fu_180 <= b_20_fu_445_p8;
                end if;
            end if; 
        end if;
    end process;

    b_3_fu_184_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_1060)) then
                if ((icmp_ln155_reg_1579 = ap_const_lv1_1)) then 
                    b_3_fu_184 <= l_24_fu_1206_p9;
                elsif (((icmp_ln164_reg_1583 = ap_const_lv1_1) and (icmp_ln155_reg_1579 = ap_const_lv1_0))) then 
                    b_3_fu_184 <= ap_const_lv64_0;
                elsif ((ap_const_boolean_1 = ap_condition_86)) then 
                    b_3_fu_184 <= b_21_fu_1037_p9;
                elsif ((ap_const_boolean_1 = ap_condition_229)) then 
                    b_3_fu_184 <= ap_const_lv64_8000000000000000;
                elsif ((ap_const_boolean_1 = ap_condition_79)) then 
                    b_3_fu_184 <= b_15_fu_885_p3;
                elsif ((ap_const_boolean_1 = ap_condition_72)) then 
                    b_3_fu_184 <= b_16_fu_801_p4;
                elsif ((ap_const_boolean_1 = ap_condition_65)) then 
                    b_3_fu_184 <= b_17_fu_715_p5;
                elsif ((ap_const_boolean_1 = ap_condition_58)) then 
                    b_3_fu_184 <= b_18_fu_627_p6;
                elsif ((ap_const_boolean_1 = ap_condition_51)) then 
                    b_3_fu_184 <= b_19_fu_537_p7;
                elsif ((ap_const_boolean_1 = ap_condition_45)) then 
                    b_3_fu_184 <= b_20_fu_445_p8;
                end if;
            end if; 
        end if;
    end process;

    b_4_fu_188_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_1063)) then
                if ((icmp_ln155_reg_1579 = ap_const_lv1_1)) then 
                    b_4_fu_188 <= l_24_fu_1206_p9;
                elsif (((icmp_ln164_reg_1583 = ap_const_lv1_1) and (icmp_ln155_reg_1579 = ap_const_lv1_0))) then 
                    b_4_fu_188 <= ap_const_lv64_0;
                elsif ((ap_const_boolean_1 = ap_condition_86)) then 
                    b_4_fu_188 <= b_21_fu_1037_p9;
                elsif ((ap_const_boolean_1 = ap_condition_229)) then 
                    b_4_fu_188 <= ap_const_lv64_8000000000000000;
                elsif ((ap_const_boolean_1 = ap_condition_79)) then 
                    b_4_fu_188 <= b_15_fu_885_p3;
                elsif ((ap_const_boolean_1 = ap_condition_72)) then 
                    b_4_fu_188 <= b_16_fu_801_p4;
                elsif ((ap_const_boolean_1 = ap_condition_65)) then 
                    b_4_fu_188 <= b_17_fu_715_p5;
                elsif ((ap_const_boolean_1 = ap_condition_58)) then 
                    b_4_fu_188 <= b_18_fu_627_p6;
                elsif ((ap_const_boolean_1 = ap_condition_51)) then 
                    b_4_fu_188 <= b_19_fu_537_p7;
                elsif ((ap_const_boolean_1 = ap_condition_45)) then 
                    b_4_fu_188 <= b_20_fu_445_p8;
                end if;
            end if; 
        end if;
    end process;

    b_5_fu_192_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_1066)) then
                if ((icmp_ln155_reg_1579 = ap_const_lv1_1)) then 
                    b_5_fu_192 <= l_24_fu_1206_p9;
                elsif (((icmp_ln164_reg_1583 = ap_const_lv1_1) and (icmp_ln155_reg_1579 = ap_const_lv1_0))) then 
                    b_5_fu_192 <= ap_const_lv64_0;
                elsif ((ap_const_boolean_1 = ap_condition_86)) then 
                    b_5_fu_192 <= b_21_fu_1037_p9;
                elsif ((ap_const_boolean_1 = ap_condition_229)) then 
                    b_5_fu_192 <= ap_const_lv64_8000000000000000;
                elsif ((ap_const_boolean_1 = ap_condition_79)) then 
                    b_5_fu_192 <= b_15_fu_885_p3;
                elsif ((ap_const_boolean_1 = ap_condition_72)) then 
                    b_5_fu_192 <= b_16_fu_801_p4;
                elsif ((ap_const_boolean_1 = ap_condition_65)) then 
                    b_5_fu_192 <= b_17_fu_715_p5;
                elsif ((ap_const_boolean_1 = ap_condition_58)) then 
                    b_5_fu_192 <= b_18_fu_627_p6;
                elsif ((ap_const_boolean_1 = ap_condition_51)) then 
                    b_5_fu_192 <= b_19_fu_537_p7;
                elsif ((ap_const_boolean_1 = ap_condition_45)) then 
                    b_5_fu_192 <= b_20_fu_445_p8;
                end if;
            end if; 
        end if;
    end process;

    b_6_fu_196_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_1069)) then
                if ((icmp_ln155_reg_1579 = ap_const_lv1_1)) then 
                    b_6_fu_196 <= l_24_fu_1206_p9;
                elsif (((icmp_ln164_reg_1583 = ap_const_lv1_1) and (icmp_ln155_reg_1579 = ap_const_lv1_0))) then 
                    b_6_fu_196 <= ap_const_lv64_0;
                elsif ((ap_const_boolean_1 = ap_condition_86)) then 
                    b_6_fu_196 <= b_21_fu_1037_p9;
                elsif ((ap_const_boolean_1 = ap_condition_229)) then 
                    b_6_fu_196 <= ap_const_lv64_8000000000000000;
                elsif ((ap_const_boolean_1 = ap_condition_79)) then 
                    b_6_fu_196 <= b_15_fu_885_p3;
                elsif ((ap_const_boolean_1 = ap_condition_72)) then 
                    b_6_fu_196 <= b_16_fu_801_p4;
                elsif ((ap_const_boolean_1 = ap_condition_65)) then 
                    b_6_fu_196 <= b_17_fu_715_p5;
                elsif ((ap_const_boolean_1 = ap_condition_58)) then 
                    b_6_fu_196 <= b_18_fu_627_p6;
                elsif ((ap_const_boolean_1 = ap_condition_51)) then 
                    b_6_fu_196 <= b_19_fu_537_p7;
                elsif ((ap_const_boolean_1 = ap_condition_45)) then 
                    b_6_fu_196 <= b_20_fu_445_p8;
                end if;
            end if; 
        end if;
    end process;

    b_7_fu_200_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_1072)) then
                if ((icmp_ln155_reg_1579 = ap_const_lv1_1)) then 
                    b_7_fu_200 <= l_24_fu_1206_p9;
                elsif (((icmp_ln164_reg_1583 = ap_const_lv1_1) and (icmp_ln155_reg_1579 = ap_const_lv1_0))) then 
                    b_7_fu_200 <= ap_const_lv64_0;
                elsif ((ap_const_boolean_1 = ap_condition_86)) then 
                    b_7_fu_200 <= b_21_fu_1037_p9;
                elsif ((ap_const_boolean_1 = ap_condition_229)) then 
                    b_7_fu_200 <= ap_const_lv64_8000000000000000;
                elsif ((ap_const_boolean_1 = ap_condition_79)) then 
                    b_7_fu_200 <= b_15_fu_885_p3;
                elsif ((ap_const_boolean_1 = ap_condition_72)) then 
                    b_7_fu_200 <= b_16_fu_801_p4;
                elsif ((ap_const_boolean_1 = ap_condition_65)) then 
                    b_7_fu_200 <= b_17_fu_715_p5;
                elsif ((ap_const_boolean_1 = ap_condition_58)) then 
                    b_7_fu_200 <= b_18_fu_627_p6;
                elsif ((ap_const_boolean_1 = ap_condition_51)) then 
                    b_7_fu_200 <= b_19_fu_537_p7;
                elsif ((ap_const_boolean_1 = ap_condition_45)) then 
                    b_7_fu_200 <= b_20_fu_445_p8;
                end if;
            end if; 
        end if;
    end process;

    b_8_fu_204_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_1075)) then
                if ((icmp_ln155_reg_1579 = ap_const_lv1_1)) then 
                    b_8_fu_204 <= l_24_fu_1206_p9;
                elsif (((icmp_ln164_reg_1583 = ap_const_lv1_1) and (icmp_ln155_reg_1579 = ap_const_lv1_0))) then 
                    b_8_fu_204 <= ap_const_lv64_0;
                elsif ((ap_const_boolean_1 = ap_condition_86)) then 
                    b_8_fu_204 <= b_21_fu_1037_p9;
                elsif ((ap_const_boolean_1 = ap_condition_229)) then 
                    b_8_fu_204 <= ap_const_lv64_8000000000000000;
                elsif ((ap_const_boolean_1 = ap_condition_79)) then 
                    b_8_fu_204 <= b_15_fu_885_p3;
                elsif ((ap_const_boolean_1 = ap_condition_72)) then 
                    b_8_fu_204 <= b_16_fu_801_p4;
                elsif ((ap_const_boolean_1 = ap_condition_65)) then 
                    b_8_fu_204 <= b_17_fu_715_p5;
                elsif ((ap_const_boolean_1 = ap_condition_58)) then 
                    b_8_fu_204 <= b_18_fu_627_p6;
                elsif ((ap_const_boolean_1 = ap_condition_51)) then 
                    b_8_fu_204 <= b_19_fu_537_p7;
                elsif ((ap_const_boolean_1 = ap_condition_45)) then 
                    b_8_fu_204 <= b_20_fu_445_p8;
                end if;
            end if; 
        end if;
    end process;

    b_9_fu_208_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_1078)) then
                if ((icmp_ln155_reg_1579 = ap_const_lv1_1)) then 
                    b_9_fu_208 <= l_24_fu_1206_p9;
                elsif (((icmp_ln164_reg_1583 = ap_const_lv1_1) and (icmp_ln155_reg_1579 = ap_const_lv1_0))) then 
                    b_9_fu_208 <= ap_const_lv64_0;
                elsif ((ap_const_boolean_1 = ap_condition_86)) then 
                    b_9_fu_208 <= b_21_fu_1037_p9;
                elsif ((ap_const_boolean_1 = ap_condition_229)) then 
                    b_9_fu_208 <= ap_const_lv64_8000000000000000;
                elsif ((ap_const_boolean_1 = ap_condition_79)) then 
                    b_9_fu_208 <= b_15_fu_885_p3;
                elsif ((ap_const_boolean_1 = ap_condition_72)) then 
                    b_9_fu_208 <= b_16_fu_801_p4;
                elsif ((ap_const_boolean_1 = ap_condition_65)) then 
                    b_9_fu_208 <= b_17_fu_715_p5;
                elsif ((ap_const_boolean_1 = ap_condition_58)) then 
                    b_9_fu_208 <= b_18_fu_627_p6;
                elsif ((ap_const_boolean_1 = ap_condition_51)) then 
                    b_9_fu_208 <= b_19_fu_537_p7;
                elsif ((ap_const_boolean_1 = ap_condition_45)) then 
                    b_9_fu_208 <= b_20_fu_445_p8;
                end if;
            end if; 
        end if;
    end process;

    b_fu_172_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_1081)) then
                if ((icmp_ln155_reg_1579 = ap_const_lv1_1)) then 
                    b_fu_172 <= l_24_fu_1206_p9;
                elsif ((ap_const_boolean_1 = ap_condition_86)) then 
                    b_fu_172 <= b_21_fu_1037_p9;
                elsif ((ap_const_boolean_1 = ap_condition_229)) then 
                    b_fu_172 <= ap_const_lv64_8000000000000000;
                elsif ((ap_const_boolean_1 = ap_condition_79)) then 
                    b_fu_172 <= b_15_fu_885_p3;
                elsif ((ap_const_boolean_1 = ap_condition_72)) then 
                    b_fu_172 <= b_16_fu_801_p4;
                elsif ((ap_const_boolean_1 = ap_condition_65)) then 
                    b_fu_172 <= b_17_fu_715_p5;
                elsif ((ap_const_boolean_1 = ap_condition_58)) then 
                    b_fu_172 <= b_18_fu_627_p6;
                elsif ((ap_const_boolean_1 = ap_condition_51)) then 
                    b_fu_172 <= b_19_fu_537_p7;
                elsif ((ap_const_boolean_1 = ap_condition_45)) then 
                    b_fu_172 <= b_20_fu_445_p8;
                end if;
            end if; 
        end if;
    end process;

    i_fu_168_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln153_fu_412_p2 = ap_const_lv1_0))) then 
                    i_fu_168 <= add_ln153_fu_418_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_168 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                i_1_reg_1572 <= ap_sig_allocacmp_i_1;
                icmp_ln155_reg_1579 <= icmp_ln155_fu_424_p2;
                icmp_ln164_reg_1583 <= icmp_ln164_fu_430_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln153_fu_418_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_1) + unsigned(ap_const_lv4_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp1)
    begin
                ap_block_pp0_stage0_01001_grp1 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp1));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp1)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp1));
    end process;


    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp1)
    begin
                ap_block_pp0_stage0_11001_grp1 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp1));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp1)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp1));
    end process;


    ap_block_state2_pp0_stage0_iter1_grp1_assign_proc : process(core_msg_strm_empty_n, icmp_ln155_reg_1579, ap_predicate_op63_read_state2, ap_predicate_op99_read_state2, ap_predicate_op134_read_state2, ap_predicate_op168_read_state2, ap_predicate_op201_read_state2, ap_predicate_op233_read_state2, ap_predicate_op292_read_state2)
    begin
                ap_block_state2_pp0_stage0_iter1_grp1 <= (((icmp_ln155_reg_1579 = ap_const_lv1_1) and (core_msg_strm_empty_n = ap_const_logic_0)) or ((ap_predicate_op292_read_state2 = ap_const_boolean_1) and (core_msg_strm_empty_n = ap_const_logic_0)) or ((ap_predicate_op233_read_state2 = ap_const_boolean_1) and (core_msg_strm_empty_n = ap_const_logic_0)) or ((ap_predicate_op201_read_state2 = ap_const_boolean_1) and (core_msg_strm_empty_n = ap_const_logic_0)) or ((ap_predicate_op168_read_state2 = ap_const_boolean_1) and (core_msg_strm_empty_n = ap_const_logic_0)) or ((ap_predicate_op134_read_state2 = ap_const_boolean_1) and (core_msg_strm_empty_n = ap_const_logic_0)) or ((ap_predicate_op99_read_state2 = ap_const_boolean_1) and (core_msg_strm_empty_n = ap_const_logic_0)) or ((ap_predicate_op63_read_state2 = ap_const_boolean_1) and (core_msg_strm_empty_n = ap_const_logic_0)));
    end process;


    ap_condition_1026_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1, i_1_reg_1572)
    begin
                ap_condition_1026 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (i_1_reg_1572 = ap_const_lv4_B) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1));
    end process;


    ap_condition_1029_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1, i_1_reg_1572)
    begin
                ap_condition_1029 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (i_1_reg_1572 = ap_const_lv4_C) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1));
    end process;


    ap_condition_1054_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1, i_1_reg_1572)
    begin
                ap_condition_1054 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (i_1_reg_1572 = ap_const_lv4_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1));
    end process;


    ap_condition_1057_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1, i_1_reg_1572)
    begin
                ap_condition_1057 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (i_1_reg_1572 = ap_const_lv4_2) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1));
    end process;


    ap_condition_1060_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1, i_1_reg_1572)
    begin
                ap_condition_1060 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (i_1_reg_1572 = ap_const_lv4_3) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1));
    end process;


    ap_condition_1063_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1, i_1_reg_1572)
    begin
                ap_condition_1063 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (i_1_reg_1572 = ap_const_lv4_4) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1));
    end process;


    ap_condition_1066_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1, i_1_reg_1572)
    begin
                ap_condition_1066 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (i_1_reg_1572 = ap_const_lv4_5) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1));
    end process;


    ap_condition_1069_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1, i_1_reg_1572)
    begin
                ap_condition_1069 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (i_1_reg_1572 = ap_const_lv4_6) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1));
    end process;


    ap_condition_1072_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1, i_1_reg_1572)
    begin
                ap_condition_1072 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (i_1_reg_1572 = ap_const_lv4_7) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1));
    end process;


    ap_condition_1075_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1, i_1_reg_1572)
    begin
                ap_condition_1075 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (i_1_reg_1572 = ap_const_lv4_8) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1));
    end process;


    ap_condition_1078_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1, i_1_reg_1572)
    begin
                ap_condition_1078 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (i_1_reg_1572 = ap_const_lv4_9) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1));
    end process;


    ap_condition_1081_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1, i_1_reg_1572)
    begin
                ap_condition_1081 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (i_1_reg_1572 = ap_const_lv4_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1));
    end process;


    ap_condition_206_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1)
    begin
                ap_condition_206 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1));
    end process;


    ap_condition_229_assign_proc : process(icmp_ln155_reg_1579, icmp_ln164_reg_1583, len_read_reg_1568)
    begin
                ap_condition_229 <= ((len_read_reg_1568 = ap_const_lv3_0) and (icmp_ln164_reg_1583 = ap_const_lv1_0) and (icmp_ln155_reg_1579 = ap_const_lv1_0));
    end process;


    ap_condition_45_assign_proc : process(icmp_ln155_reg_1579, icmp_ln164_reg_1583, len)
    begin
                ap_condition_45 <= ((len = ap_const_lv3_6) and (icmp_ln164_reg_1583 = ap_const_lv1_0) and (icmp_ln155_reg_1579 = ap_const_lv1_0));
    end process;


    ap_condition_51_assign_proc : process(icmp_ln155_reg_1579, icmp_ln164_reg_1583, len)
    begin
                ap_condition_51 <= ((len = ap_const_lv3_5) and (icmp_ln164_reg_1583 = ap_const_lv1_0) and (icmp_ln155_reg_1579 = ap_const_lv1_0));
    end process;


    ap_condition_58_assign_proc : process(icmp_ln155_reg_1579, icmp_ln164_reg_1583, len)
    begin
                ap_condition_58 <= ((len = ap_const_lv3_4) and (icmp_ln164_reg_1583 = ap_const_lv1_0) and (icmp_ln155_reg_1579 = ap_const_lv1_0));
    end process;


    ap_condition_65_assign_proc : process(icmp_ln155_reg_1579, icmp_ln164_reg_1583, len)
    begin
                ap_condition_65 <= ((len = ap_const_lv3_3) and (icmp_ln164_reg_1583 = ap_const_lv1_0) and (icmp_ln155_reg_1579 = ap_const_lv1_0));
    end process;


    ap_condition_677_assign_proc : process(icmp_ln155_reg_1579, icmp_ln164_reg_1583, len, i_1_reg_1572)
    begin
                ap_condition_677 <= ((((len = ap_const_lv3_6) and (icmp_ln164_reg_1583 = ap_const_lv1_0) and (icmp_ln155_reg_1579 = ap_const_lv1_0) and (i_1_reg_1572 = ap_const_lv4_E)) or ((len = ap_const_lv3_6) and (icmp_ln164_reg_1583 = ap_const_lv1_0) and (icmp_ln155_reg_1579 = ap_const_lv1_0) and (i_1_reg_1572 = ap_const_lv4_F))) or ((len = ap_const_lv3_6) and (icmp_ln164_reg_1583 = ap_const_lv1_0) and (icmp_ln155_reg_1579 = ap_const_lv1_0) and (i_1_reg_1572 = ap_const_lv4_D)));
    end process;


    ap_condition_685_assign_proc : process(icmp_ln155_reg_1579, icmp_ln164_reg_1583, len, i_1_reg_1572)
    begin
                ap_condition_685 <= ((((len = ap_const_lv3_5) and (icmp_ln164_reg_1583 = ap_const_lv1_0) and (icmp_ln155_reg_1579 = ap_const_lv1_0) and (i_1_reg_1572 = ap_const_lv4_E)) or ((len = ap_const_lv3_5) and (icmp_ln164_reg_1583 = ap_const_lv1_0) and (icmp_ln155_reg_1579 = ap_const_lv1_0) and (i_1_reg_1572 = ap_const_lv4_F))) or ((len = ap_const_lv3_5) and (icmp_ln164_reg_1583 = ap_const_lv1_0) and (icmp_ln155_reg_1579 = ap_const_lv1_0) and (i_1_reg_1572 = ap_const_lv4_D)));
    end process;


    ap_condition_692_assign_proc : process(icmp_ln155_reg_1579, icmp_ln164_reg_1583, len, i_1_reg_1572)
    begin
                ap_condition_692 <= ((((len = ap_const_lv3_4) and (icmp_ln164_reg_1583 = ap_const_lv1_0) and (icmp_ln155_reg_1579 = ap_const_lv1_0) and (i_1_reg_1572 = ap_const_lv4_E)) or ((len = ap_const_lv3_4) and (icmp_ln164_reg_1583 = ap_const_lv1_0) and (icmp_ln155_reg_1579 = ap_const_lv1_0) and (i_1_reg_1572 = ap_const_lv4_F))) or ((len = ap_const_lv3_4) and (icmp_ln164_reg_1583 = ap_const_lv1_0) and (icmp_ln155_reg_1579 = ap_const_lv1_0) and (i_1_reg_1572 = ap_const_lv4_D)));
    end process;


    ap_condition_699_assign_proc : process(icmp_ln155_reg_1579, icmp_ln164_reg_1583, len, i_1_reg_1572)
    begin
                ap_condition_699 <= ((((len = ap_const_lv3_3) and (icmp_ln164_reg_1583 = ap_const_lv1_0) and (icmp_ln155_reg_1579 = ap_const_lv1_0) and (i_1_reg_1572 = ap_const_lv4_E)) or ((len = ap_const_lv3_3) and (icmp_ln164_reg_1583 = ap_const_lv1_0) and (icmp_ln155_reg_1579 = ap_const_lv1_0) and (i_1_reg_1572 = ap_const_lv4_F))) or ((len = ap_const_lv3_3) and (icmp_ln164_reg_1583 = ap_const_lv1_0) and (icmp_ln155_reg_1579 = ap_const_lv1_0) and (i_1_reg_1572 = ap_const_lv4_D)));
    end process;


    ap_condition_706_assign_proc : process(icmp_ln155_reg_1579, icmp_ln164_reg_1583, len, i_1_reg_1572)
    begin
                ap_condition_706 <= ((((len = ap_const_lv3_2) and (icmp_ln164_reg_1583 = ap_const_lv1_0) and (icmp_ln155_reg_1579 = ap_const_lv1_0) and (i_1_reg_1572 = ap_const_lv4_E)) or ((len = ap_const_lv3_2) and (icmp_ln164_reg_1583 = ap_const_lv1_0) and (icmp_ln155_reg_1579 = ap_const_lv1_0) and (i_1_reg_1572 = ap_const_lv4_F))) or ((len = ap_const_lv3_2) and (icmp_ln164_reg_1583 = ap_const_lv1_0) and (icmp_ln155_reg_1579 = ap_const_lv1_0) and (i_1_reg_1572 = ap_const_lv4_D)));
    end process;


    ap_condition_713_assign_proc : process(icmp_ln155_reg_1579, icmp_ln164_reg_1583, len, i_1_reg_1572)
    begin
                ap_condition_713 <= ((((len = ap_const_lv3_1) and (icmp_ln164_reg_1583 = ap_const_lv1_0) and (icmp_ln155_reg_1579 = ap_const_lv1_0) and (i_1_reg_1572 = ap_const_lv4_E)) or ((len = ap_const_lv3_1) and (icmp_ln164_reg_1583 = ap_const_lv1_0) and (icmp_ln155_reg_1579 = ap_const_lv1_0) and (i_1_reg_1572 = ap_const_lv4_F))) or ((len = ap_const_lv3_1) and (icmp_ln164_reg_1583 = ap_const_lv1_0) and (icmp_ln155_reg_1579 = ap_const_lv1_0) and (i_1_reg_1572 = ap_const_lv4_D)));
    end process;


    ap_condition_72_assign_proc : process(icmp_ln155_reg_1579, icmp_ln164_reg_1583, len)
    begin
                ap_condition_72 <= ((len = ap_const_lv3_2) and (icmp_ln164_reg_1583 = ap_const_lv1_0) and (icmp_ln155_reg_1579 = ap_const_lv1_0));
    end process;


    ap_condition_720_assign_proc : process(icmp_ln155_reg_1579, icmp_ln164_reg_1583, len_read_reg_1568, i_1_reg_1572)
    begin
                ap_condition_720 <= ((((len_read_reg_1568 = ap_const_lv3_0) and (icmp_ln164_reg_1583 = ap_const_lv1_0) and (icmp_ln155_reg_1579 = ap_const_lv1_0) and (i_1_reg_1572 = ap_const_lv4_E)) or ((len_read_reg_1568 = ap_const_lv3_0) and (icmp_ln164_reg_1583 = ap_const_lv1_0) and (icmp_ln155_reg_1579 = ap_const_lv1_0) and (i_1_reg_1572 = ap_const_lv4_F))) or ((len_read_reg_1568 = ap_const_lv3_0) and (icmp_ln164_reg_1583 = ap_const_lv1_0) and (icmp_ln155_reg_1579 = ap_const_lv1_0) and (i_1_reg_1572 = ap_const_lv4_D)));
    end process;


    ap_condition_727_assign_proc : process(icmp_ln155_reg_1579, icmp_ln164_reg_1583, len, i_1_reg_1572)
    begin
                ap_condition_727 <= ((((len = ap_const_lv3_7) and (icmp_ln164_reg_1583 = ap_const_lv1_0) and (icmp_ln155_reg_1579 = ap_const_lv1_0) and (i_1_reg_1572 = ap_const_lv4_E)) or ((len = ap_const_lv3_7) and (icmp_ln164_reg_1583 = ap_const_lv1_0) and (icmp_ln155_reg_1579 = ap_const_lv1_0) and (i_1_reg_1572 = ap_const_lv4_F))) or ((len = ap_const_lv3_7) and (icmp_ln164_reg_1583 = ap_const_lv1_0) and (icmp_ln155_reg_1579 = ap_const_lv1_0) and (i_1_reg_1572 = ap_const_lv4_D)));
    end process;


    ap_condition_736_assign_proc : process(icmp_ln155_reg_1579, icmp_ln164_reg_1583, i_1_reg_1572)
    begin
                ap_condition_736 <= (((((icmp_ln164_reg_1583 = ap_const_lv1_1) and (icmp_ln155_reg_1579 = ap_const_lv1_0) and (i_1_reg_1572 = ap_const_lv4_E)) or ((icmp_ln164_reg_1583 = ap_const_lv1_1) and (icmp_ln155_reg_1579 = ap_const_lv1_0) and (i_1_reg_1572 = ap_const_lv4_F))) or ((icmp_ln164_reg_1583 = ap_const_lv1_1) and (icmp_ln155_reg_1579 = ap_const_lv1_0) and (i_1_reg_1572 = ap_const_lv4_D))) or ((icmp_ln164_reg_1583 = ap_const_lv1_1) and (icmp_ln155_reg_1579 = ap_const_lv1_0) and (i_1_reg_1572 = ap_const_lv4_0)));
    end process;


    ap_condition_743_assign_proc : process(icmp_ln155_reg_1579, i_1_reg_1572)
    begin
                ap_condition_743 <= ((((icmp_ln155_reg_1579 = ap_const_lv1_1) and (i_1_reg_1572 = ap_const_lv4_E)) or ((icmp_ln155_reg_1579 = ap_const_lv1_1) and (i_1_reg_1572 = ap_const_lv4_F))) or ((icmp_ln155_reg_1579 = ap_const_lv1_1) and (i_1_reg_1572 = ap_const_lv4_D)));
    end process;


    ap_condition_79_assign_proc : process(icmp_ln155_reg_1579, icmp_ln164_reg_1583, len)
    begin
                ap_condition_79 <= ((len = ap_const_lv3_1) and (icmp_ln164_reg_1583 = ap_const_lv1_0) and (icmp_ln155_reg_1579 = ap_const_lv1_0));
    end process;


    ap_condition_86_assign_proc : process(icmp_ln155_reg_1579, icmp_ln164_reg_1583, len)
    begin
                ap_condition_86 <= ((len = ap_const_lv3_7) and (icmp_ln164_reg_1583 = ap_const_lv1_0) and (icmp_ln155_reg_1579 = ap_const_lv1_0));
    end process;


    ap_condition_999_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1, i_1_reg_1572)
    begin
                ap_condition_999 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (i_1_reg_1572 = ap_const_lv4_A) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln153_fu_412_p2)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln153_fu_412_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_predicate_op134_read_state2_assign_proc : process(icmp_ln155_reg_1579, icmp_ln164_reg_1583, len)
    begin
                ap_predicate_op134_read_state2 <= ((len = ap_const_lv3_4) and (icmp_ln164_reg_1583 = ap_const_lv1_0) and (icmp_ln155_reg_1579 = ap_const_lv1_0));
    end process;


    ap_predicate_op168_read_state2_assign_proc : process(icmp_ln155_reg_1579, icmp_ln164_reg_1583, len)
    begin
                ap_predicate_op168_read_state2 <= ((len = ap_const_lv3_3) and (icmp_ln164_reg_1583 = ap_const_lv1_0) and (icmp_ln155_reg_1579 = ap_const_lv1_0));
    end process;


    ap_predicate_op201_read_state2_assign_proc : process(icmp_ln155_reg_1579, icmp_ln164_reg_1583, len)
    begin
                ap_predicate_op201_read_state2 <= ((len = ap_const_lv3_2) and (icmp_ln164_reg_1583 = ap_const_lv1_0) and (icmp_ln155_reg_1579 = ap_const_lv1_0));
    end process;


    ap_predicate_op233_read_state2_assign_proc : process(icmp_ln155_reg_1579, icmp_ln164_reg_1583, len)
    begin
                ap_predicate_op233_read_state2 <= ((len = ap_const_lv3_1) and (icmp_ln164_reg_1583 = ap_const_lv1_0) and (icmp_ln155_reg_1579 = ap_const_lv1_0));
    end process;


    ap_predicate_op292_read_state2_assign_proc : process(icmp_ln155_reg_1579, icmp_ln164_reg_1583, len)
    begin
                ap_predicate_op292_read_state2 <= ((len = ap_const_lv3_7) and (icmp_ln164_reg_1583 = ap_const_lv1_0) and (icmp_ln155_reg_1579 = ap_const_lv1_0));
    end process;


    ap_predicate_op63_read_state2_assign_proc : process(icmp_ln155_reg_1579, icmp_ln164_reg_1583, len)
    begin
                ap_predicate_op63_read_state2 <= ((len = ap_const_lv3_6) and (icmp_ln164_reg_1583 = ap_const_lv1_0) and (icmp_ln155_reg_1579 = ap_const_lv1_0));
    end process;


    ap_predicate_op99_read_state2_assign_proc : process(icmp_ln155_reg_1579, icmp_ln164_reg_1583, len)
    begin
                ap_predicate_op99_read_state2 <= ((len = ap_const_lv3_5) and (icmp_ln164_reg_1583 = ap_const_lv1_0) and (icmp_ln155_reg_1579 = ap_const_lv1_0));
    end process;

    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_1_assign_proc : process(ap_CS_fsm_pp0_stage0, i_fu_168, ap_loop_init, ap_block_pp0_stage0)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_i_1 <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_i_1 <= i_fu_168;
        end if; 
    end process;

    b_10_out <= b_10_fu_212;

    b_10_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln153_fu_412_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln153_fu_412_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            b_10_out_ap_vld <= ap_const_logic_1;
        else 
            b_10_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    b_11_out <= b_11_fu_216;

    b_11_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln153_fu_412_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln153_fu_412_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            b_11_out_ap_vld <= ap_const_logic_1;
        else 
            b_11_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    b_12_out <= b_12_fu_220;

    b_12_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln153_fu_412_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln153_fu_412_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            b_12_out_ap_vld <= ap_const_logic_1;
        else 
            b_12_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    b_13_out <= b_13_fu_224;

    b_13_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln153_fu_412_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln153_fu_412_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            b_13_out_ap_vld <= ap_const_logic_1;
        else 
            b_13_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    b_15_fu_885_p3 <= (trunc_ln177_fu_881_p1 & ap_const_lv56_80000000000000);
    b_16_fu_801_p4 <= ((trunc_ln184_fu_797_p1 & grp_fu_344_p4) & ap_const_lv48_800000000000);
    b_17_fu_715_p5 <= (((trunc_ln191_fu_711_p1 & grp_fu_344_p4) & grp_fu_354_p4) & ap_const_lv40_8000000000);
    b_18_fu_627_p6 <= ((((trunc_ln198_fu_623_p1 & grp_fu_344_p4) & grp_fu_354_p4) & grp_fu_364_p4) & ap_const_lv32_80000000);
    b_19_fu_537_p7 <= (((((trunc_ln206_fu_533_p1 & grp_fu_344_p4) & grp_fu_354_p4) & grp_fu_364_p4) & grp_fu_384_p4) & ap_const_lv24_800000);
    b_1_out <= b_1_fu_176;

    b_1_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln153_fu_412_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln153_fu_412_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            b_1_out_ap_vld <= ap_const_logic_1;
        else 
            b_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    b_20_fu_445_p8 <= ((((((trunc_ln214_fu_441_p1 & grp_fu_344_p4) & grp_fu_354_p4) & grp_fu_364_p4) & grp_fu_384_p4) & grp_fu_374_p4) & ap_const_lv16_8000);
    b_21_fu_1037_p9 <= (((((((trunc_ln223_fu_1033_p1 & grp_fu_344_p4) & grp_fu_354_p4) & grp_fu_364_p4) & grp_fu_384_p4) & grp_fu_374_p4) & grp_fu_394_p4) & ap_const_lv8_80);
    b_2_out <= b_2_fu_180;

    b_2_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln153_fu_412_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln153_fu_412_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            b_2_out_ap_vld <= ap_const_logic_1;
        else 
            b_2_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    b_3_out <= b_3_fu_184;

    b_3_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln153_fu_412_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln153_fu_412_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            b_3_out_ap_vld <= ap_const_logic_1;
        else 
            b_3_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    b_4_out <= b_4_fu_188;

    b_4_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln153_fu_412_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln153_fu_412_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            b_4_out_ap_vld <= ap_const_logic_1;
        else 
            b_4_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    b_5_out <= b_5_fu_192;

    b_5_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln153_fu_412_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln153_fu_412_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            b_5_out_ap_vld <= ap_const_logic_1;
        else 
            b_5_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    b_6_out <= b_6_fu_196;

    b_6_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln153_fu_412_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln153_fu_412_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            b_6_out_ap_vld <= ap_const_logic_1;
        else 
            b_6_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    b_7_out <= b_7_fu_200;

    b_7_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln153_fu_412_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln153_fu_412_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            b_7_out_ap_vld <= ap_const_logic_1;
        else 
            b_7_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    b_8_out <= b_8_fu_204;

    b_8_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln153_fu_412_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln153_fu_412_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            b_8_out_ap_vld <= ap_const_logic_1;
        else 
            b_8_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    b_9_out <= b_9_fu_208;

    b_9_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln153_fu_412_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln153_fu_412_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            b_9_out_ap_vld <= ap_const_logic_1;
        else 
            b_9_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    b_out <= b_fu_172;

    b_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln153_fu_412_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln153_fu_412_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            b_out_ap_vld <= ap_const_logic_1;
        else 
            b_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    core_msg_strm_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, core_msg_strm_empty_n, icmp_ln155_reg_1579, ap_predicate_op63_read_state2, ap_predicate_op99_read_state2, ap_predicate_op134_read_state2, ap_predicate_op168_read_state2, ap_predicate_op201_read_state2, ap_predicate_op233_read_state2, ap_predicate_op292_read_state2, ap_block_pp0_stage0_grp1)
    begin
        if ((((icmp_ln155_reg_1579 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1)) or ((ap_predicate_op292_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1)) or ((ap_predicate_op233_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1)) or ((ap_predicate_op201_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1)) or ((ap_predicate_op168_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1)) or ((ap_predicate_op134_read_state2 
    = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1)) or ((ap_predicate_op99_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1)) or ((ap_predicate_op63_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1)))) then 
            core_msg_strm_blk_n <= core_msg_strm_empty_n;
        else 
            core_msg_strm_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    core_msg_strm_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln155_reg_1579, ap_predicate_op63_read_state2, ap_predicate_op99_read_state2, ap_predicate_op134_read_state2, ap_predicate_op168_read_state2, ap_predicate_op201_read_state2, ap_predicate_op233_read_state2, ap_predicate_op292_read_state2, ap_block_pp0_stage0_11001_grp1)
    begin
        if ((((icmp_ln155_reg_1579 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) or ((ap_predicate_op292_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) or ((ap_predicate_op233_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) or ((ap_predicate_op201_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) or ((ap_predicate_op168_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) 
    or ((ap_predicate_op134_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) or ((ap_predicate_op99_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) or ((ap_predicate_op63_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)))) then 
            core_msg_strm_read <= ap_const_logic_1;
        else 
            core_msg_strm_read <= ap_const_logic_0;
        end if; 
    end process;

    empty_fu_1192_p1 <= core_msg_strm_dout(8 - 1 downto 0);
    grp_fu_344_p4 <= core_msg_strm_dout(15 downto 8);
    grp_fu_354_p4 <= core_msg_strm_dout(23 downto 16);
    grp_fu_364_p4 <= core_msg_strm_dout(31 downto 24);
    grp_fu_374_p4 <= core_msg_strm_dout(47 downto 40);
    grp_fu_384_p4 <= core_msg_strm_dout(39 downto 32);
    grp_fu_394_p4 <= core_msg_strm_dout(55 downto 48);
    icmp_ln153_fu_412_p2 <= "1" when (ap_sig_allocacmp_i_1 = ap_const_lv4_E) else "0";
    icmp_ln155_fu_424_p2 <= "1" when (unsigned(ap_sig_allocacmp_i_1) < unsigned(shr_i2380_cast)) else "0";
    icmp_ln164_fu_430_p2 <= "1" when (unsigned(ap_sig_allocacmp_i_1) > unsigned(shr_i2380_cast)) else "0";
    l_24_fu_1206_p9 <= (((((((empty_fu_1192_p1 & grp_fu_344_p4) & grp_fu_354_p4) & grp_fu_364_p4) & grp_fu_384_p4) & grp_fu_374_p4) & grp_fu_394_p4) & p_s_fu_1196_p4);
    len_read_reg_1568 <= len;
    p_s_fu_1196_p4 <= core_msg_strm_dout(63 downto 56);
    trunc_ln177_fu_881_p1 <= core_msg_strm_dout(8 - 1 downto 0);
    trunc_ln184_fu_797_p1 <= core_msg_strm_dout(8 - 1 downto 0);
    trunc_ln191_fu_711_p1 <= core_msg_strm_dout(8 - 1 downto 0);
    trunc_ln198_fu_623_p1 <= core_msg_strm_dout(8 - 1 downto 0);
    trunc_ln206_fu_533_p1 <= core_msg_strm_dout(8 - 1 downto 0);
    trunc_ln214_fu_441_p1 <= core_msg_strm_dout(8 - 1 downto 0);
    trunc_ln223_fu_1033_p1 <= core_msg_strm_dout(8 - 1 downto 0);
end behav;
