// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module test_core_to_axis (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        core_digest_strm_dout,
        core_digest_strm_empty_n,
        core_digest_strm_read,
        core_digest_strm_num_data_valid,
        core_digest_strm_fifo_cap,
        core_end_digest_strm_dout,
        core_end_digest_strm_empty_n,
        core_end_digest_strm_read,
        core_end_digest_strm_num_data_valid,
        core_end_digest_strm_fifo_cap,
        digest_strm_TDATA,
        digest_strm_TVALID,
        digest_strm_TREADY,
        digest_strm_TKEEP,
        digest_strm_TSTRB,
        digest_strm_TLAST,
        digest_strm_TDEST,
        dest_id_dout,
        dest_id_empty_n,
        dest_id_read,
        dest_id_num_data_valid,
        dest_id_fifo_cap
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [255:0] core_digest_strm_dout;
input   core_digest_strm_empty_n;
output   core_digest_strm_read;
input  [2:0] core_digest_strm_num_data_valid;
input  [2:0] core_digest_strm_fifo_cap;
input  [0:0] core_end_digest_strm_dout;
input   core_end_digest_strm_empty_n;
output   core_end_digest_strm_read;
input  [2:0] core_end_digest_strm_num_data_valid;
input  [2:0] core_end_digest_strm_fifo_cap;
output  [255:0] digest_strm_TDATA;
output   digest_strm_TVALID;
input   digest_strm_TREADY;
output  [31:0] digest_strm_TKEEP;
output  [31:0] digest_strm_TSTRB;
output  [0:0] digest_strm_TLAST;
output  [2:0] digest_strm_TDEST;
input  [1:0] dest_id_dout;
input   dest_id_empty_n;
output   dest_id_read;
input  [2:0] dest_id_num_data_valid;
input  [2:0] dest_id_fifo_cap;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg dest_id_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    dest_id_blk_n;
reg   [1:0] dest_id_1_reg_101;
reg    ap_block_state1;
wire    grp_core_to_axis_Pipeline_DRAIN_LOOP_fu_60_ap_start;
wire    grp_core_to_axis_Pipeline_DRAIN_LOOP_fu_60_ap_done;
wire    grp_core_to_axis_Pipeline_DRAIN_LOOP_fu_60_ap_idle;
wire    grp_core_to_axis_Pipeline_DRAIN_LOOP_fu_60_ap_ready;
wire    grp_core_to_axis_Pipeline_DRAIN_LOOP_fu_60_core_end_digest_strm_read;
wire    grp_core_to_axis_Pipeline_DRAIN_LOOP_fu_60_core_digest_strm_read;
wire    grp_core_to_axis_Pipeline_DRAIN_LOOP_fu_60_digest_strm_TREADY;
wire   [255:0] grp_core_to_axis_Pipeline_DRAIN_LOOP_fu_60_digest_strm_TDATA;
wire    grp_core_to_axis_Pipeline_DRAIN_LOOP_fu_60_digest_strm_TVALID;
wire   [31:0] grp_core_to_axis_Pipeline_DRAIN_LOOP_fu_60_digest_strm_TKEEP;
wire   [31:0] grp_core_to_axis_Pipeline_DRAIN_LOOP_fu_60_digest_strm_TSTRB;
wire   [0:0] grp_core_to_axis_Pipeline_DRAIN_LOOP_fu_60_digest_strm_TLAST;
wire   [2:0] grp_core_to_axis_Pipeline_DRAIN_LOOP_fu_60_digest_strm_TDEST;
reg    grp_core_to_axis_Pipeline_DRAIN_LOOP_fu_60_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg   [255:0] digest_strm_TDATA_reg;
reg   [31:0] digest_strm_TKEEP_reg;
reg   [31:0] digest_strm_TSTRB_reg;
reg   [0:0] digest_strm_TLAST_reg;
reg   [2:0] digest_strm_TDEST_reg;
wire    ap_CS_fsm_state4;
wire    regslice_both_digest_strm_V_data_V_U_apdone_blk;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
reg   [255:0] digest_strm_TDATA_int_regslice;
wire    digest_strm_TVALID_int_regslice;
wire    digest_strm_TREADY_int_regslice;
wire    regslice_both_digest_strm_V_data_V_U_vld_out;
wire    regslice_both_digest_strm_V_keep_V_U_apdone_blk;
reg   [31:0] digest_strm_TKEEP_int_regslice;
wire    regslice_both_digest_strm_V_keep_V_U_ack_in_dummy;
wire    regslice_both_digest_strm_V_keep_V_U_vld_out;
wire    regslice_both_digest_strm_V_strb_V_U_apdone_blk;
reg   [31:0] digest_strm_TSTRB_int_regslice;
wire    regslice_both_digest_strm_V_strb_V_U_ack_in_dummy;
wire    regslice_both_digest_strm_V_strb_V_U_vld_out;
wire    regslice_both_digest_strm_V_last_V_U_apdone_blk;
reg   [0:0] digest_strm_TLAST_int_regslice;
wire    regslice_both_digest_strm_V_last_V_U_ack_in_dummy;
wire    regslice_both_digest_strm_V_last_V_U_vld_out;
wire    regslice_both_digest_strm_V_dest_V_U_apdone_blk;
reg   [2:0] digest_strm_TDEST_int_regslice;
wire    regslice_both_digest_strm_V_dest_V_U_ack_in_dummy;
wire    regslice_both_digest_strm_V_dest_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 grp_core_to_axis_Pipeline_DRAIN_LOOP_fu_60_ap_start_reg = 1'b0;
end

test_core_to_axis_Pipeline_DRAIN_LOOP grp_core_to_axis_Pipeline_DRAIN_LOOP_fu_60(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_core_to_axis_Pipeline_DRAIN_LOOP_fu_60_ap_start),
    .ap_done(grp_core_to_axis_Pipeline_DRAIN_LOOP_fu_60_ap_done),
    .ap_idle(grp_core_to_axis_Pipeline_DRAIN_LOOP_fu_60_ap_idle),
    .ap_ready(grp_core_to_axis_Pipeline_DRAIN_LOOP_fu_60_ap_ready),
    .core_end_digest_strm_dout(core_end_digest_strm_dout),
    .core_end_digest_strm_empty_n(core_end_digest_strm_empty_n),
    .core_end_digest_strm_read(grp_core_to_axis_Pipeline_DRAIN_LOOP_fu_60_core_end_digest_strm_read),
    .core_end_digest_strm_num_data_valid(3'd0),
    .core_end_digest_strm_fifo_cap(3'd0),
    .core_digest_strm_dout(core_digest_strm_dout),
    .core_digest_strm_empty_n(core_digest_strm_empty_n),
    .core_digest_strm_read(grp_core_to_axis_Pipeline_DRAIN_LOOP_fu_60_core_digest_strm_read),
    .core_digest_strm_num_data_valid(3'd0),
    .core_digest_strm_fifo_cap(3'd0),
    .digest_strm_TREADY(grp_core_to_axis_Pipeline_DRAIN_LOOP_fu_60_digest_strm_TREADY),
    .out_pkt_dest(dest_id_1_reg_101),
    .digest_strm_TDATA(grp_core_to_axis_Pipeline_DRAIN_LOOP_fu_60_digest_strm_TDATA),
    .digest_strm_TVALID(grp_core_to_axis_Pipeline_DRAIN_LOOP_fu_60_digest_strm_TVALID),
    .digest_strm_TKEEP(grp_core_to_axis_Pipeline_DRAIN_LOOP_fu_60_digest_strm_TKEEP),
    .digest_strm_TSTRB(grp_core_to_axis_Pipeline_DRAIN_LOOP_fu_60_digest_strm_TSTRB),
    .digest_strm_TLAST(grp_core_to_axis_Pipeline_DRAIN_LOOP_fu_60_digest_strm_TLAST),
    .digest_strm_TDEST(grp_core_to_axis_Pipeline_DRAIN_LOOP_fu_60_digest_strm_TDEST)
);

test_regslice_both #(
    .DataWidth( 256 ))
regslice_both_digest_strm_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(digest_strm_TDATA_int_regslice),
    .vld_in(grp_core_to_axis_Pipeline_DRAIN_LOOP_fu_60_digest_strm_TVALID),
    .ack_in(digest_strm_TREADY_int_regslice),
    .data_out(digest_strm_TDATA),
    .vld_out(regslice_both_digest_strm_V_data_V_U_vld_out),
    .ack_out(digest_strm_TREADY),
    .apdone_blk(regslice_both_digest_strm_V_data_V_U_apdone_blk)
);

test_regslice_both #(
    .DataWidth( 32 ))
regslice_both_digest_strm_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(digest_strm_TKEEP_int_regslice),
    .vld_in(grp_core_to_axis_Pipeline_DRAIN_LOOP_fu_60_digest_strm_TVALID),
    .ack_in(regslice_both_digest_strm_V_keep_V_U_ack_in_dummy),
    .data_out(digest_strm_TKEEP),
    .vld_out(regslice_both_digest_strm_V_keep_V_U_vld_out),
    .ack_out(digest_strm_TREADY),
    .apdone_blk(regslice_both_digest_strm_V_keep_V_U_apdone_blk)
);

test_regslice_both #(
    .DataWidth( 32 ))
regslice_both_digest_strm_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(digest_strm_TSTRB_int_regslice),
    .vld_in(grp_core_to_axis_Pipeline_DRAIN_LOOP_fu_60_digest_strm_TVALID),
    .ack_in(regslice_both_digest_strm_V_strb_V_U_ack_in_dummy),
    .data_out(digest_strm_TSTRB),
    .vld_out(regslice_both_digest_strm_V_strb_V_U_vld_out),
    .ack_out(digest_strm_TREADY),
    .apdone_blk(regslice_both_digest_strm_V_strb_V_U_apdone_blk)
);

test_regslice_both #(
    .DataWidth( 1 ))
regslice_both_digest_strm_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(digest_strm_TLAST_int_regslice),
    .vld_in(grp_core_to_axis_Pipeline_DRAIN_LOOP_fu_60_digest_strm_TVALID),
    .ack_in(regslice_both_digest_strm_V_last_V_U_ack_in_dummy),
    .data_out(digest_strm_TLAST),
    .vld_out(regslice_both_digest_strm_V_last_V_U_vld_out),
    .ack_out(digest_strm_TREADY),
    .apdone_blk(regslice_both_digest_strm_V_last_V_U_apdone_blk)
);

test_regslice_both #(
    .DataWidth( 3 ))
regslice_both_digest_strm_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(digest_strm_TDEST_int_regslice),
    .vld_in(grp_core_to_axis_Pipeline_DRAIN_LOOP_fu_60_digest_strm_TVALID),
    .ack_in(regslice_both_digest_strm_V_dest_V_U_ack_in_dummy),
    .data_out(digest_strm_TDEST),
    .vld_out(regslice_both_digest_strm_V_dest_V_U_vld_out),
    .ack_out(digest_strm_TREADY),
    .apdone_blk(regslice_both_digest_strm_V_dest_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state4) & (regslice_both_digest_strm_V_data_V_U_apdone_blk == 1'b0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_core_to_axis_Pipeline_DRAIN_LOOP_fu_60_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_core_to_axis_Pipeline_DRAIN_LOOP_fu_60_ap_start_reg <= 1'b1;
        end else if ((grp_core_to_axis_Pipeline_DRAIN_LOOP_fu_60_ap_ready == 1'b1)) begin
            grp_core_to_axis_Pipeline_DRAIN_LOOP_fu_60_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        dest_id_1_reg_101 <= dest_id_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_core_to_axis_Pipeline_DRAIN_LOOP_fu_60_digest_strm_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        digest_strm_TDATA_reg <= grp_core_to_axis_Pipeline_DRAIN_LOOP_fu_60_digest_strm_TDATA;
        digest_strm_TDEST_reg <= grp_core_to_axis_Pipeline_DRAIN_LOOP_fu_60_digest_strm_TDEST;
        digest_strm_TKEEP_reg <= grp_core_to_axis_Pipeline_DRAIN_LOOP_fu_60_digest_strm_TKEEP;
        digest_strm_TLAST_reg <= grp_core_to_axis_Pipeline_DRAIN_LOOP_fu_60_digest_strm_TLAST;
        digest_strm_TSTRB_reg <= grp_core_to_axis_Pipeline_DRAIN_LOOP_fu_60_digest_strm_TSTRB;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_core_to_axis_Pipeline_DRAIN_LOOP_fu_60_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_digest_strm_V_data_V_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (regslice_both_digest_strm_V_data_V_U_apdone_blk == 1'b0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (regslice_both_digest_strm_V_data_V_U_apdone_blk == 1'b0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        dest_id_blk_n = dest_id_empty_n;
    end else begin
        dest_id_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        dest_id_read = 1'b1;
    end else begin
        dest_id_read = 1'b0;
    end
end

always @ (*) begin
    if (((grp_core_to_axis_Pipeline_DRAIN_LOOP_fu_60_digest_strm_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        digest_strm_TDATA_int_regslice = grp_core_to_axis_Pipeline_DRAIN_LOOP_fu_60_digest_strm_TDATA;
    end else begin
        digest_strm_TDATA_int_regslice = digest_strm_TDATA_reg;
    end
end

always @ (*) begin
    if (((grp_core_to_axis_Pipeline_DRAIN_LOOP_fu_60_digest_strm_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        digest_strm_TDEST_int_regslice = grp_core_to_axis_Pipeline_DRAIN_LOOP_fu_60_digest_strm_TDEST;
    end else begin
        digest_strm_TDEST_int_regslice = digest_strm_TDEST_reg;
    end
end

always @ (*) begin
    if (((grp_core_to_axis_Pipeline_DRAIN_LOOP_fu_60_digest_strm_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        digest_strm_TKEEP_int_regslice = grp_core_to_axis_Pipeline_DRAIN_LOOP_fu_60_digest_strm_TKEEP;
    end else begin
        digest_strm_TKEEP_int_regslice = digest_strm_TKEEP_reg;
    end
end

always @ (*) begin
    if (((grp_core_to_axis_Pipeline_DRAIN_LOOP_fu_60_digest_strm_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        digest_strm_TLAST_int_regslice = grp_core_to_axis_Pipeline_DRAIN_LOOP_fu_60_digest_strm_TLAST;
    end else begin
        digest_strm_TLAST_int_regslice = digest_strm_TLAST_reg;
    end
end

always @ (*) begin
    if (((grp_core_to_axis_Pipeline_DRAIN_LOOP_fu_60_digest_strm_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        digest_strm_TSTRB_int_regslice = grp_core_to_axis_Pipeline_DRAIN_LOOP_fu_60_digest_strm_TSTRB;
    end else begin
        digest_strm_TSTRB_int_regslice = digest_strm_TSTRB_reg;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_core_to_axis_Pipeline_DRAIN_LOOP_fu_60_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (regslice_both_digest_strm_V_data_V_U_apdone_blk == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (dest_id_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign core_digest_strm_read = grp_core_to_axis_Pipeline_DRAIN_LOOP_fu_60_core_digest_strm_read;

assign core_end_digest_strm_read = grp_core_to_axis_Pipeline_DRAIN_LOOP_fu_60_core_end_digest_strm_read;

assign digest_strm_TVALID = regslice_both_digest_strm_V_data_V_U_vld_out;

assign digest_strm_TVALID_int_regslice = grp_core_to_axis_Pipeline_DRAIN_LOOP_fu_60_digest_strm_TVALID;

assign grp_core_to_axis_Pipeline_DRAIN_LOOP_fu_60_ap_start = grp_core_to_axis_Pipeline_DRAIN_LOOP_fu_60_ap_start_reg;

assign grp_core_to_axis_Pipeline_DRAIN_LOOP_fu_60_digest_strm_TREADY = (digest_strm_TREADY_int_regslice & ap_CS_fsm_state3);

endmodule //test_core_to_axis
